/**
 * ARTIFACT_KNOWLEDGE_BASE.js
 * NetHack 5.0 (3.7) 全固有アーティファクト構造化ナレッジ Single Source of Truth
 * 
 * NetHack の include/artilist.h に基づく全33種の固有アーティファクト
 * （一般・神授アーティファクト20種 + 13職業クエストアーティファクト13種）の
 * ベースアイテム、アライメント、専用職業、付与耐性、攻撃/防御特殊効果、#invoke効果を完全定義します。
 */

export const ARTIFACT_KNOWLEDGE_BASE = [
    // -------------------------------------------------------------
    // 1. 一般・神授アーティファクト (20種)
    // -------------------------------------------------------------
    {
        id: 'art_excalibur',
        name: 'Excalibur',
        nameJa: 'エクスカリバー',
        baseName: 'long sword',
        baseOnum: 54,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: 'knight',
        race: null,
        isQuestArtifact: false,
        intrinsics: ['searching', 'stealth'],
        attackEffect: '追加物理(+1d10)、対アンデッド・デーモン大打撃、暗視付与、解呪',
        defenseEffect: '生命力吸収耐性 (Drain Resistance)',
        invoke: null,
        descJa: 'アーサー王伝説の聖剣。秩序のキャラクターが長剣を泉に浸す（#dip）ことで鍛造可能。自動探索・隠密・生命力吸収耐性を備え、アンデッドやデーモンに絶大な威力を誇る万能の名剣。',
        descEn: 'The legendary sword of King Arthur. Lawful characters can forge it by dipping a long sword into a fountain (#dip). Grants searching, stealth, and drain resistance.'
    },
    {
        id: 'art_stormbringer',
        name: 'Stormbringer',
        nameJa: 'ストームブリンガー',
        baseName: 'runesword',
        baseOnum: 58,
        category: 'WEAPON',
        alignment: 'CHAOTIC',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['drain_res'],
        attackEffect: '生命力吸収(レベル・HPドレイン)、暴走攻撃(周囲の友好NPCも無差別攻撃)',
        defenseEffect: '生命力吸収耐性',
        invoke: null,
        descJa: 'エルリックサーガの魔剣。相手の生命力を吸い取りHPを回復する。血に飢えた意志を持ち、平和なペットや店主にも勝手に斬りかかる暴走リスクがあるため扱いには注意が必要。',
        descEn: 'The cursed runesword of Elric of Melniboné. Drains levels from foes, but has a bloodthirsty will that may attack peaceful allies.'
    },
    {
        id: 'art_mjollnir',
        name: 'Mjollnir',
        nameJa: 'ミョルニル',
        baseName: 'war hammer',
        baseOnum: 76,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: 'valkyrie',
        race: null,
        isQuestArtifact: false,
        intrinsics: ['shock_res'],
        attackEffect: '電撃大ダメージ(+1d24)、筋力25で投擲可能（ワルキューレなら手元に戻る）',
        defenseEffect: '電撃耐性',
        invoke: null,
        descJa: 'トール神の雷神の槌。打撃時に激しい電撃ダメージを与える。筋力25（巨人の力の手袋等）で投げることができ、ワルキューレならブーメランのように手元に戻ってくる。',
        descEn: 'The hammer of Thor. Deals massive lightning damage (+1d24). Can be thrown with 25 Strength, and returns to Valkyries.'
    },
    {
        id: 'art_cleaver',
        name: 'Cleaver',
        nameJa: 'クリバー',
        baseName: 'battle-axe',
        baseOnum: 45,
        category: 'WEAPON',
        alignment: 'CHAOTIC',
        role: 'barbarian',
        race: null,
        isQuestArtifact: false,
        intrinsics: [],
        attackEffect: '追加物理ダメージ(+1d6)',
        defenseEffect: null,
        invoke: null,
        descJa: 'バーバリアンへの神の贈り物大斧。高い基本攻撃力に加えて追加物理ダメージを与える純粋な破壊兵器。',
        descEn: 'A brutal battle-axe favored by Barbarians. Deals bonus physical damage (+1d6).'
    },
    {
        id: 'art_grimtooth',
        name: 'Grimtooth',
        nameJa: 'グリムトゥース',
        baseName: 'orcish dagger',
        baseOnum: 36,
        category: 'WEAPON',
        alignment: 'CHAOTIC',
        role: null,
        race: 'orc',
        isQuestArtifact: false,
        intrinsics: ['warning_elf'],
        attackEffect: '追加物理ダメージ(+1d6)、毒攻撃',
        defenseEffect: '毒耐性',
        invoke: '毒の放射 (Fling Poison)',
        descJa: 'オーク一族の毒短剣。エルフが接近すると赤く光って警告する。敵に毒を与え、#invokeで毒を浴びせる。',
        descEn: 'An orcish dagger that glows red in warning of elves. Deals poison damage, and can fling poison via #invoke.'
    },
    {
        id: 'art_orcrist',
        name: 'Orcrist',
        nameJa: 'オルクリスト',
        baseName: 'elven broadsword',
        baseOnum: 53,
        category: 'WEAPON',
        alignment: 'CHAOTIC',
        role: null,
        race: 'elf',
        isQuestArtifact: false,
        intrinsics: ['warning_orc'],
        attackEffect: '対オーク追加物理ダメージ(+1d10)',
        defenseEffect: null,
        invoke: null,
        descJa: 'エルフの名剣（ゴブリン斬り）。オークが周囲にいると青く輝いて警告を発し、オークに対して大ダメージを与える。',
        descEn: 'The Goblin-cleaver forged in Gondolin. Warns of nearby orcs with a blue glow and deals heavy bonus damage against them.'
    },
    {
        id: 'art_sting',
        name: 'Sting',
        nameJa: 'スティング (つらぬき丸)',
        baseName: 'elven dagger',
        baseOnum: 35,
        category: 'WEAPON',
        alignment: 'CHAOTIC',
        role: null,
        race: 'elf',
        isQuestArtifact: false,
        intrinsics: ['warning_orc'],
        attackEffect: '対オーク追加物理ダメージ(+1d5)',
        defenseEffect: null,
        invoke: null,
        descJa: 'ホビットが手にしたエルフの短剣。オークの接近を青い光で警告する。床にエルベレスの文字を刻む道具としても便利。',
        descEn: 'The elven dagger carried by Bilbo and Frodo Baggins. Glows blue when orcs are near, and excels at carving Elbereth.'
    },
    {
        id: 'art_magicbane',
        name: 'Magicbane',
        nameJa: 'マジックベイン',
        baseName: 'athame',
        baseOnum: 38,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: 'wizard',
        race: null,
        isQuestArtifact: false,
        intrinsics: ['magic_res'],
        attackEffect: '魔法攻撃、気絶、混乱、恐怖、テレポート',
        defenseEffect: '95%の呪文・魔法攻撃を無効化 (Magic Resistance)',
        invoke: null,
        descJa: '魔法使いの最高峰アサメ。敵の呪文や魔法攻撃を高確率で無力化する。床にエルベレス（E-word）を刃こぼれなしで高速刻印できる最重要防衛武具。',
        descEn: 'The premier athame for Wizards. Absorbs magic attacks with 95% effectiveness and engraves permanent Elbereth safely.'
    },
    {
        id: 'art_frost_brand',
        name: 'Frost Brand',
        nameJa: 'フロストブランド',
        baseName: 'long sword',
        baseOnum: 54,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['cold_res'],
        attackEffect: '冷気2倍ダメージ (非冷気耐性モンスターに対してダメージ2倍)',
        defenseEffect: '冷気耐性',
        invoke: '吹雪の召喚 (Snowstorm)',
        descJa: '冷気属性の魔剣。冷気耐性を持たないモンスターに対して与えるダメージが2倍になる屈指の高火力武器。#invokeで吹雪を呼ぶ。',
        descEn: 'A magical long sword dealing double damage against non-cold-resistant foes. Grants cold resistance and invokes snowstorm.'
    },
    {
        id: 'art_fire_brand',
        name: 'Fire Brand',
        nameJa: 'ファイアブランド',
        baseName: 'long sword',
        baseOnum: 54,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['fire_res'],
        attackEffect: '火炎2倍ダメージ (非火炎耐性モンスターに対してダメージ2倍)',
        defenseEffect: '火炎耐性',
        invoke: '火炎嵐の召喚 (Firestorm)',
        descJa: '火炎属性の魔剣。火炎耐性を持たない敵に対してダメージが2倍になる。冷気系モンスターやアンデッドに絶大な威力を誇る。#invokeで火炎嵐を呼ぶ。',
        descEn: 'A magical long sword dealing double damage against non-fire-resistant targets. Grants fire resistance and invokes firestorm.'
    },
    {
        id: 'art_dragonbane',
        name: 'Dragonbane',
        nameJa: 'ドラゴンベイン',
        baseName: 'broadsword',
        baseOnum: 52,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['reflection'],
        attackEffect: '対ドラゴン2倍ダメージ',
        defenseEffect: '反射 (Reflection: ブレス・光線を跳ね返す)',
        invoke: null,
        descJa: 'ドラゴン討伐のために鍛えられた幅広剣。ドラゴンに対して2倍ダメージを与え、さらに反射（ブレスや破壊光線を跳ね返す）の特性を持つ。',
        descEn: 'A broadsword forged to slay dragons. Deals double damage against dragons and provides reflection.'
    },
    {
        id: 'art_demonbane',
        name: 'Demonbane',
        nameJa: 'デーモンベイン',
        baseName: 'silver mace',
        baseOnum: 74,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: 'cleric',
        race: null,
        isQuestArtifact: false,
        intrinsics: [],
        attackEffect: '対デーモン2倍ダメージ、銀特効(+1d20)',
        defenseEffect: null,
        invoke: 'デーモン追放 (Banish demon)',
        descJa: '悪魔を滅ぼす銀のメイス。大悪魔やデーモン全般に2倍ダメージを与え、銀製のため銀脆弱モンスターにも追加ダメージ。#invokeでデーモンを異界へ追放する。',
        descEn: 'A silver mace blessed against infernal beings. Deals double damage to demons plus silver damage bonus. Invoking it banishes demons.'
    },
    {
        id: 'art_werebane',
        name: 'Werebane',
        nameJa: 'ウェアベイン',
        baseName: 'silver saber',
        baseOnum: 51,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: [],
        attackEffect: '対獣人2倍ダメージ、銀特効(+1d20)',
        defenseEffect: '獣人化感染防止 (Prevent Lycanthropy)',
        invoke: null,
        descJa: '人狼（ウェアウルフ）や人ネズミ等の獣人を狩る銀のサーベル。攻撃時の大打撃に加え、獣人症の感染を完全に防ぐ。',
        descEn: 'A silver saber effective against were-creatures. Protects the wielder from lycanthropy infection.'
    },
    {
        id: 'art_grayswandir',
        name: 'Grayswandir',
        nameJa: 'グレイスワンダー',
        baseName: 'silver saber',
        baseOnum: 51,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['halluc_res'],
        attackEffect: '物理2倍ダメージ、銀特効(+1d20)',
        defenseEffect: '幻覚耐性 (Hallucination Resistance)',
        invoke: null,
        descJa: 'アンバーのコルヴィン王子の愛剣。すべての敵に対して無条件で2倍ダメージを与え、さらに銀特効ダメージが加算されるNetHack屈指の最強片手剣。幻覚耐性も付与。',
        descEn: 'The silver saber of Prince Corwin of Amber. Deals double physical damage to all enemies plus silver damage bonus, and grants hallucination resistance.'
    },
    {
        id: 'art_giantslayer',
        name: 'Giantslayer',
        nameJa: 'ジャイアントスレイヤー',
        baseName: 'long sword',
        baseOnum: 54,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: [],
        attackEffect: '対巨人2倍ダメージ',
        defenseEffect: null,
        invoke: null,
        descJa: '巨人を倒すための長剣。サイクロプス、巨人、ミノタウロス等の大型人型種に対して2倍ダメージを与える。',
        descEn: 'A long sword crafted to fell giants. Deals double damage against all giant-class foes.'
    },
    {
        id: 'art_ogresmasher',
        name: 'Ogresmasher',
        nameJa: 'オーガスマッシャー',
        baseName: 'war hammer',
        baseOnum: 76,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['str_boost'],
        attackEffect: '対オーガ2倍ダメージ、装備時筋力18に上昇',
        defenseEffect: null,
        invoke: null,
        descJa: 'オーガを粉砕する戦槌。装備するだけで筋力を18まで底上げし、オーガ族に特効を与える。',
        descEn: 'A war hammer that raises Strength to 18 when wielded and deals double damage to ogres.'
    },
    {
        id: 'art_trollsbane',
        name: 'Trollsbane',
        nameJa: 'トロールスベイン',
        baseName: 'morning star',
        baseOnum: 75,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['regeneration'],
        attackEffect: '対トロール2倍ダメージ、トロールの死体復活阻止',
        defenseEffect: null,
        invoke: null,
        descJa: 'トロールを狩るトゲ付き鉄球。倒したトロールが復活するのを阻止し、所持者に再生能力を付与する。',
        descEn: 'A morning star that prevents slain trolls from reviving and grants regeneration.'
    },
    {
        id: 'art_vorpal_blade',
        name: 'Vorpal Blade',
        nameJa: '首切りの剣 (ボーパルブレード)',
        baseName: 'long sword',
        baseOnum: 54,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: [],
        attackEffect: '首切り即死 (約5%の確率で敵の首を切り飛ばして即死させる)',
        defenseEffect: null,
        invoke: null,
        descJa: 'ルイス・キャロルの詩『ジャバウォックの詩』に登場する魔剣。攻撃時に「スニッカー・スナック！」と音を立て、一定確率で敵の首を跳ね飛ばして即死させる。',
        descEn: 'The vorpal sword goes snicker-snack! Has an approximate 5% chance per hit to behead foes instantly.'
    },
    {
        id: 'art_snickersnee',
        name: 'Snickersnee',
        nameJa: 'スニッカースニー',
        baseName: 'katana',
        baseOnum: 56,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: 'samurai',
        race: null,
        isQuestArtifact: false,
        intrinsics: [],
        attackEffect: '追加物理ダメージ(+1d8)',
        defenseEffect: null,
        invoke: null,
        descJa: '歌劇『ミカド』に由来する鋭利な刀。侍や観光客が二刀流で愛用する高威力の刀。',
        descEn: 'A razor-sharp katana from Gilbert and Sullivan\'s The Mikado. Adds +1d8 damage on every strike.'
    },
    {
        id: 'art_sunsword',
        name: 'Sunsword',
        nameJa: 'サンソード',
        baseName: 'long sword',
        baseOnum: 54,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: null,
        race: null,
        isQuestArtifact: false,
        intrinsics: ['light'],
        attackEffect: '対アンデッド・悪魔2倍ダメージ、装備時に周囲を常時照明',
        defenseEffect: '盲目耐性 (Blindness Resistance)',
        invoke: '目眩まし光線 (Blinding Ray)',
        descJa: '太陽の輝きを宿す聖剣。抜くだけで周囲を明るく照らし、盲目を防ぐ。アンデッドやデーモンに対して2倍ダメージを与え、#invokeで光線を放つ。',
        descEn: 'A blazing holy sword that lights up the dark, grants blindness resistance, and deals double damage to undead and demons.'
    },

    // -------------------------------------------------------------
    // 2. 13職業クエストアーティファクト (13種)
    // -------------------------------------------------------------
    {
        id: 'art_orb_of_detection',
        name: 'The Orb of Detection',
        nameJa: '探求の宝珠',
        baseName: 'crystal ball',
        baseOnum: 231,
        category: 'TOOL',
        alignment: 'LAWFUL',
        role: 'archeologist',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['esp', 'magic_res_carry'],
        attackEffect: null,
        defenseEffect: '所持で魔法防御 (Carry Magic Resistance)',
        invoke: '透明化 (Invisibility)',
        descJa: '考古学者のクエストアーティファクト。インベントリに所持しているだけでテレパシーと魔法防御を得る。呼び出し（#invoke）で透明化が可能。',
        descEn: 'The quest artifact of Archeologists. Grants ESP and magic resistance while carried. Invoking grants invisibility.'
    },
    {
        id: 'art_heart_of_ahriman',
        name: 'The Heart of Ahriman',
        nameJa: 'アリマンの心臓',
        baseName: 'luckstone',
        baseOnum: 470,
        category: 'GEM',
        alignment: 'NEUTRAL',
        role: 'barbarian',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['luck', 'stealth'],
        attackEffect: '投擲時に2倍ダメージ',
        defenseEffect: null,
        invoke: '浮遊 (Levitation)',
        descJa: 'バーバリアンのクエストアーティファクト。所持で幸運と隠密。スリング等で投げると2倍ダメージを与える。呼び出しで浮遊状態になれる。',
        descEn: 'The quest artifact of Barbarians. Acts as a luckstone with stealth. Deals double damage when thrown, and invokes levitation.'
    },
    {
        id: 'art_sceptre_of_might',
        name: 'The Sceptre of Might',
        nameJa: '力の笏',
        baseName: 'mace',
        baseOnum: 73,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: 'caveman',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['magic_res_wield'],
        attackEffect: '異アライメントに2倍物理ダメージ',
        defenseEffect: '装備で魔法防御',
        invoke: '闘争の発生 (Conflict)',
        descJa: '原始人のクエストアーティファクト。装備で魔法防御。他属性の敵に2倍ダメージ。呼び出しで周囲の敵同士を戦わせる闘争状態（Conflict）を発生させる。',
        descEn: 'The quest artifact of Cavemen. Deals double damage to cross-aligned foes, grants magic resistance when wielded, and invokes conflict.'
    },
    {
        id: 'art_staff_of_aesculapius',
        name: 'The Staff of Aesculapius',
        nameJa: 'アスクレピオスの杖',
        baseName: 'quarterstaff',
        baseOnum: 79,
        category: 'WEAPON',
        alignment: 'NEUTRAL',
        role: 'healer',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['drain_res', 'regeneration'],
        attackEffect: '生命力吸収(レベル・HPドレイン)',
        defenseEffect: '生命力吸収耐性',
        invoke: '完全治癒 (Full Healing)',
        descJa: '治癒師のクエストアーティファクト。生命力吸収耐性と再生。攻撃時に敵の生命力を吸い取り、呼び出し（#invoke）でHP・病気・盲目を完全回復する究極の医療杖。',
        descEn: 'The quest artifact of Healers. Drains levels on hit, provides drain resistance and regeneration, and invokes full healing.'
    },
    {
        id: 'art_magic_mirror_of_merlin',
        name: 'The Magic Mirror of Merlin',
        nameJa: 'マーリンの魔法鏡',
        baseName: 'mirror',
        baseOnum: 230,
        category: 'TOOL',
        alignment: 'LAWFUL',
        role: 'knight',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['esp', 'magic_res_carry', 'telepathy'],
        attackEffect: '騎士の呪文ダメージ倍増',
        defenseEffect: '所持で魔法防御',
        invoke: '助言・神託 (Speaks advice)',
        descJa: '騎士のクエストアーティファクト。所持で魔法防御とテレパシー。騎士の攻撃呪文のダメージを倍増させ、#invokeで知恵やアドバイスを語る。',
        descEn: 'The quest artifact of Knights. Grants ESP and magic resistance while carried, doubles spell damage for Knights, and speaks when invoked.'
    },
    {
        id: 'art_eyes_of_the_overworld',
        name: 'The Eyes of the Overworld',
        nameJa: '界の外の瞳',
        baseName: 'lenses',
        baseOnum: 232,
        category: 'TOOL',
        alignment: 'NEUTRAL',
        role: 'monk',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['xray_vision'],
        attackEffect: null,
        defenseEffect: '装備で魔法防御',
        invoke: '啓蒙 (Enlightenment)',
        descJa: 'モンクのクエストアーティファクト。着用で透視能力（X線視覚：壁の向こうのモンスターを見る）と魔法防御。呼び出しで自身の全ステータス・耐性を開示する啓蒙を発動。',
        descEn: 'The quest artifact of Monks. Grants astral vision (X-ray) and magic resistance while worn. Invoking gives self-enlightenment.'
    },
    {
        id: 'art_mitre_of_holiness',
        name: 'The Mitre of Holiness',
        nameJa: '聖なるミトラ',
        baseName: 'helm of brilliance',
        baseOnum: 96,
        category: 'ARMOR',
        alignment: 'LAWFUL',
        role: 'priest',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['fire_res_carry'],
        attackEffect: null,
        defenseEffect: '所持で火炎耐性、アンデッドからの攻撃半減',
        invoke: 'エネルギー急回復 (Energy Boost)',
        descJa: '僧侶のクエストアーティファクト。所持で火炎耐性、アンデッドからの攻撃半減。呼び出しで魔法エネルギー（MP）を最大値まで一気に充填する。',
        descEn: 'The quest artifact of Priests. Grants fire resistance and halves damage from undead. Invoking boosts magical energy to full.'
    },
    {
        id: 'art_longbow_of_diana',
        name: 'The Longbow of Diana',
        nameJa: 'ディアナの長弓',
        baseName: 'bow',
        baseOnum: 83,
        category: 'WEAPON',
        alignment: 'CHAOTIC',
        role: 'ranger',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['esp', 'reflection'],
        attackEffect: '物理追加ダメージ(+1d5)',
        defenseEffect: '装備で反射 (Reflection)',
        invoke: '矢の自動生成 (Create Ammo)',
        descJa: 'レンジャーのクエストアーティファクト。装備で反射とテレパシー。呼び出し（#invoke）でエルフの矢などの高品質な矢束をその場で生成する。',
        descEn: 'The quest artifact of Rangers. Grants reflection and ESP when wielded. Invoking creates a quiver of arrows.'
    },
    {
        id: 'art_master_key_of_thievery',
        name: 'The Master Key of Thievery',
        nameJa: '盗賊の合鍵',
        baseName: 'skeleton key',
        baseOnum: 221,
        category: 'TOOL',
        alignment: 'CHAOTIC',
        role: 'rogue',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['warning', 'teleport_control'],
        attackEffect: null,
        defenseEffect: '受ける物理ダメージ半減 (Half Physical Damage)',
        invoke: '安全な罠解除 (Untrap)',
        descJa: '盗賊のクエストアーティファクト。所持で警告、テレポート制御、受ける物理ダメージ半減。箱や扉の鍵開け・罠解除が100%安全に成功する。',
        descEn: 'The quest artifact of Rogues. Grants warning, teleport control, and halves physical damage while carried. Guarantees safe untrapping.'
    },
    {
        id: 'art_tsurugi_of_muramasa',
        name: 'The Tsurugi of Muramasa',
        nameJa: '村正のツルギ',
        baseName: 'tsurugi',
        baseOnum: 57,
        category: 'WEAPON',
        alignment: 'LAWFUL',
        role: 'samurai',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['luck'],
        attackEffect: '追加物理ダメージ(+1d8)、首切り即死 (5%の確率で首を切断)',
        defenseEffect: null,
        invoke: null,
        descJa: '侍のクエストアーティファクト。巨大な両手刀。高い基本打撃力に加えて追加ダメージと首切り即死能力を持つ必殺の妖刀。',
        descEn: 'The quest artifact of Samurai. A two-handed tsurugi that deals heavy damage (+1d8) and has a 5% chance to behead opponents.'
    },
    {
        id: 'art_yendorian_express_card',
        name: 'The Platinum Yendorian Express Card',
        nameJa: '白金のエンドール急行カード',
        baseName: 'credit card',
        baseOnum: 223,
        category: 'TOOL',
        alignment: 'NEUTRAL',
        role: 'tourist',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['esp', 'magic_res_carry'],
        attackEffect: null,
        defenseEffect: '所持で魔法防御 (Carry Magic Resistance)',
        invoke: 'アイテム充填 (Charging)',
        descJa: '観光客のクエストアーティファクト。所持で魔法防御とテレパシー。呼び出し（#invoke）で杖や魔法書、魔道具の回数を充填（チャージ）する強力無比なプラチナカード。',
        descEn: 'The quest artifact of Tourists. Grants ESP and magic resistance while carried. Invoking charges wands and magical tools.'
    },
    {
        id: 'art_orb_of_fate',
        name: 'The Orb of Fate',
        nameJa: '運命の宝珠',
        baseName: 'crystal ball',
        baseOnum: 231,
        category: 'TOOL',
        alignment: 'NEUTRAL',
        role: 'valkyrie',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['luck', 'warning'],
        attackEffect: null,
        defenseEffect: '物理・呪文全被ダメージ半減 (Half Physical & Spell Damage)',
        invoke: '浮遊 / レベルテレポート (Levitation / Level Teleport)',
        descJa: 'ワルキューレのクエストアーティファクト。所持しているだけで物理攻撃・魔法攻撃の被ダメージをすべて半分に抑える究極の防御宝珠。呼び出しで浮遊や任意階層移動。',
        descEn: 'The quest artifact of Valkyries. Halves both physical and magical damage while carried. Invokes levitation or level teleportation.'
    },
    {
        id: 'art_eye_of_the_aethiopica',
        name: 'The Eye of the Aethiopica',
        nameJa: 'アエシオーピカの目',
        baseName: 'amulet of esp',
        baseOnum: 201,
        category: 'AMULET',
        alignment: 'NEUTRAL',
        role: 'wizard',
        race: null,
        isQuestArtifact: true,
        intrinsics: ['esp', 'energy_regen'],
        attackEffect: null,
        defenseEffect: '装備で魔法防御',
        invoke: '瞬間移動ポータル (Branch Teleport)',
        descJa: '魔法使いのクエストアーティファクト。着用でテレパシーと超高速の魔法エネルギー自然回復（ターンごとのMP回復量が大幅増）。呼び出しで任意のダンジョン分岐へワープ。',
        descEn: 'The quest artifact of Wizards. Grants ESP, magic resistance, and rapid energy regeneration. Invoking opens portals to dungeon branches.'
    }
];

export const ARTIFACT_KNOWLEDGE_MAP = new Map();
for (const art of ARTIFACT_KNOWLEDGE_BASE) {
    ARTIFACT_KNOWLEDGE_MAP.set(art.id, art);
    ARTIFACT_KNOWLEDGE_MAP.set(art.name.toLowerCase(), art);
}

/**
 * IDまたは名称からアーティファクト定義を取得
 * @param {string} idOrName 
 * @returns {Object|null}
 */
export function getArtifactDefinition(idOrName) {
    if (!idOrName || typeof idOrName !== 'string') return null;
    return ARTIFACT_KNOWLEDGE_MAP.get(idOrName.toLowerCase().trim()) || null;
}

/**
 * 全アーティファクト定義を取得
 * @returns {Array<Object>}
 */
export function getAllArtifactDefinitions() {
    return ARTIFACT_KNOWLEDGE_BASE;
}
