export { GKLPlugin } from './GKLPlugin.js';
export { AreaStateManager } from "./state/AreaStateManager.js";
export { InventoryStateManager } from "./state/InventoryStateManager.js";
export { SpellStateManager } from "./state/SpellStateManager.js";
export { SkillStateManager, SKILL_RANKS } from "./state/SkillStateManager.js";
export { AttributeStateManager, ATTRIBUTE_KEYS, ATTRIBUTE_DEFINITIONS } from "./state/AttributeStateManager.js";
export { SituationCache } from "./state/SituationCache.js";
export { ContextActionEngine } from "./engines/ContextActionEngine.js";
export { TacticalAdvisor } from "./engines/TacticalAdvisor.js";
export { AssistSignalSynthesizer } from "./engines/AssistSignalSynthesizer.js";
export { GlyphClassifier } from "./engines/glyphClassifier.js";
export { StructuredKnowledgeEngine, MONSTER_KNOWLEDGE_BASE, ITEM_KNOWLEDGE_BASE } from "./engines/StructuredKnowledgeEngine.js";
export { OnDemandLookService } from "./services/OnDemandLookService.js";
export { ItemIdentificationResolver, IDENTIFICATION_LEVELS, APPEARANCE_PATTERNS, IDENTIFICATION_TIPS } from "./engines/ItemIdentificationResolver.js";
export { DiscoveryStateManager } from "./state/DiscoveryStateManager.js";
export { getAdaptiveItemSpecs, getSkillProficiencyBadge } from "./presenters/ItemSpecPresenter.js";
export { WishService, WISH_PRESETS, BLESSING_STATES, PROOF_TYPES, FAMOUS_ARTIFACTS, CATEGORY_LABELS, ITEM_JA_MAP } from "./services/WishService.js";
export { GenocideService, MONSTER_CLASS_DEFINITIONS, GENOCIDE_PRESETS } from "./services/GenocideService.js";
export { PolymorphService } from "./services/PolymorphService.js";
export { WriteService } from "./services/WriteService.js";
export { EncumbranceStateManager } from "./state/EncumbranceStateManager.js";
export { MonsterTracker } from "./state/MonsterTracker.js";
export { EquipmentActionPlanner } from "./equipment/EquipmentActionPlanner.js";
export { EquipmentRules, EQUIP_SLOTS } from "./equipment/EquipmentRules.js";
export { EquipmentDependencyAnalyzer } from "./equipment/EquipmentDependencyAnalyzer.js";

