/**
 * MONSTER_JP_MAP.js
 * NetHackJP (mon_jp.c) より抽出した全383モンスターの公式日本語名・別名エイリアス辞書 (SSOT)
 */
export const MONSTER_JP_MAP = {
    "monsters": {
        "giant ant": "巨大蟻",
        "killer bee": "殺人蜂",
        "soldier ant": "兵隊蟻",
        "fire ant": "火蟻",
        "giant beetle": "巨大カブト虫",
        "queen bee": "女王蜂",
        "acid blob": "酸のブロッブ",
        "quivering blob": "震えるブロッブ",
        "gelatinous cube": "ゼラチンキューブ",
        "chickatrice": "チカトリス",
        "cockatrice": "コカトリス",
        "pyrolisk": "ピロリスク",
        "jackal": "ジャッカル",
        "fox": "狐",
        "coyote": "コヨーテ",
        "werejackal": "ジャッカル人間",
        "little dog": "仔犬",
        "dingo": "野犬",
        "dog": "犬",
        "large dog": "大きな犬",
        "wolf": "狼",
        "werewolf": "狼人間",
        "winter wolf cub": "冬狼の子",
        "warg": "ワーグ",
        "winter wolf": "冬狼",
        "hell hound pup": "ヘルハウンドの仔",
        "hell hound": "ヘルハウンド",
        "gas spore": "包子ガス",
        "floating eye": "さまよう目",
        "freezing sphere": "氷の球体",
        "flaming sphere": "炎の球体",
        "shocking sphere": "電撃の球体",
        "kitten": "小猫",
        "housecat": "家猫",
        "jaguar": "ジャガー",
        "lynx": "山猫",
        "panther": "パンサー",
        "large cat": "大きな猫",
        "tiger": "虎",
        "displacer beast": "ディスプレイサービースト",
        "gremlin": "グレムリン",
        "gargoyle": "ガーゴイル",
        "winged gargoyle": "羽のあるガーゴイル",
        "hobbit": "ホビット",
        "dwarf": "ドワーフ",
        "bugbear": "バグベアー",
        "dwarf leader {dwarf lord}": "ドワーフの首領",
        "dwarf leader": "ドワーフの首領",
        "dwarf ruler {dwarf king}": "ドワーフの支配者",
        "dwarf ruler": "ドワーフの支配者",
        "mind flayer": "マインドフレア",
        "master mind flayer": "マスターマインドフレア",
        "manes": "亡霊",
        "homunculus": "ホムンクルス",
        "imp": "インプ",
        "lemure": "レムレース",
        "quasit": "クアシト",
        "tengu": "天狗",
        "blue jelly": "青色ゼリー",
        "spotted jelly": "まだらゼリー",
        "ochre jelly": "黄土色ゼリー",
        "kobold": "コボルド",
        "large kobold": "大きなコボルド",
        "kobold leader {kobold lord}": "コボルドの首領",
        "kobold leader": "コボルドの首領",
        "kobold shaman": "コボルドの呪術師",
        "leprechaun": "レプラコーン",
        "small mimic": "小さなミミック",
        "large mimic": "大きなミミック",
        "giant mimic": "巨大なミミック",
        "wood nymph": "木のニンフ",
        "water nymph": "水のニンフ",
        "mountain nymph": "山のニンフ",
        "goblin": "ゴブリン",
        "hobgoblin": "ホブゴブリン",
        "orc": "オーク",
        "hill orc": "丘のオーク",
        "Mordor orc": "モルドールのオーク",
        "Uruk-hai": "ウルク・ハイ",
        "orc shaman": "オークの呪術師",
        "orc-captain": "オークの隊長",
        "rock piercer": "岩喰い",
        "iron piercer": "鉄喰い",
        "glass piercer": "ガラス喰い",
        "rothe": "ロゼ",
        "mumak": "ムーマク",
        "leocrotta": "レオクロッタ",
        "wumpus": "ワンパス",
        "titanothere": "チタノゼア",
        "baluchitherium": "バルキテリウム",
        "mastodon": "マストドン",
        "sewer rat": "ドブネズミ",
        "giant rat": "巨大ネズミ",
        "rabid rat": "兇暴ネズミ",
        "wererat": "ねずみ人間",
        "rock mole": "岩もぐら",
        "woodchuck": "リス",
        "cave spider": "洞窟グモ",
        "centipede": "ムカデ",
        "giant spider": "巨大グモ",
        "scorpion": "サソリ",
        "lurker above": "ラーカー",
        "trapper": "トラッパー",
        "pony": "仔馬",
        "white unicorn": "白ユニコーン",
        "gray unicorn": "灰色ユニコーン",
        "black unicorn": "黒ユニコーン",
        "horse": "馬",
        "warhorse": "戦闘用の馬",
        "fog cloud": "霧の雲",
        "dust vortex": "ほこりの渦",
        "ice vortex": "氷の渦",
        "energy vortex": "エネルギーの渦",
        "steam vortex": "蒸気の渦",
        "fire vortex": "炎の渦",
        "baby long worm": "ロングワームの子供",
        "baby purple worm": "紫ワームの子供",
        "long worm": "ロングワーム",
        "purple worm": "紫ワーム",
        "grid bug": "グリッドバグ",
        "xan": "ザン",
        "yellow light": "黄色い光",
        "black light": "黒い光",
        "zruty": "ズルティ",
        "couatl": "コウアトル",
        "Aleax": "アレアックス",
        "Angel": "天使",
        "ki-rin": "麒麟",
        "Archon": "アルコン",
        "bat": "こうもり",
        "giant bat": "巨大こうもり",
        "raven": "オオガラス",
        "vampire bat": "吸血こうもり",
        "plains centaur": "草原のケンタウロス",
        "forest centaur": "森のケンタウロス",
        "mountain centaur": "山のケンタウロス",
        "baby gray dragon": "灰色ドラゴンの子供",
        "baby gold dragon": "金色ドラゴンの子供",
        "baby silver dragon": "銀色ドラゴンの幼体",
        "baby red dragon": "赤色ドラゴンの子供",
        "baby white dragon": "白ドラゴンの子供",
        "baby orange dragon": "オレンジドラゴンの子供",
        "baby black dragon": "黒ドラゴンの子供",
        "baby blue dragon": "青ドラゴンの子供",
        "baby green dragon": "緑ドラゴンの子供",
        "baby yellow dragon": "黄色ドラゴンの子供",
        "gray dragon": "灰色ドラゴン",
        "gold dragon": "金色ドラゴン",
        "silver dragon": "銀色ドラゴン",
        "red dragon": "赤色ドラゴン",
        "white dragon": "白ドラゴン",
        "orange dragon": "オレンジドラゴン",
        "black dragon": "黒ドラゴン",
        "blue dragon": "青ドラゴン",
        "green dragon": "緑ドラゴン",
        "yellow dragon": "黄色ドラゴン",
        "stalker": "ストーカー",
        "air elemental": "風の精",
        "fire elemental": "火の精",
        "earth elemental": "土の精",
        "water elemental": "水の精",
        "lichen": "苔の怪物",
        "brown mold": "茶色モールド",
        "yellow mold": "黄色モールド",
        "green mold": "緑モールド",
        "red mold": "赤色モールド",
        "shrieker": "シュリーカー",
        "violet fungus": "紫キノコ",
        "gnome": "ノーム",
        "gnome leader {gnome lord}": "ノームの首領",
        "gnome leader": "ノームの首領",
        "gnomish wizard": "ノームの魔法使い",
        "gnome ruler {gnome king}": "ノームの支配者",
        "gnome ruler": "ノームの支配者",
        "giant": "巨人",
        "stone giant": "岩石巨人",
        "hill giant": "丘の巨人",
        "fire giant": "炎の巨人",
        "frost giant": "吹雪の巨人",
        "ettin": "エティン",
        "storm giant": "雷の巨人",
        "titan": "タイタン",
        "minotaur": "ミノタウロス",
        "jabberwock": "ジャバウォック",
        "Keystone Kop": "警備員",
        "Kop Sergeant": "巡査",
        "Kop Lieutenant": "巡査部長",
        "Kop Kaptain": "警部補",
        "lich": "リッチ",
        "demilich": "デミリッチ",
        "master lich": "マスターリッチ",
        "arch-lich": "アーチリッチ",
        "kobold mummy": "コボルドのミイラ",
        "gnome mummy": "ノームのミイラ",
        "orc mummy": "オークのミイラ",
        "dwarf mummy": "ドワーフのミイラ",
        "elf mummy": "エルフのミイラ",
        "human mummy": "人間のミイラ",
        "ettin mummy": "エティンのミイラ",
        "giant mummy": "巨人のミイラ",
        "red naga hatchling": "赤色ナーガの雛",
        "black naga hatchling": "黒ナーガの雛",
        "golden naga hatchling": "金色ナーガの雛",
        "guardian naga hatchling": "番兵ナーガの雛",
        "red naga": "赤色ナーガ",
        "black naga": "黒ナーガ",
        "golden naga": "金色ナーガ",
        "guardian naga": "番兵ナーガ",
        "ogre": "オーガ",
        "ogre leader {ogre lord}": "オーガの首領",
        "ogre leader": "オーガの首領",
        "ogre tyrant {ogre king}": "オーガの暴君",
        "ogre tyrant": "オーガの暴君",
        "gray ooze": "灰色ウーズ",
        "brown pudding": "茶色プリン",
        "green slime": "緑スライム",
        "black pudding": "黒プリン",
        "quantum mechanic": "量子物理学者",
        "genetic engineer": "遺伝子工学者",
        "rust monster": "錆の怪物",
        "disenchanter": "吸魔の怪物",
        "garter snake": "小さなヘビ",
        "snake": "ヘビ",
        "water moccasin": "水ヘビ",
        "python": "ニシキヘビ",
        "pit viper": "ハブ",
        "cobra": "コブラ",
        "troll": "トロル",
        "ice troll": "氷のトロル",
        "rock troll": "岩のトロル",
        "water troll": "水のトロル",
        "Olog-hai": "オログハイ",
        "umber hulk": "アンバーハルク",
        "vampire": "吸血鬼",
        "vampire leader {vampire lord}": "ヴァンパイアの長",
        "vampire leader": "ヴァンパイアの長",
        "Vlad the Impaler": "吸血鬼ヴラド",
        "barrow wight": "バロウ・ワイト",
        "wraith": "レイス",
        "Nazgul": "ナズグル",
        "xorn": "ゾーン",
        "monkey": "猿",
        "ape": "類人猿",
        "owlbear": "アウルベア",
        "yeti": "イエティ",
        "carnivorous ape": "人喰い猿",
        "sasquatch": "サスカッチ",
        "kobold zombie": "コボルドのゾンビ",
        "gnome zombie": "ノームのゾンビ",
        "orc zombie": "オークのゾンビ",
        "dwarf zombie": "ドワーフのゾンビ",
        "elf zombie": "エルフのゾンビ",
        "human zombie": "人間のゾンビ",
        "ettin zombie": "エティンのゾンビ",
        "ghoul": "グール",
        "giant zombie": "巨人のゾンビ",
        "skeleton": "骸骨",
        "straw golem": "藁のゴーレム",
        "paper golem": "紙のゴーレム",
        "rope golem": "紐のゴーレム",
        "gold golem": "金のゴーレム",
        "leather golem": "皮のゴーレム",
        "wood golem": "木のゴーレム",
        "flesh golem": "肉のゴーレム",
        "clay golem": "土のゴーレム",
        "stone golem": "岩のゴーレム",
        "glass golem": "ガラスのゴーレム",
        "iron golem": "鉄のゴーレム",
        "human": "人間",
        "elf": "エルフ",
        "Woodland-elf": "森のエルフ",
        "Green-elf": "緑エルフ",
        "Grey-elf": "灰色エルフ",
        "elf-noble {elf-lord}": "エルフの貴族",
        "elf-noble": "エルフの貴族",
        "elven monarch {Elvenking}": "エルフの君主",
        "elven monarch": "エルフの君主",
        "doppelganger": "ドッペルゲンガー",
        "shopkeeper": "店主",
        "guard": "番兵",
        "prisoner": "囚人",
        "Oracle": "賢者",
        "aligned cleric {priest}": "神官",
        "aligned cleric": "神官",
        "high cleric {high priest}": "高位神官",
        "high cleric": "高位神官",
        "soldier": "兵士",
        "sergeant": "下士官",
        "nurse": "看護婦",
        "lieutenant": "副官",
        "captain": "指揮官",
        "watchman": "見張り",
        "watch captain": "見張りの隊長",
        "Medusa": "メデューサ",
        "Wizard of Yendor": "イェンダーの魔法使い",
        "Croesus": "クロイソス",
        "ghost": "幽霊",
        "shade": "影",
        "water demon": "水の魔神",
        "amorous demon {incubus}": "愛の悪魔",
        "amorous demon": "愛の悪魔",
        "horned devil": "角のある悪魔",
        "erinys": "イリニス",
        "barbed devil": "棘の悪魔",
        "marilith": "マリリス",
        "vrock": "ヴァロック",
        "hezrou": "ヘズロウ",
        "bone devil": "骨の悪魔",
        "ice devil": "氷の悪魔",
        "nalfeshnee": "ナルフェシニ",
        "pit fiend": "穴の悪霊",
        "sandestin": "サンデスティン",
        "balrog": "バルログ",
        "Juiblex": "ジョウビレックス",
        "Yeenoghu": "イーノグ",
        "Orcus": "オーケス",
        "Geryon": "ゲーリュオーン",
        "Dispater": "ディスペータ",
        "Baalzebub": "ベルゼブブ",
        "Asmodeus": "アスモデウス",
        "Demogorgon": "デモゴルゴン",
        "Death": "デス",
        "Pestilence": "ペスティレンス",
        "Famine": "フェミン",
        "mail daemon": "メイルデーモン",
        "djinni": "風のジン",
        "jellyfish": "クラゲ",
        "piranha": "ピラニア",
        "shark": "サメ",
        "giant eel": "巨大ウナギ",
        "electric eel": "電気ウナギ",
        "kraken": "クラーケン",
        "newt": "イモリ",
        "gecko": "ヤモリ",
        "iguana": "イグアナ",
        "baby crocodile": "ワニの子供",
        "lizard": "トカゲ",
        "chameleon": "カメレオン",
        "crocodile": "ワニ",
        "salamander": "サラマンダー",
        "long worm tail": "ロングワームの尻尾",
        "archeologist": "考古学者",
        "barbarian": "野蛮人",
        "cave dweller {caveman}": "洞窟人",
        "cave dweller": "洞窟人",
        "healer": "治療師",
        "knight": "騎士",
        "monk": "武闘家",
        "cleric {priest}": "司祭",
        "cleric": "司祭",
        "ranger": "レンジャー",
        "rogue": "盗賊",
        "samurai": "侍",
        "tourist": "観光客",
        "valkyrie": "ワルキューレ",
        "wizard": "魔法使い",
        "Lord Carnarvon": "カーナボン卿",
        "Pelias": "ペリアス",
        "Shaman Karnov": "呪術師カルノフ",
        "Hippocrates": "ヒポクラテス",
        "King Arthur": "アーサー王",
        "Grand Master": "総師範",
        "Arch Priest": "主席司祭",
        "Orion": "勇者オリオン",
        "Master of Thieves": "盗賊の頭領",
        "Lord Sato": "大名佐藤",
        "Twoflower": "ツーフラワー",
        "Norn": "ノルン",
        "Neferet the Green": "緑のネフェレト",
        "Minion of Huhetotl": "フヘトトルの使い",
        "Thoth Amon": "トート・アモン",
        "Chromatic Dragon": "クロマティック・ドラゴン",
        "Cyclops": "サイクロプス",
        "Ixoth": "イクソス",
        "Master Kaen": "カエン",
        "Nalzok": "ナルゾク",
        "Scorpius": "大蠍",
        "Master Assassin": "暗殺者の頭領",
        "Ashikaga Takauji": "足利尊氏",
        "Lord Surtur": "支配者スルト",
        "Dark One": "暗きもの",
        "student": "学生",
        "chieftain": "首領",
        "neanderthal": "ネアンデルタール人",
        "attendant": "随行員",
        "page": "小姓",
        "abbot": "師範",
        "acolyte": "侍者",
        "hunter": "ハンター",
        "thug": "ちんぴら",
        "ninja": "忍者",
        "roshi": "浪士",
        "guide": "ガイド",
        "warrior": "戦士",
        "apprentice": "実習生"
    },
    "aliases": {
        "mind flayer": [
            "マインドフレイヤ",
            "マインドフレア"
        ],
        "master mind flayer": [
            "マスターマインドフレイヤ",
            "マスターマインドフレア",
            "マスター・マインド・フレイヤ"
        ],
        "master lich": [
            "マスター・リッチ",
            "マスターリッチ"
        ],
        "arch-lich": [
            "アーチ・リッチ",
            "アーチリッチ"
        ],
        "demilich": [
            "デミ・リッチ",
            "デミリッチ"
        ],
        "lich": [
            "リッチ"
        ],
        "disenchanter": [
            "ディスエンチャンター",
            "分解獣"
        ],
        "cockatrice": [
            "コカトリス"
        ],
        "chickatrice": [
            "チカトリス"
        ],
        "silver dragon": [
            "銀のドラゴン",
            "シルバー・ドラゴン",
            "シルバードラゴン",
            "銀ドラゴン"
        ],
        "gray dragon": [
            "灰色のドラゴン",
            "グレー・ドラゴン",
            "グレードラゴン",
            "灰ドラゴン"
        ],
        "black dragon": [
            "黒のドラゴン",
            "ブラック・ドラゴン",
            "黒ドラゴン"
        ],
        "red dragon": [
            "赤のドラゴン",
            "レッド・ドラゴン",
            "赤ドラゴン"
        ]
    }
};
