/**
 * OBJECT_JP_MAP.js
 * NetHack 5.0 (3.7) 全 481 アイテム公式確定和名・エイリアス辞書 (SSOT)
 */

export const OBJECT_JP_MAP = {
    "objects": {
        "strange object": "奇妙な物体",
        "generic strange": "奇妙な物",
        "generic weapon": "武器",
        "generic armor": "防具",
        "generic ring": "指輪",
        "generic amulet": "魔よけ",
        "generic tool": "道具",
        "generic food": "食料",
        "generic potion": "ポーション",
        "generic scroll": "巻物",
        "generic spellbook": "魔法書",
        "generic wand": "杖",
        "generic coin": "金貨",
        "generic gem": "宝石",
        "generic large rock": "巨岩",
        "generic iron ball": "鉄球",
        "generic iron chain": "鉄の鎖",
        "generic venom": "毒",
        "arrow": "矢",
        "elven arrow": "エルフの矢",
        "orcish arrow": "オークの矢",
        "silver arrow": "銀の矢",
        "ya": "竹の矢",
        "crossbow bolt": "クロスボウのボルト",
        "dart": "ダーツ",
        "shuriken": "投石器",
        "boomerang": "ブーメラン",
        "spear": "槍",
        "elven spear": "エルフの槍",
        "orcish spear": "オークの槍",
        "dwarvish spear": "ドワーフの槍",
        "silver spear": "銀の槍",
        "javelin": "ジャベリン",
        "trident": "三叉矛",
        "dagger": "短剣",
        "elven dagger": "エルフの短剣",
        "orcish dagger": "オークの短剣",
        "silver dagger": "銀の短剣",
        "athame": "アサメ",
        "scalpel": "手術用メス",
        "knife": "ナイフ",
        "stiletto": "スティレット",
        "worm tooth": "芋虫の歯",
        "crysknife": "クリスカナイフ",
        "axe": "斧",
        "battle-axe": "戦斧",
        "short sword": "ショートソード",
        "elven short sword": "エルフのショートソード",
        "orcish short sword": "オークのショートソード",
        "dwarvish short sword": "ドワーフのショートソード",
        "scimitar": "シミター",
        "silver saber": "銀のサーベル",
        "broadsword": "ブロードソード",
        "elven broadsword": "エルフのブロードソード",
        "long sword": "ロングソード",
        "two-handed sword": "両手剣",
        "katana": "カタナ",
        "tsurugi": "ツルギ",
        "runesword": "ルーンソード",
        "partisan": "パルチザン",
        "ranseur": "ランセーア",
        "spetum": "スペタム",
        "glaive": "グレイブ",
        "halberd": "ハルバード",
        "bardiche": "バルディッシュ",
        "voulge": "ヴルジュ",
        "fauchard": "フォシャール",
        "guisarme": "ギザーム",
        "bill-guisarme": "ビルギザーム",
        "lucern hammer": "ルツェルン・ハンマー",
        "bec de corbin": "ベド・コルバン",
        "dwarvish mattock": "ドワーフのマトック",
        "lance": "ランス",
        "mace": "メイス",
        "silver mace": "銀のメイス",
        "morning star": "モーニングスター",
        "war hammer": "ウォーハンマー",
        "club": "棍棒",
        "rubber hose": "ゴムのホース",
        "quarterstaff": "杖",
        "aklys": "アクリス",
        "flail": "フレイル",
        "bullwhip": "鞭",
        "bow": "弓",
        "elven bow": "エルフの弓",
        "orcish bow": "オークの弓",
        "yumi": "和弓",
        "sling": "投石紐",
        "crossbow": "クロスボウ",
        "elven leather helm": "エルフの革の兜",
        "orcish helm": "オークの兜",
        "dwarvish iron helm": "ドワーフの鉄の兜",
        "fedora": "中折れ帽",
        "cornuthaum": "コーニュソーム",
        "dunce cap": "とんがり帽子",
        "dented pot": "へこんだ鍋",
        "helm of brilliance": "輝きの兜",
        "helmet": "兜",
        "helm of caution": "警戒の兜",
        "helm of opposite alignment": "逆配列の兜",
        "helm of telepathy": "テレパシーの兜",
        "gray dragon scale mail": "灰色ドラゴンの鱗鎧",
        "gold dragon scale mail": "金色ドラゴンの鱗鎧",
        "silver dragon scale mail": "銀色ドラゴンの鱗鎧",
        "red dragon scale mail": "赤色ドラゴンの鱗鎧",
        "white dragon scale mail": "白色ドラゴンの鱗鎧",
        "orange dragon scale mail": "橙色ドラゴンの鱗鎧",
        "black dragon scale mail": "黒色ドラゴンの鱗鎧",
        "blue dragon scale mail": "青色ドラゴンの鱗鎧",
        "green dragon scale mail": "緑色ドラゴンの鱗鎧",
        "yellow dragon scale mail": "黄色ドラゴンの鱗鎧",
        "gray dragon scales": "灰色ドラゴンの鱗",
        "gold dragon scales": "金色ドラゴンの鱗",
        "silver dragon scales": "銀色ドラゴンの鱗",
        "red dragon scales": "赤色ドラゴンの鱗",
        "white dragon scales": "白色ドラゴンの鱗",
        "orange dragon scales": "橙色ドラゴンの鱗",
        "black dragon scales": "黒色ドラゴンの鱗",
        "blue dragon scales": "青色ドラゴンの鱗",
        "green dragon scales": "緑色ドラゴンの鱗",
        "yellow dragon scales": "黄色ドラゴンの鱗",
        "plate mail": "プレートメイル",
        "crystal plate mail": "クリスタルプレートメイル",
        "bronze plate mail": "ブロンズプレートメイル",
        "splint mail": "スプリントメイル",
        "banded mail": "バンデッドメイル",
        "dwarvish mithril-coat": "ドワーフのミスリルコート",
        "elven mithril-coat": "エルフのミスリルコート",
        "chain mail": "チェインメイル",
        "orcish chain mail": "オークのチェインメイル",
        "scale mail": "スケイルメイル",
        "studded leather armor": "スタッドレザーアーマー",
        "ring mail": "リングメイル",
        "orcish ring mail": "オークのリングメイル",
        "leather armor": "レザーアーマー",
        "leather jacket": "レザージャケット",
        "Hawaiian shirt": "アロハシャツ",
        "T-shirt": "Tシャツ",
        "mummy wrapping": "ミイラの包帯",
        "elven cloak": "エルフのクローク",
        "orcish cloak": "オークのクローク",
        "dwarvish cloak": "ドワーフのクローク",
        "oilskin cloak": "オイルスキンクローク",
        "robe": "ローブ",
        "alchemy smock": "錬金術師の作業着",
        "leather cloak": "革のクローク",
        "cloak of protection": "保護のクローク",
        "cloak of invisibility": "透明のクローク",
        "cloak of magic resistance": "魔法防御のマント",
        "cloak of displacement": "分身のクローク",
        "small shield": "小さな盾",
        "shield of drain resistance": "ドレイン耐性の盾",
        "shield of shock resistance": "衝撃耐性の盾",
        "elven shield": "エルフの盾",
        "Uruk-hai shield": "ウルク＝ハイの盾",
        "orcish shield": "オークの盾",
        "large shield": "大きな盾",
        "dwarvish roundshield": "ドワーフの円盾",
        "shield of reflection": "反射の盾",
        "leather gloves": "革の手袋",
        "gauntlets of fumbling": "下手な小手",
        "gauntlets of power": "力の小手",
        "gauntlets of dexterity": "器用さの小手",
        "low boots": "短靴",
        "iron shoes": "鉄の靴",
        "high boots": "長靴",
        "speed boots": "韋駄天の靴",
        "water walking boots": "水上歩行の靴",
        "jumping boots": "跳躍の靴",
        "elven boots": "エルフの靴",
        "kicking boots": "蹴りの靴",
        "fumble boots": "つまずきの靴",
        "levitation boots": "浮遊の靴",
        "ring of adornment": "飾りの指輪",
        "ring of gain strength": "腕力増大の指輪",
        "ring of gain constitution": "体力増大の指輪",
        "ring of increase accuracy": "命中率向上の指輪",
        "ring of increase damage": "ダメージ向上の指輪",
        "ring of protection": "保護の魔法書",
        "ring of regeneration": "再生の指輪",
        "ring of searching": "探索の指輪",
        "ring of stealth": "忍びの指輪",
        "ring of sustain ability": "能力保持の指輪",
        "ring of levitation": "浮遊の魔法書",
        "ring of hunger": "飢えの指輪",
        "ring of aggravate monster": "モンスターを怒らせる指輪",
        "ring of conflict": "争いの指輪",
        "ring of warning": "警告の指輪",
        "ring of poison resistance": "毒耐性の指輪",
        "ring of fire resistance": "火耐性の指輪",
        "ring of cold resistance": "冷気耐性の指輪",
        "ring of shock resistance": "電撃耐性の指輪",
        "ring of free action": "自由行動の指輪",
        "ring of slow digestion": "消化鈍化の指輪",
        "ring of teleportation": "テレポートの杖",
        "ring of teleport control": "テレポート制御の指輪",
        "ring of polymorph": "変身の杖",
        "ring of polymorph control": "変身制御",
        "ring of invisibility": "透明の魔法書",
        "ring of see invisible": "可視のポーション",
        "ring of protection from shape changers": "変身能力者からの保護",
        "amulet of ESP": "ESPのアミュレット",
        "amulet of life saving": "生命維持のアミュレット",
        "amulet of strangulation": "絞殺のアミュレット",
        "amulet of restful sleep": "安眠のアミュレット",
        "amulet versus poison": "毒守りのアミュレット",
        "amulet of change": "性転換の魔よけ",
        "amulet of unchanging": "不変のアミュレット",
        "amulet of reflection": "反射のアミュレット",
        "amulet of magical breathing": "魔法の呼吸のアミュレット",
        "amulet of guarding": "守護の魔よけ",
        "amulet of flying": "飛行の魔よけ",
        "cheap plastic imitation of the Amulet of Yendor": "イェンドールの護符の安物プラスチックの偽物",
        "Amulet of Yendor": "イェンドールの護符",
        "large box": "大きな箱",
        "chest": "宝箱",
        "ice box": "氷箱",
        "sack": "袋",
        "oilskin sack": "オイルスキンの袋",
        "bag of holding": "軽量化の袋",
        "bag of tricks": "手品の袋",
        "skeleton key": "合鍵",
        "lock pick": "ロックピック",
        "credit card": "クレジットカード",
        "tallow candle": "獣脂の蝋燭",
        "wax candle": "蜜蝋の蝋燭",
        "brass lantern": "真鍮のランタン",
        "oil lamp": "油灯",
        "magic lamp": "魔法のランプ",
        "expensive camera": "高級カメラ",
        "mirror": "鏡",
        "crystal ball": "水晶玉",
        "lenses": "レンズ",
        "blindfold": "目隠し",
        "towel": "タオル",
        "saddle": "鞍",
        "leash": "紐",
        "stethoscope": "聴診器",
        "tinning kit": "缶詰作成キット",
        "tin opener": "缶切り",
        "can of grease": "グリース缶",
        "figurine": "小像",
        "magic marker": "魔法のマーカー",
        "land mine": "地雷",
        "beartrap": "虎ばさみ",
        "tin whistle": "ティン・ホイッスル",
        "magic whistle": "魔法の笛",
        "wooden flute": "木製のフルート",
        "magic flute": "魔法のフルート",
        "tooled horn": "加工された角",
        "frost horn": "氷の角笛",
        "fire horn": "炎の角笛",
        "horn of plenty": "豊穣の角笛",
        "wooden harp": "木製のハープ",
        "magic harp": "魔法のハープ",
        "bell": "ベル",
        "bugle": "ビューグル(角笛)",
        "leather drum": "革の太鼓",
        "drum of earthquake": "地震の太鼓",
        "pick-axe": "つるはし",
        "grappling hook": "鉤縄",
        "unicorn horn": "ユニコーンの角",
        "Candelabrum of Invocation": "祈りの燭台",
        "Bell of Opening": "開錠の鈴",
        "tripe ration": "干しホルモン",
        "corpse": "死体",
        "egg": "卵",
        "meatball": "肉団子",
        "meat stick": "肉の棒",
        "enormous meatball": "巨大な肉団子",
        "meat ring": "肉の輪",
        "glob of gray ooze": "グレー・ウーズの塊",
        "glob of brown pudding": "ブラウン・プリンの塊",
        "glob of green slime": "グリーン・スライムの塊",
        "glob of black pudding": "ブラック・プリンの塊",
        "kelp frond": "昆布の葉",
        "eucalyptus leaf": "ユーカリの葉",
        "apple": "リンゴ",
        "orange": "オレンジ",
        "pear": "ナシ",
        "melon": "メロン",
        "banana": "バナナ",
        "carrot": "人参",
        "sprig of wolfsbane": "トリカブトの小枝",
        "clove of garlic": "ニンニクの球根",
        "slime mold": "スライム・モールド",
        "lump of royal jelly": "ローヤルゼリーの塊",
        "cream pie": "クリームパイ",
        "candy bar": "キャンディバー",
        "fortune cookie": "占いクッキー",
        "pancake": "パンケーキ",
        "lembas wafer": "レンバス",
        "cram ration": "携帯食糧",
        "food ration": "食料",
        "K-ration": "Kレーション",
        "C-ration": "Cレーション",
        "tin": "缶詰",
        "potion of gain ability": "能力上昇のポーション",
        "potion of restore ability": "能力回復の魔法書",
        "potion of confusion": "混乱のポーション",
        "potion of blindness": "盲目のポーション",
        "potion of paralysis": "麻痺のポーション",
        "potion of speed": "スピードのポーション",
        "potion of levitation": "浮遊の魔法書",
        "potion of hallucination": "幻覚",
        "potion of invisibility": "透明の魔法書",
        "potion of see invisible": "可視のポーション",
        "potion of healing": "回復の魔法書",
        "potion of extra healing": "強力回復の魔法書",
        "potion of gain level": "レベル上昇",
        "potion of enlightenment": "啓蒙のポーション",
        "potion of monster detection": "モンスター探索のポーション",
        "potion of object detection": "アイテム探索のポーション",
        "potion of gain energy": "エネルギー獲得のポーション",
        "potion of sleeping": "睡眠の薬",
        "potion of full healing": "完全回復のポーション",
        "potion of polymorph": "変身の杖",
        "booze": "お酒",
        "potion of sickness": "病気",
        "fruit juice": "フルーツジュース",
        "acid": "酸のポーション",
        "oil": "油",
        "water": "水",
        "scroll of enchant armor": "防具強化の巻物",
        "scroll of destroy armor": "壊れている防具",
        "scroll of confuse monster": "モンスター混乱",
        "scroll of scare monster": "モンスターを怖がらせる巻物",
        "scroll of remove curse": "呪い解除の巻物",
        "scroll of enchant weapon": "武器強化の巻物",
        "scroll of create monster": "モンスター作成の魔法書",
        "scroll of taming": "モンスターを飼いならす巻物",
        "scroll of genocide": "虐殺の巻物",
        "scroll of light": "明かりの杖",
        "scroll of teleportation": "テレポートの杖",
        "scroll of gold detection": "金貨探索の巻物",
        "scroll of food detection": "食料探索の巻物",
        "scroll of identify": "鑑定の魔法書",
        "scroll of magic mapping": "魔法の地図の魔法書",
        "scroll of amnesia": "忘却の巻物",
        "scroll of fire": "火の巻物",
        "scroll of earth": "土の巻物",
        "scroll of punishment": "処罰の巻物",
        "scroll of charging": "充填の巻物",
        "scroll of stinking cloud": "悪臭の雲の巻物",
        "scroll of FOOBIE BLETCH": "「FOOBIE BLETCH」と書かれた巻物",
        "scroll of TEMOV": "「TEMOV」と書かれた巻物",
        "scroll of GARVEN DEH": "「GARVEN DEH」と書かれた巻物",
        "scroll of READ ME": "「READ ME」と書かれた巻物",
        "scroll of ETAOIN SHRDLU": "「ETAOIN SHRDLU」と書かれた巻物",
        "scroll of LOREM IPSUM": "「LOREM IPSUM」と書かれた巻物",
        "scroll of FNORD": "「FNORD」と書かれた巻物",
        "scroll of KO BATE": "「KO BATE」と書かれた巻物",
        "scroll of ABRA KA DABRA": "「ABRA KA DABRA」と書かれた巻物",
        "scroll of ASHPD SODALG": "「ASHPD SODALG」と書かれた巻物",
        "scroll of ZLORFIK": "「ZLORFIK」と書かれた巻物",
        "scroll of GNIK SISI VLE": "「GNIK SISI VLE」と書かれた巻物",
        "scroll of HAPAX LEGOMENON": "「HAPAX LEGOMENON」と書かれた巻物",
        "scroll of EIRIS SAZUN IDISI": "「EIRIS SAZUN IDISI」と書かれた巻物",
        "scroll of PHOL ENDE WODAN": "「PHOL ENDE WODAN」と書かれた巻物",
        "scroll of GHOTI": "「GHOTI」と書かれた巻物",
        "scroll of MAPIRO MAHAMA DIROMAT": "「MAPIRO MAHAMA DIROMAT」と書かれた巻物",
        "scroll of VAS CORP BET MANI": "「VAS CORP BET MANI」と書かれた巻物",
        "scroll of XOR OTA": "「XOR OTA」と書かれた巻物",
        "scroll of STRC PRST SKRZ KRK": "「STRC PRST SKRZ KRK」と書かれた巻物",
        "mail": "鎧",
        "scroll of blank paper": "白紙の魔法書",
        "spellbook of dig": "掘削の魔法書",
        "spellbook of magic missile": "マジックミサイルの杖",
        "spellbook of fireball": "ファイアボールの魔法書",
        "spellbook of cone of cold": "氷の円錐の魔法書",
        "spellbook of sleep": "睡眠の杖",
        "spellbook of finger of death": "死の指線の魔法書",
        "spellbook of light": "明かりの杖",
        "spellbook of detect monsters": "モンスター探索の魔法書",
        "spellbook of healing": "回復の魔法書",
        "spellbook of knock": "開扉の魔法書",
        "spellbook of force bolt": "フォースボルトの魔法書",
        "spellbook of confuse monster": "モンスター混乱",
        "spellbook of cure blindness": "失明治療の魔法書",
        "spellbook of drain life": "生命吸収の魔法書",
        "spellbook of slow monster": "モンスター鈍化の杖",
        "spellbook of wizard lock": "施錠の魔法書",
        "spellbook of create monster": "モンスター作成の魔法書",
        "spellbook of detect food": "食料探索の魔法書",
        "spellbook of cause fear": "恐怖を引き起こす",
        "spellbook of clairvoyance": "透視の魔法書",
        "spellbook of cure sickness": "病気治療の魔法書",
        "spellbook of charm monster": "モンスター魅了の魔法書",
        "spellbook of haste self": "加速の魔法書",
        "spellbook of detect unseen": "見えないものを検知",
        "spellbook of levitation": "浮遊の魔法書",
        "spellbook of extra healing": "強力回復の魔法書",
        "spellbook of restore ability": "能力回復の魔法書",
        "spellbook of invisibility": "透明の魔法書",
        "spellbook of detect treasure": "宝探索の魔法書",
        "spellbook of remove curse": "呪い解除の巻物",
        "spellbook of magic mapping": "魔法の地図の魔法書",
        "spellbook of identify": "鑑定の魔法書",
        "spellbook of turn undead": "アンデッド退散",
        "spellbook of polymorph": "変身の杖",
        "spellbook of teleport away": "テレポートの魔法書",
        "spellbook of create familiar": "使い魔の創造",
        "spellbook of cancellation": "無力化の杖",
        "spellbook of protection": "保護の魔法書",
        "spellbook of jumping": "跳躍の魔法書",
        "spellbook of stone to flesh": "石を肉にする魔法書",
        "spellbook of chain lightning": "連鎖雷",
        "spellbook of blank paper": "白紙の魔法書",
        "novel": "小説",
        "Book of the Dead": "死者の書",
        "wand of light": "明かりの杖",
        "wand of secret door detection": "隠しドア探索の杖",
        "wand of enlightenment": "啓蒙のポーション",
        "wand of create monster": "モンスター作成の魔法書",
        "wand of wishing": "願いの杖",
        "wand of stasis": "静止",
        "wand of nothing": "何も起きない杖",
        "wand of striking": "打撃の杖",
        "wand of make invisible": "透明化の杖",
        "wand of slow monster": "モンスター鈍化の杖",
        "wand of speed monster": "モンスター加速の杖",
        "wand of undead turning": "アンデッドを追い払う杖",
        "wand of polymorph": "変身の杖",
        "wand of cancellation": "無力化の杖",
        "wand of teleportation": "テレポートの杖",
        "wand of opening": "開扉の杖",
        "wand of locking": "施錠の杖",
        "wand of probing": "調査の杖",
        "wand of digging": "掘削の杖",
        "wand of magic missile": "マジックミサイルの杖",
        "wand of fire": "火の杖",
        "wand of cold": "冷気の杖",
        "wand of sleep": "睡眠の杖",
        "wand of death": "死の杖",
        "wand of lightning": "稲妻の杖",
        "wand of forked": "二股の",
        "wand of spiked": "スパイク付き",
        "wand of jeweled": "宝石を散りばめた",
        "gold piece": "金貨",
        "dilithium crystal": "ディリチウムの結晶",
        "diamond": "ダイヤモンド",
        "ruby": "ルビー",
        "jacinth": "ジルコン",
        "sapphire": "サファイア",
        "black opal": "ブラックオパール",
        "emerald": "エメラルド",
        "turquoise": "トルコ石",
        "citrine": "シトリン",
        "aquamarine": "アクアマリン",
        "amber": "琥珀",
        "topaz": "トパーズ",
        "jet": "黒玉",
        "opal": "オパール",
        "chrysoberyl": "金緑石",
        "garnet": "ガーネット",
        "amethyst": "アメジスト",
        "jasper": "碧玉",
        "fluorite": "蛍石",
        "obsidian": "黒曜石",
        "agate": "メノウ",
        "jade": "ヒスイ",
        "worthless piece of white glass": "白色のガラス玉",
        "worthless piece of blue glass": "青色のガラス玉",
        "worthless piece of red glass": "赤色のガラス玉",
        "worthless piece of yellowish brown glass": "黄褐色のガラス玉",
        "worthless piece of orange glass": "橙色のガラス玉",
        "worthless piece of yellow glass": "黄色のガラス玉",
        "worthless piece of black glass": "黒色のガラス玉",
        "worthless piece of green glass": "緑色のガラス玉",
        "worthless piece of violet glass": "紫色のガラス玉",
        "luckstone": "幸運の石",
        "loadstone": "重い石",
        "touchstone": "試金石",
        "flint": "火打石",
        "rock": "岩",
        "boulder": "巨石",
        "statue": "彫像",
        "heavy iron ball": "重い鉄球",
        "iron chain": "鉄の鎖",
        "splash of blinding venom": "目つぶしの毒液の飛沫",
        "splash of acid venom": "酸の毒液の飛沫"
    },
    "aliases": {
        "sdsm": "silver dragon scale mail",
        "gdsm": "gray dragon scale mail",
        "rdsm": "red dragon scale mail",
        "bdsm": "blue dragon scale mail",
        "ydsm": "yellow dragon scale mail",
        "odsm": "orange dragon scale mail",
        "gdsm_green": "green dragon scale mail",
        "wdsm": "white dragon scale mail",
        "銀鱗": "silver dragon scale mail",
        "灰鱗": "gray dragon scale mail",
        "虐殺": "scroll of genocide",
        "大虐殺": "scroll of genocide",
        "虐殺の巻物": "scroll of genocide",
        "大虐殺の巻物": "scroll of genocide",
        "充填": "scroll of charging",
        "充填の巻物": "scroll of charging",
        "死杖": "wand of death",
        "死の杖": "wand of death",
        "願杖": "wand of wishing",
        "願いの杖": "wand of wishing",
        "目隠し": "blindfold",
        "ホールド鞄": "bag of holding",
        "魔防マント": "cloak of magic resistance",
        "浮遊靴": "levitation boots",
        "早足靴": "speed boots",
        "反射": "amulet of reflection",
        "反射のアミュレット": "amulet of reflection",
        "命救助": "amulet of life saving",
        "生命維持のアミュレット": "amulet of life saving"
    }
};
