/**
 * tilemappings_data.js
 * docs/5_gamedata/tilemappings.lst (Single Source of Truth) より自動抽出
 * 全 384 モンスター (mnum) ＆ 全 481 オブジェクト (onum) 公式名称テーブル
 */

export const MONSTER_TILEMAP_NAMES = {
    "0": "giant ant",
    "1": "killer bee",
    "2": "soldier ant",
    "3": "fire ant",
    "4": "giant beetle",
    "5": "queen bee",
    "6": "acid blob",
    "7": "quivering blob",
    "8": "gelatinous cube",
    "9": "chickatrice",
    "10": "cockatrice",
    "11": "pyrolisk",
    "12": "jackal",
    "13": "fox",
    "14": "coyote",
    "15": "werejackal",
    "16": "little dog",
    "17": "dingo",
    "18": "dog",
    "19": "large dog",
    "20": "wolf",
    "21": "werewolf",
    "22": "winter wolf cub",
    "23": "warg",
    "24": "winter wolf",
    "25": "hell hound pup",
    "26": "hell hound",
    "27": "gas spore",
    "28": "floating eye",
    "29": "freezing sphere",
    "30": "flaming sphere",
    "31": "shocking sphere",
    "32": "kitten",
    "33": "housecat",
    "34": "jaguar",
    "35": "lynx",
    "36": "panther",
    "37": "large cat",
    "38": "tiger",
    "39": "displacer beast",
    "40": "gremlin",
    "41": "gargoyle",
    "42": "winged gargoyle",
    "43": "hobbit",
    "44": "dwarf",
    "45": "bugbear",
    "46": "dwarf leader {dwarf lord}",
    "47": "dwarf ruler {dwarf king}",
    "48": "mind flayer",
    "49": "master mind flayer",
    "50": "manes",
    "51": "homunculus",
    "52": "imp",
    "53": "lemure",
    "54": "quasit",
    "55": "tengu",
    "56": "blue jelly",
    "57": "spotted jelly",
    "58": "ochre jelly",
    "59": "kobold",
    "60": "large kobold",
    "61": "kobold leader {kobold lord}",
    "62": "kobold shaman",
    "63": "leprechaun",
    "64": "small mimic",
    "65": "large mimic",
    "66": "giant mimic",
    "67": "wood nymph",
    "68": "water nymph",
    "69": "mountain nymph",
    "70": "goblin",
    "71": "hobgoblin",
    "72": "orc",
    "73": "hill orc",
    "74": "Mordor orc",
    "75": "Uruk-hai",
    "76": "orc shaman",
    "77": "orc-captain",
    "78": "rock piercer",
    "79": "iron piercer",
    "80": "glass piercer",
    "81": "rothe",
    "82": "mumak",
    "83": "leocrotta",
    "84": "wumpus",
    "85": "titanothere",
    "86": "baluchitherium",
    "87": "mastodon",
    "88": "sewer rat",
    "89": "giant rat",
    "90": "rabid rat",
    "91": "wererat",
    "92": "rock mole",
    "93": "woodchuck",
    "94": "cave spider",
    "95": "centipede",
    "96": "giant spider",
    "97": "scorpion",
    "98": "lurker above",
    "99": "trapper",
    "100": "pony",
    "101": "white unicorn",
    "102": "gray unicorn",
    "103": "black unicorn",
    "104": "horse",
    "105": "warhorse",
    "106": "fog cloud",
    "107": "dust vortex",
    "108": "ice vortex",
    "109": "energy vortex",
    "110": "steam vortex",
    "111": "fire vortex",
    "112": "baby long worm",
    "113": "baby purple worm",
    "114": "long worm",
    "115": "purple worm",
    "116": "grid bug",
    "117": "xan",
    "118": "yellow light",
    "119": "black light",
    "120": "zruty",
    "121": "couatl",
    "122": "Aleax",
    "123": "Angel",
    "124": "ki-rin",
    "125": "Archon",
    "126": "bat",
    "127": "giant bat",
    "128": "raven",
    "129": "vampire bat",
    "130": "plains centaur",
    "131": "forest centaur",
    "132": "mountain centaur",
    "133": "baby gray dragon",
    "134": "baby gold dragon",
    "135": "baby silver dragon",
    "136": "baby red dragon",
    "137": "baby white dragon",
    "138": "baby orange dragon",
    "139": "baby black dragon",
    "140": "baby blue dragon",
    "141": "baby green dragon",
    "142": "baby yellow dragon",
    "143": "gray dragon",
    "144": "gold dragon",
    "145": "silver dragon",
    "146": "red dragon",
    "147": "white dragon",
    "148": "orange dragon",
    "149": "black dragon",
    "150": "blue dragon",
    "151": "green dragon",
    "152": "yellow dragon",
    "153": "stalker",
    "154": "air elemental",
    "155": "fire elemental",
    "156": "earth elemental",
    "157": "water elemental",
    "158": "lichen",
    "159": "brown mold",
    "160": "yellow mold",
    "161": "green mold",
    "162": "red mold",
    "163": "shrieker",
    "164": "violet fungus",
    "165": "gnome",
    "166": "gnome leader {gnome lord}",
    "167": "gnomish wizard",
    "168": "gnome ruler {gnome king}",
    "169": "giant",
    "170": "stone giant",
    "171": "hill giant",
    "172": "fire giant",
    "173": "frost giant",
    "174": "ettin",
    "175": "storm giant",
    "176": "titan",
    "177": "minotaur",
    "178": "jabberwock",
    "179": "Keystone Kop",
    "180": "Kop Sergeant",
    "181": "Kop Lieutenant",
    "182": "Kop Kaptain",
    "183": "lich",
    "184": "demilich",
    "185": "master lich",
    "186": "arch-lich",
    "187": "kobold mummy",
    "188": "gnome mummy",
    "189": "orc mummy",
    "190": "dwarf mummy",
    "191": "elf mummy",
    "192": "human mummy",
    "193": "ettin mummy",
    "194": "giant mummy",
    "195": "red naga hatchling",
    "196": "black naga hatchling",
    "197": "golden naga hatchling",
    "198": "guardian naga hatchling",
    "199": "red naga",
    "200": "black naga",
    "201": "golden naga",
    "202": "guardian naga",
    "203": "ogre",
    "204": "ogre leader {ogre lord}",
    "205": "ogre tyrant {ogre king}",
    "206": "gray ooze",
    "207": "brown pudding",
    "208": "green slime",
    "209": "black pudding",
    "210": "quantum mechanic",
    "211": "genetic engineer",
    "212": "rust monster",
    "213": "disenchanter",
    "214": "garter snake",
    "215": "snake",
    "216": "water moccasin",
    "217": "python",
    "218": "pit viper",
    "219": "cobra",
    "220": "troll",
    "221": "ice troll",
    "222": "rock troll",
    "223": "water troll",
    "224": "Olog-hai",
    "225": "umber hulk",
    "226": "vampire",
    "227": "vampire leader {vampire lord}",
    "228": "Vlad the Impaler",
    "229": "barrow wight",
    "230": "wraith",
    "231": "Nazgul",
    "232": "xorn",
    "233": "monkey",
    "234": "ape",
    "235": "owlbear",
    "236": "yeti",
    "237": "carnivorous ape",
    "238": "sasquatch",
    "239": "kobold zombie",
    "240": "gnome zombie",
    "241": "orc zombie",
    "242": "dwarf zombie",
    "243": "elf zombie",
    "244": "human zombie",
    "245": "ettin zombie",
    "246": "ghoul",
    "247": "giant zombie",
    "248": "skeleton",
    "249": "straw golem",
    "250": "paper golem",
    "251": "rope golem",
    "252": "gold golem",
    "253": "leather golem",
    "254": "wood golem",
    "255": "flesh golem",
    "256": "clay golem",
    "257": "stone golem",
    "258": "glass golem",
    "259": "iron golem",
    "260": "human",
    "261": "wererat",
    "262": "werejackal",
    "263": "werewolf",
    "264": "elf",
    "265": "Woodland-elf",
    "266": "Green-elf",
    "267": "Grey-elf",
    "268": "elf-noble {elf-lord}",
    "269": "elven monarch {Elvenking}",
    "270": "doppelganger",
    "271": "shopkeeper",
    "272": "guard",
    "273": "prisoner",
    "274": "Oracle",
    "275": "aligned cleric {priest}",
    "276": "high cleric {high priest}",
    "277": "soldier",
    "278": "sergeant",
    "279": "nurse",
    "280": "lieutenant",
    "281": "captain",
    "282": "watchman",
    "283": "watch captain",
    "284": "Medusa",
    "285": "Wizard of Yendor",
    "286": "Croesus",
    "287": "ghost",
    "288": "shade",
    "289": "water demon",
    "290": "amorous demon {incubus}",
    "291": "horned devil",
    "292": "erinys",
    "293": "barbed devil",
    "294": "marilith",
    "295": "vrock",
    "296": "hezrou",
    "297": "bone devil",
    "298": "ice devil",
    "299": "nalfeshnee",
    "300": "pit fiend",
    "301": "sandestin",
    "302": "balrog",
    "303": "Juiblex",
    "304": "Yeenoghu",
    "305": "Orcus",
    "306": "Geryon",
    "307": "Dispater",
    "308": "Baalzebub",
    "309": "Asmodeus",
    "310": "Demogorgon",
    "311": "Death",
    "312": "Pestilence",
    "313": "Famine",
    "314": "mail daemon",
    "315": "djinni",
    "316": "jellyfish",
    "317": "piranha",
    "318": "shark",
    "319": "giant eel",
    "320": "electric eel",
    "321": "kraken",
    "322": "newt",
    "323": "gecko",
    "324": "iguana",
    "325": "baby crocodile",
    "326": "lizard",
    "327": "chameleon",
    "328": "crocodile",
    "329": "salamander",
    "330": "long worm tail",
    "331": "archeologist",
    "332": "barbarian",
    "333": "cave dweller {caveman}",
    "334": "healer",
    "335": "knight",
    "336": "monk",
    "337": "cleric {priest}",
    "338": "ranger",
    "339": "rogue",
    "340": "samurai",
    "341": "tourist",
    "342": "valkyrie",
    "343": "wizard",
    "344": "Lord Carnarvon",
    "345": "Pelias",
    "346": "Shaman Karnov",
    "347": "Hippocrates",
    "348": "King Arthur",
    "349": "Grand Master",
    "350": "Arch Priest",
    "351": "Orion",
    "352": "Master of Thieves",
    "353": "Lord Sato",
    "354": "Twoflower",
    "355": "Norn",
    "356": "Neferet the Green",
    "357": "Minion of Huhetotl",
    "358": "Thoth Amon",
    "359": "Chromatic Dragon",
    "360": "Cyclops",
    "361": "Ixoth",
    "362": "Master Kaen",
    "363": "Nalzok",
    "364": "Scorpius",
    "365": "Master Assassin",
    "366": "Ashikaga Takauji",
    "367": "Lord Surtur",
    "368": "Dark One",
    "369": "student",
    "370": "chieftain",
    "371": "neanderthal",
    "372": "attendant",
    "373": "page",
    "374": "abbot",
    "375": "acolyte",
    "376": "hunter",
    "377": "thug",
    "378": "ninja",
    "379": "roshi",
    "380": "guide",
    "381": "warrior",
    "382": "apprentice",
    "788": "invisible mon"
};

export const OBJECT_TILEMAP_NAMES = {
    "0": "strange object",
    "1": "strange / generic strange",
    "2": "weapon / generic weapon",
    "3": "armor / generic armor",
    "4": "ring / generic ring",
    "5": "amulet / generic amulet",
    "6": "tool / generic tool",
    "7": "food / generic food",
    "8": "potion / generic potion",
    "9": "scroll / generic scroll",
    "10": "spellbook / generic spellbook",
    "11": "wand / generic wand",
    "12": "coin / generic coin",
    "13": "gem / generic gem",
    "14": "large rock / generic large rock",
    "15": "iron ball / generic iron ball",
    "16": "iron chain / generic iron chain",
    "17": "venom / generic venom",
    "18": "arrow",
    "19": "runed arrow / elven arrow",
    "20": "crude arrow / orcish arrow",
    "21": "silver arrow",
    "22": "bamboo arrow / ya",
    "23": "crossbow bolt",
    "24": "dart",
    "25": "throwing star / shuriken",
    "26": "boomerang",
    "27": "spear",
    "28": "runed spear / elven spear",
    "29": "crude spear / orcish spear",
    "30": "stout spear / dwarvish spear",
    "31": "silver spear",
    "32": "throwing spear / javelin",
    "33": "trident",
    "34": "dagger",
    "35": "runed dagger / elven dagger",
    "36": "crude dagger / orcish dagger",
    "37": "silver dagger",
    "38": "athame",
    "39": "scalpel",
    "40": "knife",
    "41": "stiletto",
    "42": "worm tooth",
    "43": "crysknife",
    "44": "axe",
    "45": "double-headed axe / battle-axe",
    "46": "short sword",
    "47": "runed short sword / elven short sword",
    "48": "crude short sword / orcish short sword",
    "49": "broad short sword / dwarvish short sword",
    "50": "curved sword / scimitar",
    "51": "silver saber",
    "52": "broadsword",
    "53": "runed broadsword / elven broadsword",
    "54": "long sword",
    "55": "two-handed sword",
    "56": "samurai sword / katana",
    "57": "long samurai sword / tsurugi",
    "58": "runed broadsword / runesword",
    "59": "vulgar polearm / partisan",
    "60": "hilted polearm / ranseur",
    "61": "forked polearm / spetum",
    "62": "single-edged polearm / glaive",
    "63": "angled poleaxe / halberd",
    "64": "long poleaxe / bardiche",
    "65": "pole cleaver / voulge",
    "66": "pole sickle / fauchard",
    "67": "pruning hook / guisarme",
    "68": "hooked polearm / bill-guisarme",
    "69": "pronged polearm / lucern hammer",
    "70": "beaked polearm / bec de corbin",
    "71": "broad pick / dwarvish mattock",
    "72": "lance",
    "73": "mace",
    "74": "silver mace",
    "75": "morning star",
    "76": "war hammer",
    "77": "club",
    "78": "rubber hose",
    "79": "staff / quarterstaff",
    "80": "thonged club / aklys",
    "81": "flail",
    "82": "bullwhip",
    "83": "bow",
    "84": "runed bow / elven bow",
    "85": "crude bow / orcish bow",
    "86": "long bow / yumi",
    "87": "sling",
    "88": "crossbow",
    "89": "leather hat / elven leather helm",
    "90": "iron skull cap / orcish helm",
    "91": "hard hat / dwarvish iron helm",
    "92": "fedora",
    "93": "conical hat / cornuthaum",
    "94": "conical hat / dunce cap",
    "95": "dented pot",
    "96": "crystal helmet / helm of brilliance",
    "97": "plumed helmet / helmet",
    "98": "etched helmet / helm of caution",
    "99": "crested helmet / helm of opposite alignment",
    "100": "visored helmet / helm of telepathy",
    "101": "gray dragon scale mail",
    "102": "gold dragon scale mail",
    "103": "silver dragon scale mail",
    "104": "red dragon scale mail",
    "105": "white dragon scale mail",
    "106": "orange dragon scale mail",
    "107": "black dragon scale mail",
    "108": "blue dragon scale mail",
    "109": "green dragon scale mail",
    "110": "yellow dragon scale mail",
    "111": "gray dragon scales",
    "112": "gold dragon scales",
    "113": "silver dragon scales",
    "114": "red dragon scales",
    "115": "white dragon scales",
    "116": "orange dragon scales",
    "117": "black dragon scales",
    "118": "blue dragon scales",
    "119": "green dragon scales",
    "120": "yellow dragon scales",
    "121": "plate mail",
    "122": "crystal plate mail",
    "123": "bronze plate mail",
    "124": "splint mail",
    "125": "banded mail",
    "126": "dwarvish mithril-coat",
    "127": "elven mithril-coat",
    "128": "chain mail",
    "129": "crude chain mail / orcish chain mail",
    "130": "scale mail",
    "131": "studded leather armor",
    "132": "ring mail",
    "133": "crude ring mail / orcish ring mail",
    "134": "leather armor",
    "135": "leather jacket",
    "136": "Hawaiian shirt",
    "137": "T-shirt",
    "138": "mummy wrapping",
    "139": "faded pall / elven cloak",
    "140": "coarse mantelet / orcish cloak",
    "141": "hooded cloak / dwarvish cloak",
    "142": "slippery cloak / oilskin cloak",
    "143": "robe",
    "144": "apron / alchemy smock",
    "145": "leather cloak",
    "146": "tattered cape / cloak of protection",
    "147": "opera cloak / cloak of invisibility",
    "148": "ornamental cope / cloak of magic resistance",
    "149": "piece of cloth / cloak of displacement",
    "150": "wooden shield / small shield",
    "151": "wooden shield / shield of drain resistance",
    "152": "wooden shield / shield of shock resistance",
    "153": "blue and green shield / elven shield",
    "154": "white-handed shield / Uruk-hai shield",
    "155": "red-eyed shield / orcish shield",
    "156": "large shield",
    "157": "large round shield / dwarvish roundshield",
    "158": "polished silver shield / shield of reflection",
    "159": "old gloves / leather gloves",
    "160": "padded gloves / gauntlets of fumbling",
    "161": "riding gloves / gauntlets of power",
    "162": "fencing gloves / gauntlets of dexterity",
    "163": "walking shoes / low boots",
    "164": "hard shoes / iron shoes",
    "165": "jackboots / high boots",
    "166": "combat boots / speed boots",
    "167": "jungle boots / water walking boots",
    "168": "hiking boots / jumping boots",
    "169": "mud boots / elven boots",
    "170": "buckled boots / kicking boots",
    "171": "riding boots / fumble boots",
    "172": "snow boots / levitation boots",
    "173": "wooden / adornment",
    "174": "granite / gain strength",
    "175": "opal / gain constitution",
    "176": "clay / increase accuracy",
    "177": "coral / increase damage",
    "178": "black onyx / protection",
    "179": "moonstone / regeneration",
    "180": "tiger eye / searching",
    "181": "jade / stealth",
    "182": "bronze / sustain ability",
    "183": "agate / levitation",
    "184": "topaz / hunger",
    "185": "sapphire / aggravate monster",
    "186": "ruby / conflict",
    "187": "diamond / warning",
    "188": "pearl / poison resistance",
    "189": "iron / fire resistance",
    "190": "brass / cold resistance",
    "191": "copper / shock resistance",
    "192": "twisted / free action",
    "193": "steel / slow digestion",
    "194": "silver / teleportation",
    "195": "gold / teleport control",
    "196": "ivory / polymorph",
    "197": "emerald / polymorph control",
    "198": "wire / invisibility",
    "199": "engagement / see invisible",
    "200": "shiny / protection from shape changers",
    "201": "circular / amulet of ESP",
    "202": "spherical / amulet of life saving",
    "203": "oval / amulet of strangulation",
    "204": "triangular / amulet of restful sleep",
    "205": "pyramidal / amulet versus poison",
    "206": "square / amulet of change",
    "207": "concave / amulet of unchanging",
    "208": "hexagonal / amulet of reflection",
    "209": "octagonal / amulet of magical breathing",
    "210": "perforated / amulet of guarding",
    "211": "cubical / amulet of flying",
    "212": "Amulet of Yendor / cheap plastic imitation of the Amulet of Yendor",
    "213": "Amulet of Yendor / Amulet of Yendor",
    "214": "large box",
    "215": "chest",
    "216": "ice box",
    "217": "bag / sack",
    "218": "bag / oilskin sack",
    "219": "bag / bag of holding",
    "220": "bag / bag of tricks",
    "221": "key / skeleton key",
    "222": "lock pick",
    "223": "credit card",
    "224": "candle / tallow candle",
    "225": "candle / wax candle",
    "226": "brass lantern",
    "227": "lamp / oil lamp",
    "228": "lamp / magic lamp",
    "229": "expensive camera",
    "230": "looking glass / mirror",
    "231": "glass orb / crystal ball",
    "232": "lenses",
    "233": "blindfold",
    "234": "towel",
    "235": "saddle",
    "236": "leash",
    "237": "stethoscope",
    "238": "tinning kit",
    "239": "tin opener",
    "240": "can of grease",
    "241": "figurine",
    "242": "magic marker",
    "243": "land mine",
    "244": "beartrap",
    "245": "whistle / tin whistle",
    "246": "whistle / magic whistle",
    "247": "flute / wooden flute",
    "248": "flute / magic flute",
    "249": "horn / tooled horn",
    "250": "horn / frost horn",
    "251": "horn / fire horn",
    "252": "horn / horn of plenty",
    "253": "harp / wooden harp",
    "254": "harp / magic harp",
    "255": "bell",
    "256": "bugle",
    "257": "drum / leather drum",
    "258": "drum / drum of earthquake",
    "259": "pick-axe",
    "260": "grappling hook",
    "261": "unicorn horn",
    "262": "candelabrum / Candelabrum of Invocation",
    "263": "silver bell / Bell of Opening",
    "264": "tripe ration",
    "265": "corpse",
    "266": "egg",
    "267": "meatball",
    "268": "meat stick",
    "269": "enormous meatball",
    "270": "meat ring",
    "271": "glob of gray ooze",
    "272": "glob of brown pudding",
    "273": "glob of green slime",
    "274": "glob of black pudding",
    "275": "kelp frond",
    "276": "eucalyptus leaf",
    "277": "apple",
    "278": "orange",
    "279": "pear",
    "280": "melon",
    "281": "banana",
    "282": "carrot",
    "283": "sprig of wolfsbane",
    "284": "clove of garlic",
    "285": "slime mold",
    "286": "lump of royal jelly",
    "287": "cream pie",
    "288": "candy bar",
    "289": "fortune cookie",
    "290": "pancake",
    "291": "lembas wafer",
    "292": "cram ration",
    "293": "food ration",
    "294": "K-ration",
    "295": "C-ration",
    "296": "tin",
    "297": "ruby / gain ability",
    "298": "pink / restore ability",
    "299": "orange / confusion",
    "300": "yellow / blindness",
    "301": "emerald / paralysis",
    "302": "dark green / speed",
    "303": "cyan / levitation",
    "304": "sky blue / hallucination",
    "305": "brilliant blue / invisibility",
    "306": "magenta / see invisible",
    "307": "purple-red / healing",
    "308": "puce / extra healing",
    "309": "milky / gain level",
    "310": "swirly / enlightenment",
    "311": "bubbly / monster detection",
    "312": "smoky / object detection",
    "313": "cloudy / gain energy",
    "314": "effervescent / sleeping",
    "315": "black / full healing",
    "316": "golden / polymorph",
    "317": "brown / booze",
    "318": "fizzy / sickness",
    "319": "dark / fruit juice",
    "320": "white / acid",
    "321": "murky / oil",
    "322": "clear / water",
    "323": "ZELGO MER / enchant armor",
    "324": "JUYED AWK YACC / destroy armor",
    "325": "NR 9 / confuse monster",
    "326": "XIXAXA XOXAXA XUXAXA / scare monster",
    "327": "PRATYAVAYAH / remove curse",
    "328": "DAIYEN FOOELS / enchant weapon",
    "329": "LEP GEX VEN ZEA / create monster",
    "330": "PRIRUTSENIE / taming",
    "331": "ELBIB YLOH / genocide",
    "332": "VERR YED HORRE / light",
    "333": "VENZAR BORGAVVE / teleportation",
    "334": "THARR / gold detection",
    "335": "YUM YUM / food detection",
    "336": "KERNOD WEL / identify",
    "337": "ELAM EBOW / magic mapping",
    "338": "DUAM XNAHT / amnesia",
    "339": "ANDOVA BEGARIN / fire",
    "340": "KIRJE / earth",
    "341": "VE FORBRYDERNE / punishment",
    "342": "HACKEM MUCHE / charging",
    "343": "VELOX NEB / stinking cloud",
    "344": "FOOBIE BLETCH",
    "345": "TEMOV",
    "346": "GARVEN DEH",
    "347": "READ ME",
    "348": "ETAOIN SHRDLU",
    "349": "LOREM IPSUM",
    "350": "FNORD",
    "351": "KO BATE",
    "352": "ABRA KA DABRA",
    "353": "ASHPD SODALG",
    "354": "ZLORFIK",
    "355": "GNIK SISI VLE",
    "356": "HAPAX LEGOMENON",
    "357": "EIRIS SAZUN IDISI",
    "358": "PHOL ENDE WODAN",
    "359": "GHOTI",
    "360": "MAPIRO MAHAMA DIROMAT",
    "361": "VAS CORP BET MANI",
    "362": "XOR OTA",
    "363": "STRC PRST SKRZ KRK",
    "364": "stamped / mail",
    "365": "unlabeled / blank paper",
    "366": "parchment / dig",
    "367": "vellum / magic missile",
    "368": "ragged / fireball",
    "369": "dog eared / cone of cold",
    "370": "mottled / sleep",
    "371": "stained / finger of death",
    "372": "cloth / light",
    "373": "leathery / detect monsters",
    "374": "white / healing",
    "375": "pink / knock",
    "376": "red / force bolt",
    "377": "orange / confuse monster",
    "378": "yellow / cure blindness",
    "379": "velvet / drain life",
    "380": "light green / slow monster",
    "381": "dark green / wizard lock",
    "382": "turquoise / create monster",
    "383": "cyan / detect food",
    "384": "light blue / cause fear",
    "385": "dark blue / clairvoyance",
    "386": "indigo / cure sickness",
    "387": "magenta / charm monster",
    "388": "purple / haste self",
    "389": "violet / detect unseen",
    "390": "tan / levitation",
    "391": "plaid / extra healing",
    "392": "light brown / restore ability",
    "393": "dark brown / invisibility",
    "394": "gray / detect treasure",
    "395": "wrinkled / remove curse",
    "396": "dusty / magic mapping",
    "397": "bronze / identify",
    "398": "copper / turn undead",
    "399": "silver / polymorph",
    "400": "gold / teleport away",
    "401": "glittering / create familiar",
    "402": "shining / cancellation",
    "403": "dull / protection",
    "404": "thin / jumping",
    "405": "thick / stone to flesh",
    "406": "checkered / chain lightning",
    "407": "plain / blank paper",
    "408": "paperback / novel",
    "409": "papyrus / Book of the Dead",
    "410": "glass / light",
    "411": "balsa / secret door detection",
    "412": "crystal / enlightenment",
    "413": "maple / create monster",
    "414": "pine / wishing",
    "415": "redwood / stasis",
    "416": "oak / nothing",
    "417": "ebony / striking",
    "418": "marble / make invisible",
    "419": "tin / slow monster",
    "420": "brass / speed monster",
    "421": "copper / undead turning",
    "422": "silver / polymorph",
    "423": "platinum / cancellation",
    "424": "iridium / teleportation",
    "425": "zinc / opening",
    "426": "aluminum / locking",
    "427": "uranium / probing",
    "428": "iron / digging",
    "429": "steel / magic missile",
    "430": "hexagonal / fire",
    "431": "short / cold",
    "432": "runed / sleep",
    "433": "long / death",
    "434": "curved / lightning",
    "435": "forked",
    "436": "spiked",
    "437": "jeweled",
    "438": "gold piece",
    "439": "white / dilithium crystal",
    "440": "white / diamond",
    "441": "red / ruby",
    "442": "orange / jacinth",
    "443": "blue / sapphire",
    "444": "black / black opal",
    "445": "green / emerald",
    "446": "green / turquoise",
    "447": "yellow / citrine",
    "448": "green / aquamarine",
    "449": "yellowish brown / amber",
    "450": "yellowish brown / topaz",
    "451": "black / jet",
    "452": "white / opal",
    "453": "yellow / chrysoberyl",
    "454": "red / garnet",
    "455": "violet / amethyst",
    "456": "red / jasper",
    "457": "violet / fluorite",
    "458": "black / obsidian",
    "459": "orange / agate",
    "460": "green / jade",
    "461": "white / worthless piece of white glass",
    "462": "blue / worthless piece of blue glass",
    "463": "red / worthless piece of red glass",
    "464": "yellowish brown / worthless piece of yellowish brown glass",
    "465": "orange / worthless piece of orange glass",
    "466": "yellow / worthless piece of yellow glass",
    "467": "black / worthless piece of black glass",
    "468": "green / worthless piece of green glass",
    "469": "violet / worthless piece of violet glass",
    "470": "gray / luckstone",
    "471": "gray / loadstone",
    "472": "gray / touchstone",
    "473": "gray / flint",
    "474": "rock",
    "475": "boulder",
    "476": "statue",
    "477": "heavy iron ball",
    "478": "iron chain",
    "479": "splash of venom / splash of blinding venom",
    "480": "splash of venom / splash of acid venom"
};
