# NetHackJP WebAssembly Build Script for Windows
# Compiles satokiyon/NetHackJP to Wasm for WebUI

$ErrorActionPreference = "Stop"

$BASE_ROOT = $PWD
$NH_ROOT = Join-Path $BASE_ROOT "NetHackJP"
$EMSDK_PATH = "C:\Users\e3-sh\Documents\GitHub\emsdk"
$VCVARS_PATH = "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvarsall.bat"

Write-Host "=== Building NetHackJP Wasm ==="

# 1. Setup Environments
Write-Host "--- Setting up environments ---"
if (Test-Path "$EMSDK_PATH\emsdk_env.ps1") {
    & "$EMSDK_PATH\emsdk_env.ps1"
}
else {
    Write-Error "Emscripten SDK not found at $EMSDK_PATH"
}

if (!(Get-Command cl -ErrorAction SilentlyContinue)) {
    Write-Host "Activating MSVC..."
    $vcvars_cmd = "`"$VCVARS_PATH`" x64 && set"
    $env_vars = cmd /c $vcvars_cmd
    foreach ($line in $env_vars) {
        if ($line -match "^(.*?)=(.*)$") {
            $name = $Matches[1]
            $value = $Matches[2]
            if ($name -ne "" -and $name -notmatch " ") {
                Set-Item "env:$name" $value
            }
        }
    }
}

# 2. Patch winshim.c into NetHackJP
Write-Host "--- Copying winshim.c to NetHackJP/win/shim ---"
$shim_src = Join-Path $BASE_ROOT "NetHack-NetHack-5.0/win/shim/winshim.c"
$shim_dst = Join-Path $NH_ROOT "win/shim/winshim.c"
if (Test-Path $shim_src) {
    if (!(Test-Path (Split-Path $shim_dst))) {
        New-Item -ItemType Directory -Path (Split-Path $shim_dst) -Force
    }
    Copy-Item $shim_src $shim_dst -Force
} else {
    Write-Error "Source winshim.c not found at $shim_src"
}

Set-Location $NH_ROOT

# 3. Generate nhlua.h
Write-Host "--- Generating nhlua.h ---"
$nhlua_content = @"
/* nhlua.h - generated by build_wasm_jp.ps1 */
#include "lua.h"
LUA_API int (lua_error) (lua_State *L) NORETURN;
#include "lualib.h"
#include "lauxlib.h"
/*nhlua.h*/
"@
$nhlua_content | Out-File -FilePath "include/nhlua.h" -Encoding ascii

# 4. Build Host Utilities (makedefs, tilemap) if needed
Write-Host "--- Step 1: Building makedefs (Host) ---"
$LUA_INC = "submodules/lua"
$makedefs_src = @(
    "util/makedefs.c",
    "src/monst.c",
    "src/objects.c",
    "src/alloc.c",
    "util/panic.c",
    "src/hacklib.c",
    "src/date.c",
    "src/mon_jp.c",
    "src/obj_jp.c"
)
cl /utf-8 /O2 /Iinclude /Isys/windows /I$LUA_INC /DCROSSCOMPILE /DWIN32 $makedefs_src /link /out:util/makedefs.exe

Write-Host "--- Step 1-b: Building tilemap (Host) ---"
$tilemap_src = @(
    "win/share/tilemap.c",
    "src/monst.c",
    "src/objects.c",
    "src/drawing.c",
    "src/hacklib.c",
    "util/panic.c",
    "src/alloc.c"
)
cl /utf-8 /O2 /Iinclude /Isys/windows /I$LUA_INC /DCROSSCOMPILE /DWIN32 $tilemap_src /link /out:util/tilemap.exe
if ($LASTEXITCODE -eq 0) {
    Write-Host "Running tilemap.exe to generate tilemappings.lst..."
    Unblock-File util/tilemap.exe -ErrorAction SilentlyContinue
    cmd /c "cd /d `"$NH_ROOT\util`" && tilemap.exe"
    Copy-Item "util/tilemappings.lst" "./" -Force -ErrorAction SilentlyContinue
}

# 5. Generate data files
Write-Host "--- Step 2: Generating data files ---"
if (Test-Path "util/makedefs.exe") {
    Unblock-File util/makedefs.exe -ErrorAction SilentlyContinue
    $util_dir = Join-Path $NH_ROOT "util"
    cmd /c "cd /d `"$util_dir`" && makedefs.exe -d && makedefs.exe -r && makedefs.exe -h && makedefs.exe -s && makedefs.exe -o"
}

# 6. Build NetHackJP Wasm (including Lua sources directly)
Write-Host "--- Step 3: Compiling NetHackJP + Lua (Wasm) ---"
$lua_src = Get-ChildItem "$LUA_INC/*.c" | Where-Object { $_.Name -notmatch "lua.c|luac.c" } | ForEach-Object { "submodules/lua/$($_.Name)" }

$nethack_src = @(
    "src/allmain.c", "src/alloc.c", "src/apply.c", "src/artifact.c", "src/attrib.c",
    "src/ball.c", "src/bones.c", "src/botl.c", "src/calendar.c", "src/cfgfiles.c", "src/coloratt.c",
    "src/cmd.c", "src/date.c", "src/dbridge.c", "src/decl.c", "src/detect.c", "src/dig.c",
    "src/display.c", "src/dlb.c", "src/do.c", "src/do_name.c", "src/do_wear.c",
    "src/dog.c", "src/dogmove.c", "src/dokick.c", "src/dothrow.c", "src/drawing.c",
    "src/dungeon.c", "src/earlyarg.c", "src/eat.c", "src/end.c", "src/engrave.c",
    "src/exper.c", "src/explode.c", "src/extralev.c", "src/files.c", "src/fountain.c",
    "src/getpos.c", "src/glyphs.c", "src/hack.c", "src/hacklib.c", "src/iactions.c",
    "src/insight.c", "src/invent.c", "src/isaac64.c", "src/light.c", "src/lock.c",
    "src/mail.c", "src/makemon.c", "src/mcastu.c", "src/mdlib.c", "src/mhitm.c",
    "src/mhitu.c", "src/minion.c", "src/mklev.c", "src/mkmap.c", "src/mkmaze.c",
    "src/mkobj.c", "src/mkroom.c", "src/mon.c", "src/mondata.c", "src/monmove.c",
    "src/monst.c", "src/mplayer.c", "src/mthrowu.c", "src/muse.c", "src/music.c",
    "src/nhlua.c", "src/nhlsel.c", "src/nhlobj.c", "src/nhmd4.c", "src/objects.c",
    "src/o_init.c", "src/objnam.c", "src/options.c", "src/pager.c", "src/pickup.c",
    "src/pline.c", "src/polyself.c", "src/potion.c", "src/pray.c", "src/priest.c",
    "src/quest.c", "src/questpgr.c", "src/read.c", "src/rect.c", "src/region.c",
    "src/report.c", "src/restore.c", "src/revision.c", "src/rip.c", "src/rnd.c", "src/role.c",
    "src/rumors.c", "src/save.c", "src/selvar.c", "src/sfbase.c", "src/sfstruct.c", "src/shk.c",
    "src/shknam.c", "src/sit.c", "src/sounds.c", "src/sp_lev.c", "src/spell.c",
    "src/stairs.c", "src/steal.c", "src/steed.c", "src/strutil.c", "src/symbols.c", "src/sys.c",
    "src/teleport.c", "src/timeout.c", "src/topten.c", "src/track.c", "src/trap.c",
    "src/u_init.c", "src/uhitm.c", "src/utf8map.c", "src/vault.c", "src/version.c",
    "src/vision.c", "src/weapon.c", "src/were.c", "src/wield.c", "src/windows.c",
    "src/wizard.c", "src/wizcmds.c", "src/worm.c", "src/worn.c", "src/write.c",
    "src/zap.c",
    # NetHackJP Custom C Sources
    "src/jp_data_lookup.c", "src/mon_jp.c", "src/obj_jp.c", "src/spell_jp.c"
)
$wasm_sys_src = @(
    "sys/libnh/libnhmain.c",
    "sys/share/ioctl.c",
    "sys/share/unixtty.c",
    "sys/share/pmatchregex.c",
    "sys/unix/unixunix.c",
    "sys/unix/unixres.c",
    "win/shim/winshim.c"
)
$all_src = $lua_src + $nethack_src + $wasm_sys_src
$all_src | ForEach-Object { "`"$_`"" } | Out-File -FilePath nethack_files.rsp -Encoding ascii

$emcc_flags = @(
    "-O2",
    "-Iinclude",
    "-I$LUA_INC",
    "-DCROSSCOMPILE",
    "-DCROSSCOMPILE_TARGET",
    "-DCROSS_TO_WASM",
    "-DNOTTYGRAPHICS",
    "-DSHIM_GRAPHICS",
    "-DLIBNH",
    "-DNOMAIL",
    "-DNO_SIGNAL",
    "-sASYNCIFY=1",
    "-sASYNCIFY_IMPORTS=['local_callback']",
    "-sEXPORTED_FUNCTIONS=['_main','_shim_graphics_set_callback','_repopulate_perminvent','_malloc','_get_plname','_get_nummons','_get_num_objects']",
    "-sEXPORTED_RUNTIME_METHODS=['cwrap','ccall','addFunction','UTF8ToString','stringToUTF8','getValue','setValue','FS','IDBFS']",
    "-sDYNCALLS=1",
    "-lidbfs.js",
    "-sALLOW_TABLE_GROWTH=1",
    "-sALLOW_MEMORY_GROWTH=1",
    "-sERROR_ON_UNDEFINED_SYMBOLS=0"
)
$emcc_flags | Out-File -FilePath nethack_flags.rsp -Encoding ascii

# 7. Final Link with embedded files
Write-Host "--- Step 4: Linking and Packaging (nethack_jp.js / nethack_jp.wasm) ---"
Unblock-File "C:\Users\e3-sh\Documents\GitHub\emsdk\upstream\bin\wasm-emscripten-finalize.exe" -ErrorAction SilentlyContinue
cmd /c "emcc @nethack_files.rsp @nethack_flags.rsp -o nethack_jp.js --embed-file dat@/"

# 8. Deploy outputs
Write-Host "--- Step 5: Deploying build outputs ---"
Copy-Item "nethack_jp.js" "$BASE_ROOT/" -Force
Copy-Item "nethack_jp.wasm" "$BASE_ROOT/" -Force

Set-Location $BASE_ROOT

Write-Host "=== NetHackJP Wasm Build Complete! ==="
