# NetHack 5.0 WebAssembly Build Script for Windows
# Official 100% Unmodified C-Core Build

param(
    [string]$NH_ROOT = "C:\Users\e3-sh\Desktop\works\NetHack-NetHack-5.0_org\NetHack-NetHack-5.0.1",
    [string]$EMSDK_PATH = "C:\Users\e3-sh\Documents\GitHub\emsdk",
    [string]$VCVARS_PATH = "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvarsall.bat",
    [string]$LUA_SOURCE_FALLBACK = "C:\Users\e3-sh\Documents\Antigravity\NetHack\lib\lua-5.4.8"
)

$ErrorActionPreference = "Stop"

if (!(Test-Path $NH_ROOT)) {
    Write-Error "NetHack root not found at $NH_ROOT"
}

$DEPLOY_ROOT = (Resolve-Path "$PSScriptRoot/../").Path
Write-Host "NetHack Root: $NH_ROOT"
Write-Host "Deploy Root : $DEPLOY_ROOT"

# 1. Setup Environments
Write-Host "--- Setting up environments ---"
if (Test-Path "$EMSDK_PATH\emsdk_env.ps1") {
    & "$EMSDK_PATH\emsdk_env.ps1"
} else {
    Write-Error "Emscripten SDK not found at $EMSDK_PATH"
}

if (!(Get-Command cl -ErrorAction SilentlyContinue)) {
    Write-Host "Activating MSVC..."
    $vcvars_cmd = "`"$VCVARS_PATH`" x64 && set"
    $env_vars = cmd /c $vcvars_cmd
    foreach ($line in $env_vars) {
        if ($line -match "^(.*?)=(.*)$") {
            $name = $Matches[1]
            $value = $Matches[2]
            if ($name -ne "" -and $name -notmatch " ") {
                Set-Item "env:$name" $value
            }
        }
    }
}

Push-Location $NH_ROOT
try {
    # 1.5 Prepare Lua source & Generate nhlua.h
    $LUA_VERSION = "5.4.8"
    $LUA_SRC_DIR = "lib/lua-$LUA_VERSION/src"
    if (!(Test-Path $LUA_SRC_DIR)) {
        if (Test-Path $LUA_SOURCE_FALLBACK) {
            Write-Host "Preparing Lua source from $LUA_SOURCE_FALLBACK..."
            New-Item -ItemType Directory -Path "lib" -Force | Out-Null
            Copy-Item -Path $LUA_SOURCE_FALLBACK -Destination "lib/lua-$LUA_VERSION" -Recurse -Force
        } else {
            Write-Error "Lua source not found at $LUA_SRC_DIR or $LUA_SOURCE_FALLBACK."
        }
    }

    Write-Host "--- Generating nhlua.h ---"
    $nhlua_content = @"
/* nhlua.h - generated by build_wasm_50.ps1 */
#include "lua.h"
LUA_API int (lua_error) (lua_State *L) NORETURN;
#include "lualib.h"
#include "lauxlib.h"
/*nhlua.h*/
"@
    $nhlua_content | Out-File -FilePath "include/nhlua.h" -Encoding ascii

    # 2. Build Host Utilities (makedefs)
    Write-Host "--- Step 1: Building makedefs (Host) ---"
    $makedefs_src = @(
        "util/makedefs.c",
        "src/monst.c",
        "src/objects.c",
        "src/alloc.c",
        "util/panic.c",
        "src/hacklib.c",
        "src/date.c"
    )
    cl /O2 /Iinclude /Ilib/lua-5.4.8/src /DCROSSCOMPILE $makedefs_src /link /out:util/makedefs.exe

    Write-Host "--- Step 1-b: Building tilemap (Host) ---"
    $tilemap_src = @(
        "win/share/tilemap.c",
        "src/monst.c",
        "src/objects.c",
        "src/drawing.c",
        "src/hacklib.c",
        "util/panic.c",
        "src/alloc.c"
    )
    cl /O2 /Iinclude /Ilib/lua-5.4.8/src /DCROSSCOMPILE $tilemap_src /link /out:util/tilemap.exe
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Running tilemap.exe to generate tile.c and tilemappings.lst..."
        Push-Location util
        .\tilemap.exe
        Pop-Location
    }

    # 3. Generate data files
    Write-Host "--- Step 2: Generating data files ---"
    if (Test-Path "util/makedefs.exe") {
        Push-Location util
        .\makedefs.exe -d
        .\makedefs.exe -r
        .\makedefs.exe -h
        .\makedefs.exe -s
        .\makedefs.exe -o
        Pop-Location
    } else {
        Write-Error "makedefs.exe was not built successfully."
    }

    # 4. Official winshim.c verification (Unmodified)
    Write-Host "--- Step 3: Verifying winshim.c (Official Unmodified) ---"
    if (Test-Path "win/shim/winshim.c") {
        Write-Host "win/shim/winshim.c confirmed (official unmodified C source directly used)."
    } else {
        Write-Error "win/shim/winshim.c not found in $NH_ROOT."
    }

    # 5. Build Wasm Lua
    Write-Host "--- Step 4: Building Lua (Wasm) ---"
    $lua_src_files = Get-ChildItem "$LUA_SRC_DIR/*.c" | Where-Object { $_.Name -notmatch "lua.c|luac.c" } 
    $lua_src_files | ForEach-Object { "`"$($_.FullName)`"" } | Out-File -FilePath lua_files.rsp -Encoding ascii

    emcc -O3 -c "@lua_files.rsp" -I$LUA_SRC_DIR

    $lua_obj_files = Get-ChildItem "*.o" | ForEach-Object { $_.Name }
    if (Test-Path "liblua.a") { Remove-Item "liblua.a" }
    foreach ($obj in $lua_obj_files) {
        & emar r liblua.a $obj
    }
    & emar s liblua.a
    Remove-Item *.o

    # 6. Build NetHack Wasm
    Write-Host "--- Step 5: Building NetHack (Wasm) ---"
    $nethack_src = @(
        "src/allmain.c", "src/alloc.c", "src/apply.c", "src/artifact.c", "src/attrib.c",
        "src/ball.c", "src/bones.c", "src/botl.c", "src/calendar.c", "src/cfgfiles.c", "src/coloratt.c",
        "src/cmd.c", "src/date.c", "src/dbridge.c", "src/decl.c", "src/detect.c", "src/dig.c",
        "src/display.c", "src/dlb.c", "src/do.c", "src/do_name.c", "src/do_wear.c",
        "src/dog.c", "src/dogmove.c", "src/dokick.c", "src/dothrow.c", "src/drawing.c",
        "src/dungeon.c", "src/earlyarg.c", "src/eat.c", "src/end.c", "src/engrave.c",
        "src/exper.c", "src/explode.c", "src/extralev.c", "src/files.c", "src/fountain.c",
        "src/getpos.c", "src/glyphs.c", "src/hack.c", "src/hacklib.c", "src/iactions.c",
        "src/insight.c", "src/invent.c", "src/isaac64.c", "src/light.c", "src/lock.c",
        "src/mail.c", "src/makemon.c", "src/mcastu.c", "src/mdlib.c", "src/mhitm.c",
        "src/mhitu.c", "src/minion.c", "src/mklev.c", "src/mkmap.c", "src/mkmaze.c",
        "src/mkobj.c", "src/mkroom.c", "src/mon.c", "src/mondata.c", "src/monmove.c",
        "src/monst.c", "src/mplayer.c", "src/mthrowu.c", "src/muse.c", "src/music.c",
        "src/nhlua.c", "src/nhlsel.c", "src/nhlobj.c", "src/nhmd4.c", "src/objects.c",
        "src/o_init.c", "src/objnam.c", "src/options.c", "src/pager.c", "src/pickup.c",
        "src/pline.c", "src/polyself.c", "src/potion.c", "src/pray.c", "src/priest.c",
        "src/quest.c", "src/questpgr.c", "src/read.c", "src/rect.c", "src/region.c",
        "src/report.c", "src/restore.c", "src/revision.c", "src/rip.c", "src/rnd.c", "src/role.c",
        "src/rumors.c", "src/save.c", "src/selvar.c", "src/sfbase.c", "src/sfstruct.c", "src/shk.c",
        "src/shknam.c", "src/sit.c", "src/sounds.c", "src/sp_lev.c", "src/spell.c",
        "src/stairs.c", "src/steal.c", "src/steed.c", "src/strutil.c", "src/symbols.c", "src/sys.c",
        "src/teleport.c", "src/timeout.c", "src/topten.c", "src/track.c", "src/trap.c",
        "src/u_init.c", "src/uhitm.c", "src/utf8map.c", "src/vault.c", "src/version.c",
        "src/vision.c", "src/weapon.c", "src/were.c", "src/wield.c", "src/windows.c",
        "src/wizard.c", "src/wizcmds.c", "src/worm.c", "src/worn.c", "src/write.c",
        "src/zap.c"
    )
    $wasm_sys_src = @(
        "sys/libnh/libnhmain.c",
        "sys/share/ioctl.c",
        "sys/share/unixtty.c",
        "sys/share/pmatchregex.c",
        "sys/unix/unixunix.c",
        "sys/unix/unixres.c",
        "win/shim/winshim.c"
    )
    $all_src = $nethack_src + $wasm_sys_src
    $all_src | ForEach-Object { "`"$_`"" } | Out-File -FilePath nethack_files.rsp -Encoding ascii

    $emcc_flags = @(
        "-O2",
        "-Iinclude",
        "-Ilib/lua-5.4.8/src",
        "-DCROSSCOMPILE",
        "-DCROSSCOMPILE_TARGET",
        "-DCROSS_TO_WASM",
        "-DNOTTYGRAPHICS",
        "-DSHIM_GRAPHICS",
        "-DLIBNH",
        "-DNOMAIL",
        "-DNO_SIGNAL",
        "-sASYNCIFY=1",
        "-sASYNCIFY_IMPORTS=['local_callback']",
        "-sEXPORTED_FUNCTIONS=['_main','_shim_graphics_set_callback','_repopulate_perminvent','_malloc']",
        "-sEXPORTED_RUNTIME_METHODS=['cwrap','ccall','addFunction','UTF8ToString','stringToUTF8','getValue','setValue','FS','IDBFS']",
        "-lidbfs.js",
        "-sALLOW_TABLE_GROWTH=1",
        "-sALLOW_MEMORY_GROWTH=1",
        "-sERROR_ON_UNDEFINED_SYMBOLS=0"
    )
    $emcc_flags | Out-File -FilePath nethack_flags.rsp -Encoding ascii

    # Step 6: Final Link with embedded files
    Write-Host "--- Step 6: Linking and Packaging ---"
    emcc "@nethack_files.rsp" "liblua.a" "@nethack_flags.rsp" -o nethack.js --embed-file dat@/

    # Step 7: Copy build outputs to WebUI root
    Write-Host "--- Step 7: Deploying build outputs ---"
    Copy-Item "nethack.js" "$DEPLOY_ROOT/nethack.js" -Force
    Copy-Item "nethack.wasm" "$DEPLOY_ROOT/nethack.wasm" -Force
    if (Test-Path "util/tilemappings.lst") {
        Copy-Item "util/tilemappings.lst" "$DEPLOY_ROOT/docs/5_gamedata/tilemappings.lst" -Force
    }
    elseif (Test-Path "tilemappings.lst") {
        Copy-Item "tilemappings.lst" "$DEPLOY_ROOT/docs/5_gamedata/tilemappings.lst" -Force
    }

    Write-Host "Build Complete!"
}
finally {
    Pop-Location
}
