/**
 * defaultDefines.js - 入力・操作用デフォルト定義定数モジュール
 *
 * 旧 param/rogueDefines.js から KEYMAP, GPAD_DEFAULT, TOUCH_DEFAULT 定数を抽出・ESモジュール化。
 * ブラウザの window.rogueDefines グローバル依存を無くし、純粋なインポート可能定数として提供する。
 */

export const KEYMAP = {
    'ArrowUp': ['8'.charCodeAt(0), '8'.charCodeAt(0), null],
    'ArrowDown': ['2'.charCodeAt(0), '2'.charCodeAt(0), null],
    'ArrowLeft': ['4'.charCodeAt(0), '4'.charCodeAt(0), null],
    'ArrowRight': ['6'.charCodeAt(0), '6'.charCodeAt(0), null],
    'Enter': [13, 13, 13],
    'Escape': [27, 27, 27],
    'End': [27, 27, 27],
    'Space': [32, 32, 32],
    'Delete': [27, 27, 27],
    'Backspace': [8, 8, 8],
    'KeyA': ["a".charCodeAt(0), "A".charCodeAt(0), 1],
    'KeyB': ["b".charCodeAt(0), "B".charCodeAt(0), 2],
    'KeyC': ["c".charCodeAt(0), "C".charCodeAt(0), 3],
    'KeyD': ["d".charCodeAt(0), "D".charCodeAt(0), 4],
    'KeyE': ["e".charCodeAt(0), "E".charCodeAt(0), 5],
    'KeyF': ["f".charCodeAt(0), "F".charCodeAt(0), 6],
    'KeyG': ["g".charCodeAt(0), "G".charCodeAt(0), 7],
    'KeyH': ["h".charCodeAt(0), "H".charCodeAt(0), 8],
    'KeyI': ["i".charCodeAt(0), "I".charCodeAt(0), 9],
    'KeyJ': ["j".charCodeAt(0), "J".charCodeAt(0), 10],
    'KeyK': ["k".charCodeAt(0), "K".charCodeAt(0), 11],
    'KeyL': ["l".charCodeAt(0), "L".charCodeAt(0), 12],
    'KeyM': ["m".charCodeAt(0), "M".charCodeAt(0), 13],
    'KeyN': ["n".charCodeAt(0), "N".charCodeAt(0), 14],
    'KeyO': ["o".charCodeAt(0), "O".charCodeAt(0), 15],
    'KeyP': ["p".charCodeAt(0), "P".charCodeAt(0), 16],
    'KeyQ': ["q".charCodeAt(0), "Q".charCodeAt(0), 17],
    'KeyR': ["r".charCodeAt(0), "R".charCodeAt(0), 18],
    'KeyS': ["s".charCodeAt(0), "S".charCodeAt(0), 19],
    'KeyT': ["t".charCodeAt(0), "T".charCodeAt(0), 20],
    'KeyU': ["u".charCodeAt(0), "U".charCodeAt(0), 21],
    'KeyV': ["v".charCodeAt(0), "V".charCodeAt(0), 22],
    'KeyW': ["w".charCodeAt(0), "W".charCodeAt(0), 23],
    'KeyX': ["x".charCodeAt(0), "X".charCodeAt(0), 24],
    'KeyY': ["y".charCodeAt(0), "Y".charCodeAt(0), 25],
    'KeyZ': ["z".charCodeAt(0), "Z".charCodeAt(0), 26],
    'Digit0': ["0".charCodeAt(0), "0".charCodeAt(0), null],
    'Digit1': ["1".charCodeAt(0), "!".charCodeAt(0), null],
    'Digit2': ["2".charCodeAt(0), '"'.charCodeAt(0), null],
    'Digit3': ["3".charCodeAt(0), "#".charCodeAt(0), null],
    'Digit4': ["4".charCodeAt(0), "$".charCodeAt(0), null],
    'Digit5': ["5".charCodeAt(0), "%".charCodeAt(0), null],
    'Digit6': ["6".charCodeAt(0), "&".charCodeAt(0), null],
    'Digit7': ["7".charCodeAt(0), "'".charCodeAt(0), null],
    'Digit8': ["8".charCodeAt(0), "(".charCodeAt(0), null],
    'Digit9': ["9".charCodeAt(0), ")".charCodeAt(0), null],
    'Numpad0': ["0".charCodeAt(0), "0".charCodeAt(0), null],
    'Numpad1': ["1".charCodeAt(0), "1".charCodeAt(0), null],
    'Numpad2': ["2".charCodeAt(0), "2".charCodeAt(0), null],
    'Numpad3': ["3".charCodeAt(0), "3".charCodeAt(0), null],
    'Numpad4': ["4".charCodeAt(0), "4".charCodeAt(0), null],
    'Numpad5': ["5".charCodeAt(0), "5".charCodeAt(0), null],
    'Numpad6': ["6".charCodeAt(0), "6".charCodeAt(0), null],
    'Numpad7': ["7".charCodeAt(0), "7".charCodeAt(0), null],
    'Numpad8': ["8".charCodeAt(0), "8".charCodeAt(0), null],
    'Numpad9': ["9".charCodeAt(0), "9".charCodeAt(0), null],
    'NumpadEnter': [13, 13, 13],
    'NumpadDecimal': [".".charCodeAt(0), ".".charCodeAt(0), null],
    'NumpadAdd': ["+".charCodeAt(0), "+".charCodeAt(0), null],
    'NumpadSubtract': ["-".charCodeAt(0), "-".charCodeAt(0), null],
    'NumpadDevide': ["/".charCodeAt(0), "/".charCodeAt(0), null],
    'NumpadMultiply': ["*".charCodeAt(0), "*".charCodeAt(0), null],
    'Period': [".".charCodeAt(0), ">".charCodeAt(0), null],
    'Comma': [",".charCodeAt(0), "<".charCodeAt(0), null],
    'Minus': ["-".charCodeAt(0), "=".charCodeAt(0), null],
    'BracketLeft': ["@".charCodeAt(0), "`".charCodeAt(0), null],
    'BracketRight': ["[".charCodeAt(0), "{".charCodeAt(0), null],
    'Quote': [":".charCodeAt(0), "*".charCodeAt(0), null],
    'Slash': ["/".charCodeAt(0), "?".charCodeAt(0), null],
    'Semicolon': [";".charCodeAt(0), "+".charCodeAt(0), null],
    'IntlRo': ["\\".charCodeAt(0), "_".charCodeAt(0), null],
    'Backslash': ["]".charCodeAt(0), "}".charCodeAt(0), null],
    'Equal': ["^".charCodeAt(0), "~".charCodeAt(0), null],
    'IntlYen': ["\\".charCodeAt(0), "|".charCodeAt(0), null],
};

export const GPAD_DEFAULT = {
    NORMAL: {
        P1: { label: " 1", key: ["Numpad1"] },
        P2: { label: " 2", key: ["Numpad2"] },
        P3: { label: " 3", key: ["Numpad3"] },
        P4: { label: " 4", key: ["Numpad4"] },
        P6: { label: " 6", key: ["Numpad6"] },
        P7: { label: " 7", key: ["Numpad7"] },
        P8: { label: " 8", key: ["Numpad8"] },
        P9: { label: " 9", key: ["Numpad9"] },
        START: { label: " # ", key: ["Digit3", "ShiftLeft"] },
        BACK: { label: "Save", key: ["KeyS", "ShiftLeft"] },
        A: { label: "Trav", key: ["Numpad5"] },
        B: { label: "ESC", key: ["Delete"] },
        X: { label: "Ent", key: ["Enter"] },
        Y: { label: " i ", key: ["KeyI"] },
        L3: { label: " : ", key: ["Quote"] },
        R3: { label: " s ", key: ["KeyS"] },
    },
    RT: {
        A: { label: "w)ld", key: ["KeyW"] },
        B: { label: "W)ear", key: ["KeyW", "ShiftLeft"] },
        X: { label: "T)off", key: ["KeyT", "ShiftLeft"] },
        Y: { label: "z)ap", key: ["KeyZ"] },
    },
    LT: {
        P2: { label: " 2", key: ["Numpad2"] },
        P4: { label: " 4", key: ["Numpad4"] },
        P6: { label: " 6", key: ["Numpad6"] },
        P8: { label: " 8", key: ["Numpad8"] },
        A: { label: "q)uf", key: ["KeyQ"] },
        B: { label: "r)ead", key: ["KeyR"] },
        X: { label: "e)at", key: ["KeyE"] },
        Y: { label: "t)hw", key: ["KeyT"] },
    },
    RB: {
        A: { label: " . ", key: ["Period"] },
        B: { label: "<)Up", key: ["Comma", "ShiftLeft"] },
        X: { label: ">)Dn", key: ["Period", "ShiftLeft"] },
        Y: { label: ",)get", key: ["Comma"] },
    },
    LB: {
        P2: { label: " 2", key: ["Numpad2"] },
        P4: { label: " 4", key: ["Numpad4"] },
        P6: { label: " 6", key: ["Numpad6"] },
        P8: { label: " 8", key: ["Numpad8"] },
        A: { label: "Z)ap", key: ["KeyZ", "ShiftLeft"] },
        B: { label: "a)ply", key: ["KeyA"] },
        X: { label: "k)ik", key: ["KeyK"] },
        Y: { label: "Pray", key: ["Digit3", "ShiftLeft"] },
    },
    LB_LT: {
        A: { label: " y ", key: ["KeyY"] },
        B: { label: " n ", key: ["KeyN"] },
        X: { label: " a ", key: ["KeyA"] },
        Y: { label: " q ", key: ["KeyQ"] },
        P4: { label: " l ", key: ["KeyL"] },
        P6: { label: " r ", key: ["KeyR"] },
    },
    RB_RT: {
        A: { label: " a ", key: ["KeyA"] },
        B: { label: " d ", key: ["KeyD"] },
        X: { label: " @ ", key: ["BracketLeft"] },
        Y: { label: " / ", key: ["Slash"] },
        START: { label: " * ", key: ["Quote", "ShiftLeft"] },
        BACK: { label: " # ", key: ["Digit3", "ShiftLeft"] },
    },
    LB_RB: {},
    LT_RT: {},
    LB_RT: {},
    LT_RB: {},
};

export const TOUCH_DEFAULT = {
    ver: "12x9",
    Center: {
        0: { label: "7", action: ["Numpad7"] }, 1: { label: "8", action: ["Numpad8"] }, 2: { label: "9", action: ["Numpad9"] },
        12: { label: "4", action: ["Numpad4"] }, 13: { label: "Trav", action: ["Numpad5"] }, 14: { label: "6", action: ["Numpad6"] },
        24: { label: "1", action: ["Numpad1"] }, 25: { label: "2", action: ["Numpad2"] }, 26: { label: "3", action: ["Numpad3"] },
        36: { label: "[-L-]", action: 2 }, 37: { label: "Ent", action: ["Enter"] }, 38: { label: "ESC", action: ["Delete"] },

        9: { label: "q)uf", action: ["KeyQ"] }, 10: { label: "r)ed", action: ["KeyR"] }, 11: { label: "e)at", action: ["KeyE"] },
        21: { label: "w)ld", action: ["KeyW"] }, 22: { label: "W)ear", action: ["KeyW", "ShiftLeft"] }, 23: { label: "T)off", action: ["KeyT", "ShiftLeft"] },
        33: { label: "k)ik", action: ["KeyK"] }, 34: { label: "a)ply", action: ["KeyA"] }, 35: { label: "z)ap", action: ["KeyZ"] },
        45: { label: ". wait", action: ["Period"] }, 46: { label: "i)nv", action: ["KeyI"] }, 47: { label: "s)rh", action: ["KeyS"] },
        57: { label: ">)Dn", action: ["Period", "ShiftLeft"] }, 58: { label: "<)Up", action: ["Comma", "ShiftLeft"] }, 59: { label: ",)get", action: ["Comma"] },
        69: { label: "o)pn", action: ["KeyO"] }, 70: { label: "c)ls", action: ["KeyC"] }, 71: { label: "# ext", action: ["Digit3", "ShiftLeft"] },
        81: { label: "[-L-]", action: 2 }, 82: { label: "[-R-]", action: 3 }, 83: { label: "ENTER", action: ["Enter"] }
    },
    Left: {
        0: { label: "7", action: ["Numpad7"] }, 1: { label: "8", action: ["Numpad8"] }, 2: { label: "9", action: ["Numpad9"] },
        12: { label: "4", action: ["Numpad4"] }, 13: { label: "Trav", action: ["Numpad5"] }, 14: { label: "6", action: ["Numpad6"] },
        24: { label: "1", action: ["Numpad1"] }, 25: { label: "2", action: ["Numpad2"] }, 26: { label: "3", action: ["Numpad3"] },
        36: { label: "[-N-]", action: 1 }, 37: { label: "Enter", action: ["Enter"] }, 38: { label: "ESC", action: ["Delete"] },

        9: { label: "P)on", action: ["KeyP", "ShiftLeft"] }, 10: { label: "R)mov", action: ["KeyR", "ShiftLeft"] }, 11: { label: "a)ply", action: ["KeyA"] },
        21: { label: "k)ik", action: ["KeyK"] }, 22: { label: "o)pn", action: ["KeyO"] }, 23: { label: "c)ls", action: ["KeyC"] },
        33: { label: "# pray", action: ["Digit3", "ShiftLeft"] }, 34: { label: "Z)ap", action: ["KeyZ", "ShiftLeft"] }, 35: { label: "f)ire", action: ["KeyF"] },
        45: { label: "l)ook", action: ["KeyL"] }, 46: { label: "v)rs", action: ["KeyV", "ShiftLeft"] }, 47: { label: "[-R-]", action: 3 },
        81: { label: "[-N-]", action: 1 }, 82: { label: "[-R-]", action: 3 }, 83: { label: "ENTER", action: ["Enter"] }
    },
    Right: {
        0: { label: "7", action: ["Numpad7"] }, 1: { label: "8", action: ["Numpad8"] }, 2: { label: "9", action: ["Numpad9"] },
        12: { label: "4", action: ["Numpad4"] }, 13: { label: "Trav", action: ["Numpad5"] }, 14: { label: "6", action: ["Numpad6"] },
        24: { label: "1", action: ["Numpad1"] }, 25: { label: "2", action: ["Numpad2"] }, 26: { label: "3", action: ["Numpad3"] },
        36: { label: "[-L-]", action: 2 }, 37: { label: "Enter", action: ["Enter"] }, 38: { label: "ESC", action: ["Delete"] },

        9: { label: "y es", action: ["KeyY"] }, 10: { label: "n o", action: ["KeyN"] }, 11: { label: "a ll", action: ["KeyA"] },
        21: { label: "q uit", action: ["KeyQ"] }, 22: { label: "S)ave", action: ["KeyS", "ShiftLeft"] }, 23: { label: "Enter", action: ["Enter"] },
        33: { label: "Space", action: ["Space"] }, 34: { label: "Bksp", action: ["Backspace"] }, 35: { label: "Tab", action: ["Tab"] },
        45: { label: "# ext", action: ["Digit3", "ShiftLeft"] }, 46: { label: "ESC", action: ["Delete"] }, 47: { label: "[-N-]", action: 1 },
        81: { label: "[-L-]", action: 2 }, 82: { label: "[-N-]", action: 1 }, 83: { label: "ENTER", action: ["Enter"] }
    },
    YN: {
        0: { label: "7", action: ["Numpad7"] }, 1: { label: "8", action: ["Numpad8"] }, 2: { label: "9", action: ["Numpad9"] },
        12: { label: "4", action: ["Numpad4"] }, 13: { label: "5", action: ["Numpad5"] }, 14: { label: "6", action: ["Numpad6"] },
        24: { label: "1", action: ["Numpad1"] }, 25: { label: "2", action: ["Numpad2"] }, 26: { label: "3", action: ["Numpad3"] },
        36: { label: "[-L-]", action: 2 }, 37: { label: "[-N-]", action: 1 }, 38: { label: "[-R-]", action: 3 },
        9: { label: "y", action: ["KeyY"] }, 10: { label: "n", action: ["KeyN"] }, 11: { label: "a", action: ["KeyA"] },
        21: { label: "q", action: ["KeyQ"] }, 22: { label: "l", action: ["KeyL"] }, 23: { label: "r", action: ["KeyR"] },
        33: { label: "*", action: ["Quote", "ShiftLeft"] }, 34: { label: "/", action: ["Slash"] }, 35: { label: "ESC", action: ["Delete"] },
        81: { label: "[-L-]", action: 2 }, 82: { label: "[-N-]", action: 1 }, 83: { label: "[-R-]", action: 3 }
    },
    MENU: {
        0: { label: "7", action: ["Numpad7"] }, 1: { label: "8", action: ["Numpad8"] }, 2: { label: "9", action: ["Numpad9"] },
        12: { label: "4", action: ["Numpad4"] }, 13: { label: "5", action: ["Numpad5"] }, 14: { label: "6", action: ["Numpad6"] },
        24: { label: "1", action: ["Numpad1"] }, 25: { label: "2", action: ["Numpad2"] }, 26: { label: "3", action: ["Numpad3"] },
        36: { label: "[-L-]", action: 2 }, 37: { label: "[-N-]", action: 1 }, 38: { label: "[-R-]", action: 3 },
        9: { label: "Space", action: ["Space"] }, 10: { label: "Enter", action: ["Enter"] }, 11: { label: "ESC", action: ["Delete"] },
        21: { label: "a", action: ["KeyA"] }, 22: { label: "d", action: ["KeyD"] }, 23: { label: "q", action: ["KeyQ"] },
        33: { label: "*", action: ["Quote", "ShiftLeft"] }, 34: { label: "/", action: ["Slash"] },
        81: { label: "[-L-]", action: 2 }, 82: { label: "[-N-]", action: 1 }, 83: { label: "[-R-]", action: 3 }
    },
    LIN: {
        0: { label: "7", action: ["Numpad7"] }, 1: { label: "8", action: ["Numpad8"] }, 2: { label: "9", action: ["Numpad9"] },
        12: { label: "4", action: ["Numpad4"] }, 13: { label: "5", action: ["Numpad5"] }, 14: { label: "6", action: ["Numpad6"] },
        24: { label: "1", action: ["Numpad1"] }, 25: { label: "2", action: ["Numpad2"] }, 26: { label: "3", action: ["Numpad3"] },
        9: { label: "Bksp", action: ["Backspace"] }, 10: { label: "Enter", action: ["Enter"] }, 11: { label: "ESC", action: ["Delete"] },
        81: { label: "[-L-]", action: 2 }, 82: { label: "[-N-]", action: 1 }, 83: { label: "[-R-]", action: 3 }
    }
};
