const fs = require('fs');
const path = require('path');

const WORKSPACE = path.join(__dirname, '..');
const LST_PATH = path.join(WORKSPACE, 'docs', 'tilemappings.lst');
const ITEM_LIST_PATH = path.join(WORKSPACE, 'docs', 'item_list.ja.md');
const OUT_JS_PATH = path.join(WORKSPACE, 'param', 'tileMapping.js');
const OUT_CSV_PATH = path.join(WORKSPACE, 'tools', 'tile_reorder_map.csv');

function main() {
    console.log('--- Re-analyzing Tile Mappings ---');

    if (!fs.existsSync(LST_PATH)) {
        console.error(`Error: tilemappings.lst not found at ${LST_PATH}`);
        process.exit(1);
    }

    // 1. Parse tilemappings.lst (5.0.0 mappings)
    const lstContent = fs.readFileSync(LST_PATH, 'utf-8');
    const lines = lstContent.split('\n');

    const glyphToTile = {};
    const tile50Names = {}; // tile50_index -> Name representation

    // Parse offsets and config from lst header
    const offsets = {};
    const pmRegex = /^(\w+)\s*=\s*(\d+)/;
    const glyphRegex = /^glyph\[(\d+)\]\s*\[(\d+)\]\s*(.*)/;

    lines.forEach(line => {
        let m;
        if ((m = line.match(pmRegex))) {
            offsets[m[1]] = parseInt(m[2], 10);
        } else if ((m = line.match(glyphRegex))) {
            const glyph = parseInt(m[1], 10);
            const tile = parseInt(m[2], 10);
            const desc = m[3].trim();
            glyphToTile[glyph] = tile;

            // Track names mapped to 5.0.0 tiles
            // Strip structural info for matching
            let cleanDesc = desc
                .replace(/\(mnum=\d+\)/, '')
                .replace(/\(onum=\d+\)/, '')
                .replace(/\{.*\}/, '')
                .replace(/^(male|female|detected|ridden|pet|body of|piletop body of|piletop)\s+/, '')
                .trim();

            if (!tile50Names[tile]) {
                tile50Names[tile] = [];
            }
            if (!tile50Names[tile].includes(cleanDesc)) {
                tile50Names[tile].push(cleanDesc);
            }
        }
    });

    console.log(`Parsed ${Object.keys(glyphToTile).length} glyphs from 5.0.0 tilemappings.lst`);

    // 2. Generate param/tileMapping.js (Direct 1:1 Mapping Object)
    let jsContent = `/**
 * tileMapping (Generated)
 * NetHack 5.0.0 Glyph ID to 5.0.0 Tile Index 1:1 Mapping Table
 * 
 * @description
 * This file is automatically generated by tools/generate_mapping.js.
 * It provides a direct 1:1 lookup table mapping Wasm Glyph ID to 5.0.0 Tile Index,
 * eliminating all runtime calculation errors.
 */
function tileMapping(offsets) {
    const m = {
`;

    Object.keys(glyphToTile).sort((a,b) => a-b).forEach(glyph => {
        jsContent += `        ${glyph}: ${glyphToTile[glyph]},\n`;
    });

    jsContent += `    };
    return m;
}
`;
    fs.writeFileSync(OUT_JS_PATH, jsContent, 'utf-8');
    console.log(`Successfully generated direct mapping table: ${OUT_JS_PATH}`);

    // 3. Reconstruct 3.7.0 Names & Mappings to build Rearrange CSV
    // Parse 3.7.0 items from docs/item_list.ja.md
    if (!fs.existsSync(ITEM_LIST_PATH)) {
        console.warn(`Warning: item_list.ja.md not found at ${ITEM_LIST_PATH}. Skipping CSV generation.`);
        return;
    }

    const mdContent = fs.readFileSync(ITEM_LIST_PATH, 'utf-8');
    const mdLines = mdContent.split('\n');

    const items37 = [
        'strange object',
        'generic strange',
        'generic weapon',
        'generic armor',
        'generic ring',
        'generic amulet',
        'generic tool',
        'generic food',
        'generic potion',
        'generic scroll',
        'generic spellbook',
        'generic wand',
        'generic coin',
        'generic gem',
        'generic large rock',
        'generic iron ball',
        'generic iron chain',
        'generic venom'
    ];

    mdLines.forEach(line => {
        const m = line.match(/^-\s+([^\/]+)\s*\//);
        if (m) {
            const name = m[1].trim();
            // Avoid duplicates
            if (!items37.includes(name)) {
                items37.push(name);
            }
        }
    });

    console.log(`Parsed ${items37.length} items from 3.7.0 item_list.ja.md`);

    // Reconstruct 3.7.0 Tile Indexes
    const tile37Names = {};

    // 3.7.0 Monsters (from 5.0.0 list, since order and names are identical)
    let tile37 = 0;
    const monConds = [26, 31, 135, 145, 178, 227, 286, 346, 346, 359, 371];
    
    // We fetch monster names from 5.0.0 tilemappings list (mnum=0 to 382)
    // 3.7.0 monster definitions are 381 (or similar)
    const numMons = offsets.NUMMONS || 383;
    for (let i = 0; i < numMons; i++) {
        // Find name of monster i from 5.0.0
        const mLines = lines.filter(l => l.includes(`(mnum=${i})`) && l.startsWith('glyph['));
        let monName = `monster_${i}`;
        if (mLines.length > 0) {
            const match = mLines[0].match(/male\s+(.*)\s+\(mnum=/);
            if (match) monName = match[1].trim();
        }

        tile37Names[tile37] = `monster: ${monName}`;
        tile37++;

        // Shift for conditionals
        monConds.forEach(pred => {
            if (pred === i) {
                // Skips 1 tile for conditionals (Cerberus, beholder, etc.)
                let condName = 'conditional_monster';
                if (i === 26) condName = 'Cerberus';
                else if (i === 31) condName = 'beholder';
                else if (i === 135) condName = 'baby shimmering dragon';
                else if (i === 145) condName = 'shimmering dragon';
                else if (i === 178) condName = 'vorpal jabberwock';
                else if (i === 227) condName = 'vampire mage';
                else if (i === 286) condName = 'Charon';
                else if (i === 346 && tile37Names[tile37-2] !== 'Earendil') condName = 'Earendil';
                else if (i === 346) condName = 'Elwing';
                else if (i === 359) condName = 'Goblin King';
                else if (i === 371) condName = 'High-elf';

                tile37Names[tile37] = `monster_cond: ${condName}`;
                tile37++;
            }
        });
    }

    // 3.7.0 Invisible Monster
    tile37Names[tile37] = 'invisible monster';
    tile37++;

    // 3.7.0 Objects
    const objConds = [66, 68, 77];
    const objCondsDel = [268, 269, 270, 271, 272, 273];

    for (let i = 0; i < items37.length; i++) {
        tile37Names[tile37] = `object: ${items37[i]}`;
        
        // Handle object conditionals
        objCondsDel.forEach(pred => {
            if (pred === i) tile37--;
        });
        objConds.forEach(pred => {
            if (pred === i) {
                let condName = 'conditional_object';
                if (i === 66) condName = 'shimmering dragon scale mail'; // Check actual indexes
                tile37Names[tile37 + 1] = `object_cond: ${condName}`;
                tile37++;
            }
        });
        tile37++;
    }

    // 4. Match 3.7.0 Tiles with 5.0.0 Tiles to create Reorder CSV
    const csvLines = ['"3.7.0_Index","5.0.0_Index","Name_3.7.0","Name_5.0.0"'];

    // Map monster categories
    for (let t37 = 0; t37 < 393; t37++) {
        const name37 = tile37Names[t37] || '';
        let cleanName37 = name37.replace(/^(monster|monster_cond):\s+/, '');

        // Find match in 5.0.0
        let matchedTile50 = '';
        let matchedName50 = '';
        for (const [t50, names] of Object.entries(tile50Names)) {
            // Monsters are 0 to 788 in 5.0.0
            if (parseInt(t50, 10) >= 788) continue; 
            
            if (names.some(n => n.toLowerCase() === cleanName37.toLowerCase())) {
                matchedTile50 = t50;
                matchedName50 = names.join(' / ');
                break;
            }
        }

        // Special fallback matches for monsters
        if (!matchedTile50) {
            if (cleanName37 === 'invisible monster') {
                matchedTile50 = '788';
                matchedName50 = 'invisible monster';
            }
        }

        csvLines.push(`"${t37}","${matchedTile50}","${name37}","${matchedName50}"`);
    }

    // Map objects
    const start37Obj = 393;
    const max37Obj = start37Obj + items37.length;
    for (let t37 = start37Obj; t37 < max37Obj; t37++) {
        const name37 = tile37Names[t37] || '';
        let cleanName37 = name37.replace(/^(object|object_cond):\s+/, '').toLowerCase();

        let matchedTile50 = '';
        let matchedName50 = '';
        for (const [t50, names] of Object.entries(tile50Names)) {
            const t50Int = parseInt(t50, 10);
            if (t50Int < 789 || t50Int >= 1272) continue; // Objects are 789-1271 in 5.0.0

            if (names.some(n => n.toLowerCase() === cleanName37 || n.toLowerCase().includes(cleanName37) || cleanName37.includes(n.toLowerCase()))) {
                matchedTile50 = t50;
                matchedName50 = names.join(' / ');
                break;
            }
        }

        csvLines.push(`"${t37}","${matchedTile50}","${name37}","${matchedName50}"`);
    }

    // Map CMAP (Dungeon parts)
    // 3.7.0 CMAP starts at 847. 5.0.0 CMAP starts at 1272.
    // They are mostly identical in sequence, with minor offsets.
    const cmapMatches = [
        { t37: 847, t50: 1272, name: 'S_stone / Stone substrate' },
        // Walls (11 types)
        { t37: 851, t50: 1273, name: 'Main wall vertical' },
        { t37: 862, t50: 1284, name: 'Doorway' },
        { t37: 863, t50: 1285, name: 'Vertical open door' },
        { t37: 864, t50: 1286, name: 'Horizontal open door' },
        { t37: 865, t50: 1287, name: 'Vertical closed door' },
        { t37: 866, t50: 1288, name: 'Horizontal closed door' },
        { t37: 867, t50: 1289, name: 'Iron bars' },
        { t37: 868, t50: 1290, name: 'Tree' },
        { t37: 869, t50: 1291, name: 'Room' },
        { t37: 870, t50: 1292, name: 'Dark room' },
        { t37: 871, t50: 1293, name: 'Corridor' },
        { t37: 872, t50: 1294, name: 'Lit corridor' },
        { t37: 873, t50: 1295, name: 'Stairs up' },
        { t37: 874, t50: 1296, name: 'Stairs down' },
        { t37: 875, t50: 1297, name: 'Ladder up' },
        { t37: 876, t50: 1298, name: 'Ladder down' },
        { t37: 877, t50: 1299, name: 'Altar' },
        { t37: 878, t50: 1304, name: 'Grave' },
        { t37: 879, t50: 1305, name: 'Throne' },
        { t37: 880, t50: 1306, name: 'Sink' },
        { t37: 881, t50: 1307, name: 'Fountain' },
        { t37: 882, t50: 1308, name: 'Water' },
        { t37: 883, t50: 1309, name: 'Ice' },
        { t37: 884, t50: 1310, name: 'Lava' },
        { t37: 885, t50: 1312, name: 'Drawbridge vertical' },
        { t37: 886, t50: 1313, name: 'Drawbridge horizontal' },
        { t37: 889, t50: 1316, name: 'Air' },
        { t37: 890, t50: 1317, name: 'Cloud' },
        { t37: 891, t50: 1318, name: 'Underwater' },
        { t37: 892, t50: 1319, name: 'Arrow trap' }
        // ... (This list provides key anchor points for rearrangement)
    ];

    cmapMatches.forEach(m => {
        csvLines.push(`"${m.t37}","${m.t50}","cmap: ${m.name}","cmap: ${m.name}"`);
    });

    fs.writeFileSync(OUT_CSV_PATH, csvLines.join('\n'), 'utf-8');
    console.log(`Successfully generated tile reorder map: ${OUT_CSV_PATH}`);
}

main();
