function nhMessage_org() {
    return [
        "Shall I pick character's race, role, gender and alignment for you? [ynaq]",

        "    After the Creation, the cruel god Moloch rebelled",
        "    against the authority of Marduk the Creator.",
        "    Moloch stole from Marduk the most powerful of all",
        "    the artifacts of the gods, the Amulet of Yendor,",
        "    and he hid it in the dark cavities of Gehennom, the",
        "    Under World, where he now lurks, and bides his time.",

        "Beware, there will be no return!  Still climb?",
        "Do you want your possessions identified?",
        "Do you want to see your attributes?",
        "Do you want an account of creatures vanquished?",
        "Do you want to see your conduct?",
        "Do you want to see the dungeon overview?",

        "Entering the tutorial.",
        "Something is engraved here on the floor.",
        "Move around with 4 2 8 6",
        "Move diagonally with 1 9 3 7",
        "Some actions may require multiple tries before succeeding",
        "Open the door by moving into it",
        "Close the door with 'c'",
        "Note: Outside the tutorial, Ctrl-key combinations are shown prefixed with a caret, like '^D'",
        "This door is locked. Kick it with 'k'",
        "(Tip: use 'm' prefix to step in if you really want to.)",
        "Look around the map with ';', press ESC when you're done",
        "Use 's' to search for secret doors",
        "Behind this door is a dark corridor",
        "There are four traps next to you! Search for them.",
        "Some traps can be disabled with 'u'",
        "Pick up items with ','",
        "Wear armor with 'W'",
        "Wield weapons with 'w'",
        "Hit monsters by walking into them.",
        "Now you know the very basics. You can leave the tutorial via the magic portal.",
        "Step into this portal to leave the tutorial",
        "Push boulders by moving into them",
        "Take off armor with 'T'",
        "Some items have shuffled descriptions, different each game",
        "Pick up this scroll, read it with 'r', and try to remove the armor again",
        "Avoid being burdened, it slows you down",
        "Drop items with 'd'",
        "You can drop partial stacks by prefixing the item slot letter with a number",
        "Throw items with 't'",
        "Missiles, such as rocks, work better when fired from appropriate launcher",
        "Wield the sling",
        "Use 'f' to fire missiles with the wielded launcher",
        "You can wait a turn with '.'",
        "Firing launches items from your quiver; Use 'Q' to put items in it",
        "You loot containers with 'l'",
        "Containers can also be emptied with 'Alt-T'",
        "Magic wands are used with 'z'",
        "Another magic portal, a way to leave this tutorial",
        "Resuming regular play.",

        "It's a wall.",
        "The door opens.",
        "This door is locked.",
        "In what direction?",
        "As you kick the door, it crashes open!",
        "There is a broken door here.",
        "You find a hidden door.",
        "The door resists!",
        "It's solid stone.",
        "What a strange direction!",
        "Thwack!!",
        "Whammm!!",
        "Clonk!",
        "Really step onto that squeaky board?",
        "Really step into that magic portal?",
        "You activated a magic portal!",
        "Resetting time to move #1.",
        "There is a staircase up out of the dungeon here.",
        "There is a staircase down here.",
        "You descend the stairs.",
        "You climb up the stairs.",

        "A cloud of gas puts you to sleep!",
        "You wake up.",
        "You stumble into a spider web!",
        "You disentangle yourself.",
        "With great effort you move the boulder.",
        "You try to move the boulder, but in vain.",
        "However, you can squeeze yourself into a small opening.",
        "You see here a boulder.",
        "You cannot pass through the bars.",
        "It's a tree.",

        "You don't have that object.",
        "Never mind.",

        "You fall into the pool of water!",
        "You sink like a rock.",
        "You try to crawl out of the water.",
        "Pheew!  That was close.",
        "You plunge into the wall of water!",

        "Really step onto that sleeping gas trap?",
        "You are stuck to the web.",
        "Really step into that web?",
        "You escape a web.",

        "Things that are here:",
        "Ouch!  That hurts!",
        "Your right leg is in no shape for kicking.",
        "Your leg feels better.",
        "Some text has been burned into the floor here.",
        "You don't have anything to eat.",
        "Autopickup: ON, for all objects.",
        "Core dumped.",
        "Something is engraved here on the ground.",
        "You can run by prefixing a movement key with '5'",
        "Travel across the level with '_'",
        "Where do you want to travel to?",
        "(For instructions type a '?')",
        "Move cursor to the desired destination:",
        "floor of a room",
        "wall (no travel path)",
        "closed door",
        "unexplored area (no travel path)",
        "There is nothing here to pick up.",
        "You are already bare handed.",
        "Your hands are empty.",
        "Your left hand is empty.",
        "You are bare handed.",
        "You have no secondary weapon readied.",
        "You begin two-weapon combat.",
        "Autopickup: OFF.",
        "Which ring-finger, Right or Left?",
        "You start to float in the air!",
        "There is molten lava here.",
        "You are back over solid ground.",
        "You float gently to the floor.",
        "Not wearing any accessories or armor.",
        "You don't have anything to drink.",
        "UNDER CONSTRUCTION",
        "Spellcasting",
        "Unfortunately you don't have enough energy to cast spells.",
        "Pick up the spellbook with ','",
        "Can't get through?  You're carrying too much.",
        "A trap door opens up under you!",
        "There is a staircase up here.",
        "No count allowed with this command.",
        "There appears to be no shopkeeper here to receive your payment.",
        "Use '>' to go down the stairs",
        "You reveal a secret door!",
        "You begin to memorize the runes.",
        "You don't have enough energy to cast that spell yet.",
        "Hmmm, the chest turns out to be locked.",
        "You hear the footsteps of a guard on patrol.",
        "moat",
        "You kick at empty space.",
        "You hear someone counting gold coins.",
        "Double run prefix, canceled.",
        "Something is written here in the dust.",
        "You don't know any spells right now.",
        "You hear someone cursing shoplifters.",
        "You hear a door open.",
        "That door is closed.",
        "You learn more about your items by comparing them.",
        "Really save?",
        "Saving...",
        "Restoring save file...",

        "You fall into the molten lava!",
        "You burn to a crisp...",
        "The '5' prefix should be followed by a movement command.",
        "Program in disorder!  (Saving and reloading may fix this problem.)",
        "Please report these messages to devteam@nethack.org.",
        "Alternatively, contact local support: NetHack Wasm Port",
        "You detect the presence of objects.",
        "Move cursor to object:",

        "Hmmm, the large box turns out to be locked.",
        "You hear the splashing of a naiad.",

        "You get zapped!",
        "You hear a monster behind the boulder.",
        "Perhaps that's why you cannot move it.",

        "You hear distant howling.",
        "You are enveloped in a cloud of gas!",
        "That is a silly thing to put on.",
        "Really step into that hole?",
        "You escape a hole.",
        "There is a fountain here.",
        "Unlock it with your lock pick?",
        "You succeed in picking the lock.",
        "You hear crashing rock.",
        "You die...",

        "Dumb move!  You strain a muscle.",
        "There is a sink here.",
        "You hear a chugging sound.",
        "There's some graffiti on the floor here.",
        "You can't go down here.",
        "The wand hits you!",

        "You materialize in a different location!",
        "You hear some noises in the distance.",
        "You are momentarily blinded by a flash of light!",
        "You hear a deafening roar!",
        "Wait!  There's something there you can't see!",
        "You hear bubbling water.",
        "You are suddenly very hot!",
        "You hear some noises.",
        "There is a doorway here.",
        "You can see again.",
        "Really step onto that magic trap?",
        "You can hear again.",
        "It misses!",
        "It bites!",
        "You kill it!",

        "You faint from lack of food.",
        "You regain consciousness.",
        "You can move again.",
        "You don't have enough leverage to push the boulder.",
        "You cannot reach the floor.",
        "That is a silly thing to read.",
        "You can't reach the floor.",
        "You are not wearing any armor.",
        "Really float into that magic portal?",
        "Your movements are slowed slightly because of your load.",
        "Your movements are now unencumbered.",
        "As you read the scroll, it disappears.",

        "lamp is now on.",
        "You rebalance your load.  Movement is difficult.",
        "You find a hidden passage.",
        "You fall down the stairs.",
        "You are beginning to feel hungry.",
        "You finish your dressing maneuver.",
        "You hear water falling on coins.",
        "You are hit by a crude dagger.",
        "You are beginning to feel weak.",
        "You lash the orc zombie.",
        "This food really hits the spot!",
        "You stop eating the food ration.",

        "A trap door in the ceiling opens and a rock falls on your head!",
        "Really step onto that falling rock trap?",
        "Something is engraved here on the headstone.",
        "Could you please take a breath mint?",

        "Pick a monster, object or location.",
        "Move cursor to a monster, object or location:",
        "wall",
        "unexplored area",
        "dark part of a room",
        "engraving",
        "You avoid harm.",
        "As you kick the door, it shatters to pieces!",
        "You can't.  It is cursed.",
        "You don't have anything else to wear.",
        "You have no ammunition readied.",
        "Blecch!  Rotten food!",
        "stone (no travel path)",
        "corridor",
        "doorway",
        "broken door",
        "an effervescent",

        "stone",
        "lit corridor",
        "You feel threatened.",
        "You produce a strange whistling sound.",

        "You fall down a deep shaft!",
        "A shiver runs up and down your spine!",
        "You already found a monster.  Use 'm' prefix to force another search.",
        "You feel stealthy!",
        "purse feels lighter.",

        "You hear the chime of a cash register.",
        "You hear a gurgling noise.",
        "ANOINT, v.t.  To grease a king or other great functionary",
        "already sufficiently slippery.",
        "        [ The Devil's Dictionary, by Ambrose Bierce ]",
        "You are hit by an arrow.",
        "You feet are frozen to the floor!",

        "Really quit?",
        "You are not wearing an amulet.",
        "That is a silly thing to drink.",
        "Don't forget to stop and smell the roses",
        "You feel strong!",
        "You must have been exercising diligently.",
        "You feel tough!",
        "You must have been leading a healthy life-style.",
        "You are still weak.",

        "You stagger...",
        "You feel a bit steadier now.",
        "You have nothing to ready for firing.",
        "open door",

        "Is this a dagger which I see before me,",
        "The handle toward my hand? Come, let me clutch thee.",
        "I have thee not, and yet I see thee still.",
        "Art thou not, fatal vision, sensible",
        "To feeling as to sight? or art thou but",
        "A dagger of the mind, a false creation,",
        "Proceeding from the heat-oppressed brain?",
        "I see thee yet, in form as palpable",
        "As this which now I draw.",
        "        [ Macbeth, by William Shakespeare ]",

        "You smite the yellow mold.",
        "That ammunition is already readied!",
        "Confess my sins to god?  Which one?",
        "You feel better.",
        "Really step into that pit?",
        "You fall into a pit!",
        "There is a grave here.",
        "You stagger under your heavy load.  Movement is very hard.",
        "You don't have enough stamina to move.",
        "You hear scratching noises.",
        "You don't have anything else to put on.",
        "Ouch!  You bump into a door.",
        "Refresh your memory anyway?",

        "Loot in what direction?",
        "You don't find anything there to loot.",
        "A map coalesces in your mind!",
        "When the gods want to punish you, they answer your prayers.",
        "fountain",
        "grave",
        "You feel feverish.",     
                
        "You are already wearing some armor.",
        "Orcs, bipeds with a humanoid appearance, are related to the",
        "goblins, but much bigger and more dangerous.  The average",
        "is only moderately intelligent, has broad, muscled shoulders,",
        "a short neck, a sloping forehead and a thick, dark fur.",
        "Their lower eye-teeth are pointing forward, like a boar's.",
        "Female orcs are more lightly built and bare-chested.  Not",
        "needing any clothing, they do like to dress in variegated",
        "apparels.  Suspicious by nature, orcs live in tribes or",
        "hordes.  They tend to live underground as well as above",
        "ground (but they dislike sunlight).  Orcs can use all weapons,",
        "tools and armours that are used by men.  Since they don't have",
        "the talent to fashion these themselves, they are constantly",
        "hunting for them.  There is nothing a horde of orcs cannot",
        "use.",
        "        [ het Boek van de Regels; Het Oog des Meesters ]",

        "You finish taking off your mail.",
        "The door closes.",

        "If you start from scratch, cooking tripe is a long-drawn-out",
        "affair.  Fresh whole tripe calls for a minimum of 12 hours of",
        "cooking, some time-honored recipes demanding as much as 24.",
        "To prepare fresh tripe, trim if necessary.  Wash it thoroughly,",
        "soaking overnight, and blanch, for 1/2 hour in salted water.",
        "Wash well again, drain and cut for cooking.  When cooked, the",
        "texture of tripe should be like that of soft gristle.  More",
        "often, alas, because the heat has not been kept low enough,",
        "it has the consistency of wet shoe leather.",
        "        [ Joy of Cooking, by I Rombauer and M Becker ]",

        "A metal of characteristic yellow colour, the most precious",
        "metal used as a common commercial medium of exchange.  Symbol,",
        "Au; at. no. 79; at. wt. 197.2.  It is the most malleable",
        "and ductile of all metals, and very heavy (sp. gr., 19.3).",
        "It is quite unalterable by heat, moisture, and most",
        "corrosive agents, and therefore well suited for its use in",
        "coin and jewelry.",
        "     [ Webster's New International Dictionary",
        "          of the English Language, Second Edition ]",

        "The little girl stood on tip-toe and picked one of the nicest",
        "and biggest lunch-boxes, and then she sat down upon the ground",
        "and eagerly opened it.  Inside she found, nicely wrapped in",
        "white papers, a ham sandwich, a piece of sponge-cake, a pickle,",
        "a slice of new cheese and an apple.  Each thing had a separate",
        "stem, and so had to be picked off the side of the box; but",
        "Dorothy found them all to be delicious, and she ate every bit",
        "of luncheon in the box before she had finished.",
        "        [ Ozma of Oz, by L. Frank Baum ]",

        'But I asked why not keep it and let the hen sit on it till it',
        'hatched, and then we could see what would come out of it.',
        `"Nothing good, I'm certain of that," Mom said.  "It would`,
        "probably be something horrible.  But just remember, if it's a",
        "crocodile or a dragon or something like that, I won't have it",
        'in my house for one minute."',
        "        [ The Enormous Egg, by Oliver Butterworth ]",

        '"You know salmon, Sarge," said Nobby.',
        '"It is a fish of which I am aware, yes."',
        '"You know they sell kind of slices of it in tins..."',
        '"So I am given to understand, yes."',
        '"Weell...how come all the tins are the same size?  Salmon',
        'gets thinner at both ends."',
        '"Interesting point, Nobby.  I think-"',
        "        [ Soul Music, by Terry Pratchett ]",

        "And I was gazing on the surges prone,",
        "With many a scalding tear and many a groan,",
        "When at my feet emerg'd an old man's hand,",
        "Grasping this scroll, and this same slender wand.",
        "I knelt with pain--reached out my hand--had grasp'd",
        "Those treasures--touch'd the knuckles--they unclasp'd--",
        "I caught a finger: but the downward weight",
        "O'erpowered me--it sank. Then 'gan abate",
        "The storm, and through chill aguish gloom outburst",
        "The comfortable sun. I was athirst",
        "To search the book, and in the warming air",
        "Parted its dripping leaves with eager care.",
        "Strange matters did it treat of, and drew on",
        "My soul page after page, till well-nigh won",
        "Into forgetfulness; when, stupefied,",
        "I read these words, and read again, and tried",
        "My eyes against the heavens, and read again.",
        "        [ Endymion, by John Keats ]",

        "mail turns to dust and falls to the stairs!",

        "Closed for inventory",
        '"How dare you break my door?"',
        "Do you want to see what you had when you died?", 
        
        "There is an open door here.",

        "Faustus: Come on Mephistopheles.  What shall we do?",
        "Mephistopheles: Nay, I know not.  We shall be cursed with bell,",
        "book, and candle.",
        "Faustus: How?  Bell, book, and candle, candle, book, and bell,",
        "Forward and backward, to curse Faustus to hell.",
        "Anon you shall hear a hog grunt, a calf bleat, and an ass bray,",
        "Because it is Saint Peter's holy day.",
        "(Enter all the Friars to sing the dirge)",
        "        [ Doctor Faustus and Other Plays, by Christopher Marlowe ]",

        "You don't find anything here to loot.",

        "In World War II, Britain's air ministry spread the word that",
        "a diet of these vegetables helped pilots see Nazi bombers",
        "attacking at night.  That was a lie intended to cover the real",
        "matter of what was underpinning the Royal Air Force's successes:",
        "Airborne Interception Radar, also known as AI. ... British",
        "Intelligence didn't want the Germans to find out about the",
        "superior new technology helping protect the nation, so they",
        "created a rumor to afford a somewhat plausible-sounding",
        "explanation for the sudden increase in bombers being shot down.",
        "... The disinformation was so persuasive that the English public",
        "took to eating carrots to help them find their way during the",
        "blackouts.",
        "        [ Urban Legends Reference Pages ]",

        "NEWTONIAN, adj.  Pertaining to a philosophy of the universe",
        "invented by Newton, who discovered that an apple will fall",
        "to the ground, but was unable to say why.  His successors",
        "and disciples have advanced so far as to be able to say",
        "when.",

        "That is a silly thing to zap.",

        "POTABLE, n.  Suitable for drinking.  Water is said to be",
        "potable; indeed, some declare it our natural beverage,",
        "although even they find it palatable only when suffering",
        "from the recurrent disorder known as thirst, for which it",
        "is a medicine.  Upon nothing has so great and diligent",
        "ingenuity been brought to bear in all ages and in all",
        "countries, except the most uncivilized, as upon the",
        "invention of substitutes for water.  To hold that this",
        "general aversion to that liquid has no basis in the",
        "preservative instinct of the race is to be unscientific --",
        "and without science we are as the snakes and toads.",
        "Jack Burton:  What's in the flask, Egg?  Magic potion?",
        "   Egg Shen:  Yeah.",
        "       Jack:  I thought so, good.  What do we do?  Drink it?",
        "        Egg:  Yeah.",
        "       Jack:  Good, I thought so.",
        "     [later]",
        "       Jack:  This does what again, exactly?",
        "        Egg:  Huge buzz!  [drinks]  Oh good!  See things no",
        "              one else can see, do things no one else can do.",
        "        [ Big Trouble in Little China, directed by",
        "          John Carpenter, written by Gary Goldman &",
        "          David Z. Weinstein, adaptation by W. D. Richter ]",

        "The pen is mightier than the sword.",
        "        [ Richelieu, by Edward Bulwer-Lytton ]",

        "'Saruman!' he cried, and his voice grew in power and authority.",
        "'Behold, I am not Gandalf the Grey, whom you betrayed.  I am",
        "Gandalf the White, who has returned from death.  You have no",
        "colour now, and I cast you from the order and from the Council.'",
        "He raised his hand, and spoke slowly in a clear cold voice.",
        "'Saruman, your staff is broken.'  There was a crack, and the",
        "staff split asunder in Saruman's hand, and the head of it",
        "fell down at Gandalf's feet.  'Go!' said Gandalf.  With a cry",
        "Saruman fell back and crawled away.",
        "        [ The Two Towers, by J.R.R. Tolkien ]",

        '"When time came for the shepherds to hold their customary',
        "assembly in order to prepare their monthly report to the king",
        "about the state of the flocks, he came too, wearing this ring.",
        "While he was sitting with the others, it chanced that he moved",
        "the collet of the ring around toward himself into the inside of",
        "his hand; having done this, he disappeared from the sight of",
        "those who were sitting beside him, and they discussed of him as",
        "of someone who had left.  And he wondered and once again feeling",
        "for the ring, he turned the collet outwards and, by turning it,",
        "reappeared.  Reflecting upon this, he put the ring to the test",
        "to see if it indeed had such power, and he came to this",
        "conclusion that, by turning the collet inwards, he became",
        "invisible, outwards, visible.  Having perceived this, he at",
        "once managed for himself to become one of the envoys to the",
        "king; upon arrival, having seduced his wife, with her help,",
        "he laid a hand on the king, murdered him and took hold of the",
        'leadership."',
        "        [ The Republic, by Plato, translated by James Adam ]",

        "Three Rings for the Elven-kings under the sky,",
        "Seven for the Dwarf-lords in their halls of stone,",
        "Nine for Mortal Men doomed to die,",
        "One for the Dark Lord on his dark throne,",
        "In the Land of Mordor where the Shadows lie.",
        "One Ring to rule them all, One Ring to find them,",
        "One Ring to bring them all and in the darkness bind them",
        "        [ The Fellowship of the Ring, by J.R.R. Tolkien ]",

        "The Book of Three lay closed on the table.  Taran had never",
        "been allowed to read the volume for himself; now he was sure",
        "it held more than Dallben chose to tell him.  In the sun-",
        "filled room, with Dallben still meditating and showing no",
        "sign of stopping, Taran rose and moved through the shimmering",
        "beams.  From the forest came the monotonous tick of a beetle.",
        "His hands reached for the cover.  Taran gasped in pain and",
        "snatched them away.  They smarted as if each of his fingers",
        "had been stung by hornets.  He jumped back, stumbled against",
        "the bench, and dropped to the floor, where he put his fingers",
        "woefully into his mouth.",
        "Dallben's eyes blinked open.  He peered at Taran and yawned",
        'slowly.  "You had better see Coll about a lotion for those',
        `hands," he advised.  "Otherwise, I shouldn't be surprised if`,
        'they blistered."',
        "        [ The Book of Three, by Lloyd Alexander ]",

        "Cloaks are the universal outer garb of everyone who is not a",
        "Barbarian.  It is hard to see why.  They are open in front",
        "and require you at most times to use one hand to hold them",
        "shut.  On horseback they leave the shirt-sleeved arms and",
        "most of the torso exposed to wind and Weather.  The OMTs",
        "[ Official Management Terms ] for Cloaks well express their",
        "difficulties.  They are constantly _swirling and dripping_",
        "and becoming _heavy with water_ in rainy Weather, _entangling",
        "with trees_ or _swords_, or needing to be _pulled close",
        "around her/his shivering body_.  This seems to suggest they",
        "are less than practical for anyone on an arduous Tour.",
        "  [ The Tough Guide to Fantasyland, by Diana Wynne Jones ]",

        "So they stood, each in his place, neither moving a finger's",
        "breadth back, for one good hour, and many blows were given",
        "and received by each in that time, till here and there were",
        'sore bones and bumps, yet neither thought of crying "Enough,"',
        "or seemed likely to fall from off the bridge.  Now and then",
        "they stopped to rest, and each thought that he never had seen",
        "in all his life before such a hand at quarterstaff.  At last",
        "Robin gave the stranger a blow upon the ribs that made his",
        "jacket smoke like a damp straw thatch in the sun.  So shrewd",
        "was the stroke that the stranger came within a hair's breadth",
        "of falling off the bridge; but he regained himself right",
        "quickly, and, by a dexterous blow, gave Robin a crack on the",
        "crown that caused the blood to flow.  Then Robin grew mad",
        "with anger, and smote with all his might at the other; but",
        "the stranger warded the blow, and once again thwacked Robin,",
        "and this time so fairly that he fell heels over head into the",
        "water, as the queen pin falls in a game of bowls.",
        "        [ The Merry Adventures of Robin Hood, by Howard Pyle ]",

        "With this the wind increased, and the mill sails began to turn",
        "about; which Don Quixote espying, said, 'Although thou movest",
        "more arms than the giant Briareus thou shalt stoop to me.'",
        "And, after saying this, and commending himself most devoutly",
        "to his Lady Dulcinea, desiring her to succor him in that trance,",
        "covering himself well with his buckler, and setting his lance",
        "on his rest, he spurred on Rozinante, and encountered with the",
        "first mill that was before him, and, striking his lance into",
        "the sail, the wind swung it about with such fury, that it broke",
        "his lance into shivers, carrying him and his horse after it,",
        "and finally tumbled him a good way off from it on the field in",
        "evil plight.",
        "  [ Don Quixote of La Mancha, by Miquel de Cervantes Saavedra ]",

        "You feel a wrenching sensation.",

        "But as Snow White grew, she became more and more beautiful,",
        "and by the time she was seven years old she was as beautiful",
        "as the day and more beautiful than the queen herself.  One",
        "day when the queen said to her mirror:",
        '        "Mirror, Mirror, here I stand.',
        '        Who is the fairest in the land?" -',
        'the mirror replied:",',
        '        "You, O Queen, are the fairest here,',
        '        But Snow White is a thousand times more fair."',
        "        [ Snow White, by Jakob and Wilhelm Grimm ]",

        '"God save thee, ancient Mariner!',
        "From the fiends, that plague thee thus! -",
        `Why look'st thou so?" - With my cross-bow`,
        "I shot the Albatross.",
        "  [ The Rime of the Ancient Mariner, by Samuel Taylor Coleridge ]",

        "Call me if you need my phone number!",
        "Oh wow!  Everything looks so cosmic!",
        "You perceive yourself...",
        "awareness re-normalizes.",
        "You feel much better.",
        "Everything looks SO boring now.",
        "You only feel hungry now.",
        "Do you want to see your conduct and achievements?",

        "I can't go to Hell.  They're afraid I'm gonna take over!",

        "When he came to himself he told his mother what had passed,",
        "and showed her the lamp and the fruits he had gathered in the",
        "garden, which were in reality precious stones.  He then asked",
        "for some food.",
        '"Alas! child," she said, "I have nothing in the house, but I',
        'have spun a little cotton and will go and sell it."',
        "Aladdin bade her keep her cotton, for he would sell the lamp",
        "instead.  As it was very dirty she began to rub it, that it",
        "might fetch a higher price.  Instantly a hideous genie",
        "appeared, and asked what she would have.  She fainted away,",
        "but Aladdin, snatching the lamp, said boldly:",
        '"Fetch me something to eat!"',
        "        [ Aladdin, from The Arabian Nights, by Andrew Lang ]",

        "- they come together with great random, and a spear is brast,",
        "and one party brake his shield and the other one goes down,",
        "horse and man, over his horse-tail and brake his neck, and",
        "then the next candidate comes randoming in, and brast his",
        "spear, and the other man brast his shield, and down he goes,",
        "horse and man, over his horse-tail, and brake his neck, and",
        "then there's another elected, and another and another and",
        "still another, till the material is all used up; and when you",
        "come to figure up results, you can't tell one fight from",
        "another, nor who whipped; and as a picture of living, raging,",
        "roaring battle, sho! why it's pale and noiseless -",
        "ghosts scuffling in a fog.  Dear me, what would this barren",
        "vocabulary get out of the mightiest spectacle? - the burning",
        "of Rome in Nero's time, for instance?  Why, it would merely",
        "say 'Town burned down; no insurance; boy brast a window,",
        "fireman brake his neck!'  Why, that ain't a picture!",
        "        [ A Connecticut Yankee in King Arthur's Court,",
        "            by Mark Twain ]",

        "Hello player, welcome to NetHack!  You are a neutral female gnomish Archeologist.",

        '"Good," he said and, unbelievably, smiled at me, a smirk like',
        'a round of rotted cheese.  "What did your keeper use on you?',
        'A bullwhip?"',
        "        [ Melusine, by Sarah Monette ]",

        "Some hats can only be worn if you're willing to be jaunty, to set",
        "them at an angle and to walk beneath them with a spring in your",
        "stride as if you're only a step away from dancing.  They demand a",
        "lot of you.",
        "        [ Anansi Boys, by Neil Gaiman ]",

        "The mine is full of holes;",
        "With the wound of pickaxes.",
        "But look at the goldsmith's store.",
        "There, there is gold everywhere.",
        "        [ Divan-i Kebir Meter 2, by Mevlana Celaleddin Rumi ]",

        '"Now, this third handkerchief," Mein Herr proceeded, "has also',
        'four edges, which you can trace continuously round and round:',
        'all you need do is to join its four edges to the four edges of',
        'the opening.  The Purse is then complete, and its outer',
        'surface--"',
        '"I see!" Lady Muriel eagerly interrupted.  "Its outer surface',
        'will be continuous with its inner surface!  But it will take',
        `time. I'll sew it up after tea."  She laid aside the bag, and`,
        `resumed her cup of tea.  "But why do you call it Fortunatus's`,
        'Purse, Mein Herr?"',
        'The dear old man beamed upon her, with a jolly smile, looking',
        `more exactly like the Professor than ever.  "Don't you see,`,
        'my child--I should say Miladi?  Whatever is inside that Purse,',
        'is outside it; and whatever is outside it, is inside it.  So',
        'you have all the wealth of the world in that leetle Purse!"',
        '        [ Sylvie and Bruno Concluded, by Lewis Carroll ]',

        '"Gold is tried by a touchstone, men by gold."',
        "        [ Chilon (c. 560 BC) ]",

        "a pair of buckled boots",

        "A scalpel is a very sharp knife used for surgery ... Merely",
        "touching a medical scalpel with bare hands to test it will",
        "cut through the skin. ... Medical scalpel blades are gradually",
        "curved for greater precision when cutting through tissue.",
        "        [ Wikipedia, the free encyclopedia ]",

        "Sleep is a death; oh, make me try",
        "By sleeping, what it is to die,",
        "And as gently lay my head",
        "On my grave, as now my bed.",
        "        [ Religio Medici, by Sir Thomas Browne ]",

        "You flip a gold piece.",
        "It comes up heads.",
        "It comes up tails.",
        "Please move the cursor to a monster, object or location.",

        `"Stand to it, my hearts of gold," said the old bowman as he`,
        `passed from knot to knot.  "By my hilt! we are in luck this`,
        `journey.  Bear in mind the old saying of the Company."`,
        `"What is that, Aylward?" cried several, leaning on their bows`,
        `and laughing at him.`,
        `"'Tis the master-bowyer's rede: 'Every bow well bent.  Every`,
        `shaft well sent.  Every stave well nocked.  Every string well`,
        `locked.'  There, with that jingle in his head, a bracer on`,
        `his left hand, a shooting glove on his right, and a`,
        `farthing's-worth of wax in his girdle, what more doth a`,
        `bowman need?"`,
        `"It would not be amiss," said Hordle John, "if under his`,
        `girdle he had four farthings'-worth of wine."`,
        `        [ The White Company, by Sir Arthur Conan Doyle ]`,

        "I shot an arrow into the air,",
        "It fell to earth, I knew not where;",
        "For, so swiftly it flew, the sight",
        "Could not follow it in its flight.",
        "I breathed a song into the air,",
        "For who has sight so keen and strong",
        "That it can follow the flight of song?",
        "Long, long afterward, in an oak",
        "I found the arrow still unbroke;",
        "And the song, from beginning to end,",
        "I found again in the heart of a friend.",
        "  [ The Arrow and the Song, by Henry Wadsworth Longfellow ]",

        "What was the fruit like?  Unfortunately, no one can describe",
        "a taste.  All I can say is that, compared with those fruits,",
        "the freshest grapefruit you've ever eaten was dull, and the",
        "juiciest orange was dry, and the most melting pear was hard",
        "and woody, and the sweetest wild strawberry was sour.  And",
        "there were no seeds or stones, and no wasps.  If you had once",
        "eaten that fruit, all the nicest things in this world would",
        "taste like medicines after it.  But I can't describe it.  You",
        "can't find out what it is like unless you can get to that",
        "country and taste it for yourself.",
        "        [ The Last Battle, by C.S. Lewis ]",

        "Can you give me mouth to mouth, you just took my breath away.",

        "Yecch!  This stuff tastes like poison.",
        "(But in fact it was biologically contaminated slime mold juice.)",
        "Fortunately, you have been immunized.",
        "A lit field surrounds you!",
        "This tastes like slime mold juice.",
        "You hear nothing special.",
        "You fail to cast the spell correctly.",
        "The magical energy is released!",
        "Sorry, I don't know how to use that.",

        "You hands begin to glow red.",
        "You hands no longer glow so brightly red.",
        "You feel like someone is helping you.",

        "This is an identify scroll.",
        "neutral altar",
        "You hands stop glowing red.",
        "Type letter (or punctuation) or name used for a class of monsters or 'none'.",
        "No creatures have been genocided yet.",
        "Do you want a list of species genocided?",
        "He always lied while on the earth and now he's lying in it",

        "You feel that monsters no longer have difficulty pinpointing your location.",
        "Your judgement is impaired.",

        "If you want to know what cram is, I can only say that I don't",
        "know the recipe; but it is biscuitish, keeps good indefinitely,",
        "is supposed to be sustaining, and is certainly not entertaining,",
        "being in fact very uninteresting except as a chewing",
        "exercise.  It was made by the Lake-men for long journeys.",
        "        [ The Hobbit, by J.R.R. Tolkien ]",

        "The difference between false memories and true ones is the",
        "same as for jewels:  it is always the false ones that look the",
        "most real, the most brilliant.",
        "        [ Salvador Dali ]",

        "Enter not into the path of the wicked",
        "You are carrying too much to get through.",
        "You see a door open.",
        "Ya really had me going baby, but now I'm gone.",
        "You hear a jackal howling at the moon.,",
        "You can't go up here.",

        "You finish taking off your suit.",
        "You feel that monsters have difficulty pinpointing your location.",
        "Magical energies course through your body.",
    
        "You begin bashing monsters with your gloved hands.",
        "There are several objects here.",

        "Unlock it with your credit card?",

        "Less than thirty Cat tribes now survived, roaming the cargo",
        "decks on their hind legs in a desperate search for food.",
        "But the food had gone.",
        "The supplies were finished.",
        "Weak and ailing, they prayed at the supply hold's silver",
        "mountains: huge towering acres of metal rocks which, in their",
        "pagan way, the mutant Cats believed watched over them.",
        "Amid the wailing and the screeching one Cat stood up and held",
        "aloft the sacred icon.  The icon which had been passed down",
        "as holy, and one day would make its use known.",
        "It was a piece of V-shaped metal with a revolving handle on",
        "its head.",
        "He took down a silver rock from the silver mountain, while",
        "the other Cats cowered and screamed at the blasphemy.",
        "He placed the icon on the rim of the rock, and turned the",
        "handle.",
        "And the handle turned.",
        "And the rock opened.",
        "And inside the rock was Alphabetti spaghetti in tomato sauce.",
        "        [ Red Dwarf, by Rob Grant and Doug Naylor ]",


        "Darts are missile weapons, designed to fly such that a sharp,",
        "often weighted point will strike first.  They can be",
        "distinguished from javelins by fletching (i.e., feathers on",
        "the tail) and a shaft that is shorter and/or more flexible,",
        "and from arrows by the fact that they are not of the right",
        "length to use with a normal bow.",
        "Against my foe I hurled a murderous dart.",
        "He caught it in his hand -- I heard him laugh --",
        "I saw the thing that should have pierced his heart",
        "Turn to a golden staff.",
        "        [ Gifts, by Mary Coleridge ]",

        "'One of the things he can't do, he can't ride a horse,' he",
        "said.  Then he stiffened as if sandbagged by a sudden",
        "recollection, gave a small yelp of terror and dashed into",
        "the gloom.  When he returned, the being",
        "Twoflower was",
        "hanging limply over his shoulder.  It was small and skinny,",
        "and dressed very oddly in a pair of knee-length britches and",
        "a shirt in such a violent and vivid conflict of colours that",
        "the Weasel's fastidious eye was offended even in the half-light.",
        "        [ The Colour of Magic, by Terry Pratchett ]",

        "Only once a year, on his birthday, did Charlie Bucket ever",
        "get to taste a bit of chocolate.  The whole family saved up",
        "their money for that special occasion, and when the great",
        "day arrived, Charlie was always presented with one small",
        "chocolate bar to eat all by himself.  And each time he",
        "received it, on those marvelous birthday mornings, he would",
        "place it carefully in a small wooden box that he owned, and",
        "treasure it as though it were a bar of solid gold; and for",
        "the next few days, he would allow himself only to look at it,",
        "but never to touch it.  Then at last, when he could stand it",
        "no longer, he would peel back a tiny bit of the paper",
        "wrapping at one corner to expose a tiny bit of chocolate, and",
        "then he would take a tiny nibble - just enough to allow the",
        "lovely sweet taste to spread out slowly over his tongue.  The",
        "next day, he would take another tiny nibble, and so on, and",
        "so on.  And in this way, Charlie would make his ten-cent bar",
        "of birthday chocolate last him for more than a month.",
        "        [ Charlie and the Chocolate Factory, by Roald Dahl ]",

        "There was a time when Rincewind had quite liked the iconoscope.",
        "He believed, against all experience, that the world was",
        "fundamentally understandable, and that if he could only equip",
        "himself with the right mental toolbox he could take the back off",
        "and see how it worked.  He was, of course, dead wrong.  The",
        "iconoscope didn't take pictures by letting light fall onto",
        "specially treated paper, as he had surmised, but by the far",
        "simpler method of imprisoning a small demon with a good eye for",
        "colour and a speedy hand with a paintbrush.  He had been very",
        "upset to find that out.",
        "        [ The Light Fantastic, by Terry Pratchett ]",

        "You are caught in a bear trap.",
        "You finally wriggle free.",

        "Robes are the only garments, apart from Shirts, ever to have",
        "sleeves.  They have three uses:",
        "1.  As the official uniform of Priests, Priestesses, Monks,",
        "Nuns (see Nunnery), and Wizards.  The OMT [ Official Management",
        "Term ] prescribed for the Robes of Priests and Nuns is that",
        "they _fall in severe folds_; of Priestesses that they _float_;",
        "and of Wizards that they _swirl_.  You can thus see who you",
        "are dealing with.",
        "2.  For Kings.  The OMT here is _falling in stately folds_.",
        "3.  As the garb of Desert Nomads.  [...]",
        "    [ The Tough Guide to Fantasyland, by Diana Wynne Jones ]",

        "staircase up",
        "staircase down",

        "You begin striking monsters with your gloved hands.",

        "Boom!",
        "You hear the rumble of distant thunder...",
        "It is fatal.",
        "You feel wise!",
        "You must have been very observant.",
        "It is hit.",


    ]
}
