/**
 * 固有名詞や単語単位の翻訳辞書
 * 再帰翻訳で使用されます。
 */
function nhMessage_entity() {
    return {
        //
        "you": "you",

        // 性別・神
        "god": "神",
        "goddess": "女神",
        "Her": "彼女",
        "Him": "彼",
        "Her.": "彼女。",
        "Him.": "彼。",

        // 神の名前
        "The Lady": "レディ",
        "Amaterasu Omikami": "天照大御神",
        "Quetzalcoatl": "ケツァルコアトル",
        "Lugh": "ルー",
        "Venus": "ヴィーナス",
        "Anu": "アヌ",
        "Hermes": "ヘルメス",
        "Set": "セト",
        "Tyr": "テュール",
        "Chih Sung-tzu": "赤松子",
        "Mars": "マーズ",
        "Camaxtli": "カマシュトリ",
        "Kos": "コス",
        "Thoth": "トート",
        "Ishtar": "イシュタル",
        "Huan Ti": "黄帝",
        "Mitora": "ミトラ",
        "Anhur": "アンフル",
        "Athena": "アテナ",
        "Offler": "オファーラー",
        "Poseidon": "ポセイドン",
        "Crom": "クロム",
        "Odin": "Odin",
        "Shan Lai Ching": "Shan Lai Ching",
        "Loki": "Loki",

        //
        "chaotic": "chaotic",


        // 職業（サンプル）
        "Rambler": "放浪者",
        "Hatamoto": "旗本",
        "Digger": "掘削者",
        "Gallant": "騎士",
        "Tenderfoot": "初心者",
        "Troglodyte": "原始人",
        "Rhizotomist": "薬草取り",
        "Plunderer": "掠奪者",
        "Plunderess": "掠奪者",
        "Stripling": "若造",
        "Candidate": "候補生",
        "Footpad": "追剥",
        "Evoker": "召喚師",
        "Aspirant": "志願者",

        // チュートリアル・その他
        "Move around with 4 2 8 6": "8 2 4 6 で上下左右に移動",
        "Move diagonally with 1 9 3 7": "7 9 1 3 で斜め移動",

        "an E note": "ミの音",
        "an F note": "ファの音",
        "an A note": "ラの音",
        "a B note": "シの音",
        "a C note": "ドの音",
        "a D note": "レの音",
        "an E flat": "Eフラットの音",
        "an F sharp": "Fシャープの音",
        "a G sharp": "Gシャープの音",
        "a B flat": "Bフラットの音",
        "a D flat": "Dフラットの音",

        "pool of water": "水たまり",
        "molten lava": "溶けた溶岩",
        "wall of lava": "溶岩の壁",
        "wall of water": "水の壁",

        "You stop in front of the door.": "ドアの前で立ち止まった。",
        "Wrong secret": "間違った秘密",
        "Use 'e' to eat edible things": "「e」で食べられるものを食べます",
        "You can run by prefixing a movement key with '5'": "移動キーの前に「5」を付けることで走ることができます",
        "Travel across the level with '_'": "「_」でレベル内を移動（トラベル）します",
        "Swap weapons quickly with 'x'": "「x」で武器を素早く切り替えます",
        "Use 'X' to use two weapons at once": "「X」で二刀流（二つの武器を同時に使用）にします",
        "Put on accessories with 'P'": "「P」でアクセサリーを身に着けます",
        "Remove accessories with 'R'": "「R」でアクセサリーを外します",
        "You \"quaff\" potions with 'q'": "「q」でポーションを「飲み（がぶ飲み）」ます",
        "Pick up the spellbook with ','": "「,」で魔導書を拾います",
        "Read the spellbook with 'r'": "「r」で魔導書を読みます",
        "Use 'Z' to cast a spell": "「Z」で呪文を唱えます",
        "Use '<' to go up the stairs": "「<」で階段を上ります",
        "Use '>' to go down the stairs": "「>」で階段を下りること",

        //pet/Monst
        "kitten": "子猫",
        "lichen": "地衣類",
        "sewer rat": "下水ネズミ",
        "newt": "イモリ",
        "jackal": "ジャッカル",
        "grid bug": "グリッドバグ",
        "brown mold": "茶色カビ",
        "goblin": "ゴブリン",
        "little dog": "子犬",
        "fox": "キツネ",
        "dwarf": "ドワーフ",
        "gnome": "ノーム",
        "giant rat": "大ネズミ",
        "it": "それ",
        "hobbit": "ホビット",
        "red mold": "赤カビ",

        "gecko": "ヤモリ",
        "yellow mold": "黄カビ",
        "floating eye": "浮遊する目玉",
        "hobgoblin": "ホブゴブリン",
        "orc": "オーク",
        "orc zombie": "オークゾンビ",
        "kobold": "kobold",
        "kobold zombie": "kobold zombie",
        "manes":"manes",
        "gnome lady":"gnome lady",
        "leprechaun":"leprechaun",
        "centipede":"centipede",
        "rothe":"rothe",
        "bat": "bat",
        "giant bat": "giant bat",

        // 状態・アイテム種別（再帰翻訳用）
        "corpse": "屍",
        "statue": "像",
        "egg": "卵",
        "scroll": "巻物",
        "potion": "ポーション",
        "wand": "杖",
        "ring": "指輪",
        "spellbook": "魔導書",
        "slime": "スライム",
        "boulder": "巨石",

        // 種族
        "human": "人間",
        "elf": "エルフ",
        "dwarf": "ドワーフ",
        "gnome": "ノーム",
        "orc": "オーク",

        //Command
        "zap": "zap",
        "put on": "put on",
        "wear": "wear",
        "wield": "wield",
        "fire": "fire",
        "ready": "ready",
        "read": "read",
        "drink": "drink",
        "eat": "eat",
    };
}
