function nhMessage_org() {
    return [
        "Shall I pick character's race, role, gender and alignment for you? [ynaq] ",

        "It is written in the Book of The Lady:",
        "",
        "    After the Creation, the cruel god Moloch rebelled",
        "    against the authority of Marduk the Creator.",
        "    Moloch stole from Marduk the most powerful of all",
        "    the artifacts of the gods, the Amulet of Yendor,",
        "    and he hid it in the dark cavities of Gehennom, the",
        "    Under World, where he now lurks, and bides his time.",

        "Your goddess The Lady seeks to possess the Amulet, and with it",
        "to gain deserved ascendance over the other gods.",
        "You, a newly trained Rambler, have been heralded",
        "from birth as the instrument of The Lady.  You are destined",
        "to recover the Amulet for your deity, or die in the",
        "attempt.  Your hour of destiny has come.  For the sake",
        "of us all:  Go bravely with The Lady!",
        "[The Lady has chosen you to recover the Amulet of Yendor for Her.]",

        "Beware, there will be no return!  Still climb? yn",
        "Do you want your possessions identified? ynq",
        "Do you want to see your attributes? ynq",
        "Do you want an account of creatures vanquished? ynq",
        "Do you want to see your conduct? ynq",
        "Do you want to see the dungeon overview? ynq",
        "Cannot open file xlogfile.  Is NetHack installed correctly?",

        "It is written in the Book of Amaterasu Omikami:",
        "Your goddess Amaterasu Omikami seeks to possess the Amulet, and with it",
        "You, a newly trained Hatamoto, have been heralded",
        "from birth as the instrument of Amaterasu Omikami.  You are destined",
        "of us all:  Go bravely with Amaterasu Omikami!",
        "[Amaterasu Omikami has chosen you to recover the Amulet of Yendor for Her.]",

        "It is written in the Book of Quetzalcoatl:",
        "Your god Quetzalcoatl seeks to possess the Amulet, and with it",
        "You, a newly trained Digger, have been heralded",
        "from birth as the instrument of Quetzalcoatl.  You are destined",
        "of us all:  Go bravely with Quetzalcoatl!",
        "[Quetzalcoatl has chosen you to recover the Amulet of Yendor for Him.]",

        "It is written in the Book of Lugh:",
        "Your god Lugh seeks to possess the Amulet, and with it",
        "You, a newly trained Gallant, have been heralded",
        "from birth as the instrument of Lugh.  You are destined",
        "of us all:  Go bravely with Lugh!",
        "[Lugh has chosen you to recover the Amulet of Yendor for Him.]",

        "It is written in the Book of Venus:",
        "Your goddess Venus seeks to possess the Amulet, and with it",
        "You, a newly trained Tenderfoot, have been heralded",
        "from birth as the instrument of Venus.  You are destined",
        "of us all:  Go bravely with Venus!",
        "[Venus has chosen you to recover the Amulet of Yendor for Her.]",
        
        "It is written in the Book of Anu:",
        "Your god Anu seeks to possess the Amulet, and with it",
        "You, a newly trained Troglodyte, have been heralded",
        "from birth as the instrument of Anu.  You are destined",
        "of us all:  Go bravely with Anu!",
        "[Anu has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Hermes:",
        "Your god Hermes seeks to possess the Amulet, and with it",
        "You, a newly trained Rhizotomist, have been heralded",
        "from birth as the instrument of Hermes.  You are destined",
        "of us all:  Go bravely with Hermes!",
        "[Hermes has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Set:",
        "Your god Set seeks to possess the Amulet, and with it",
        "You, a newly trained Plunderer, have been heralded",
        "from birth as the instrument of Set.  You are destined",
        "of us all:  Go bravely with Set!",
        "[Set has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Tyr:",
        "Your god Tyr seeks to possess the Amulet, and with it",
        "You, a newly trained Stripling, have been heralded",
        "from birth as the instrument of Tyr.  You are destined",
        "of us all:  Go bravely with Tyr!",
        "[Tyr has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Chih Sung-tzu:",
        "Your god Chih Sung-tzu seeks to possess the Amulet, and with it",
        "You, a newly trained Candidate, have been heralded",
        "from birth as the instrument of Chih Sung-tzu.  You are destined",
        "of us all:  Go bravely with Chih Sung-tzu!",
        "[Chih Sung-tzu has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Mars:",
        "Your god Mars seeks to possess the Amulet, and with it",
        "from birth as the instrument of Mars.  You are destined",
        "of us all:  Go bravely with Mars!",
        "[Mars has chosen you to recover the Amulet of Yendor for Him.]",
        "It is written in the Book of Camaxtli:",
        "Your god Camaxtli seeks to possess the Amulet, and with it",
        "from birth as the instrument of Camaxtli.  You are destined",
        "of us all:  Go bravely with Camaxtli!",
        "[Camaxtli has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Kos:",
        "Your god Kos seeks to possess the Amulet, and with it",
        "You, a newly trained Footpad, have been heralded",
        "from birth as the instrument of Kos.  You are destined",
        "of us all:  Go bravely with Kos!",
        "[Kos has chosen you to recover the Amulet of Yendor for Him.]",

        "You, a newly trained Plunderess, have been heralded",

        "Entering the tutorial.",
        "Something is engraved here on the floor.",
        "You read: \"Move around with h j k l\".",
        "You read: \"Move diagonally with b u n y\".",
        "You read: \"Some actions may require multiple tries before succeeding\".",
        "You read: \"Open the door by moving into it\".",
        "You read: \"Close the door with 'c'\".",
        "You read: \"Note: Outside the tutorial, Ctrl-key combinations are shown prefixed with a caret, like '^D'\".",
        "You read: \"This door is locked. Kick it with 'Ctrl-D'\".",
        "(Tip: use 'm' prefix to step in if you really want to.)",
        "You read: \"Look around the map with ';', press ESC when you're done\".",
        "You read: \"Use 's' to search for secret doors\".",
        "You read: \"Behind this door is a dark corridor\".",
        "You read: \"There are four traps next to you! Search for them.\".",
        "You read: \"Some traps can be disabled with 'M-u'\".",
        "You read: \"Pick up items with ','\".",
        "You read: \"Wear armor with 'W'\".",
        "You read: \"Wield weapons with 'w'\".",
        "You read: \"Hit monsters by walking into them.\".",
        "You read: \"Now you know the very basics. You can leave the tutorial via the magic portal.\".",
        "You read: \"Step into this portal to leave the tutorial\".",
        "You read: \"Push boulders by moving into them\".",
        "You read: \"Take off armor with 'T'\".",
        "You read: \"Some items have shuffled descriptions, different each game\".",
        "You read: \"Pick up this scroll, read it with 'r', and try to remove the armor again\".",
        "You read: \"Avoid being burdened, it slows you down\".",
        "You read: \"Drop items with 'd'\".",
        "You read: \"You can drop partial stacks by prefixing the item slot letter with a number\".",
        "You read: \"Throw items with 't'\".",
        "You read: \"Missiles, such as rocks, work better when fired from appropriate launcher\".",
        "You read: \"Wield the sling\".",
        "You read: \"Use 'f' to fire missiles with the wielded launcher\".",
        "You read: \"You can wait a turn with '.'\".",
        "You read: \"Firing launches items from your quiver; Use 'Q' to put items in it\".",
        "You read: \"You loot containers with 'M-l'\".",
        "You read: \"Containers can also be emptied with 'Alt-T'\".",
        "You read: \"Magic wands are used with 'z'\".",
        "You read: \"Another magic portal, a way to leave this tutorial\".",
        "Resuming regular play.",

        "It's a wall.",
        "The door opens.",
        "This door is locked.",
        "In what direction? ",
        "As you kick the door, it crashes open!",
        "There is a broken door here.",
        "You find a hidden door.",
        "The door resists!",
        "It's solid stone.",
        "What a strange direction!",
        "Thwack!!",
        "Whammm!!",
        "Really step onto that squeaky board? yn",
        "Really step into that magic portal? yn",
        "You activated a magic portal!",
        "Resetting time to move #1.",
        "There is a staircase up out of the dungeon here.",

        "You avoid stepping into the pool of water.",
        "You avoid stepping into the molten lava.",
        "You avoid stepping into the wall of lava.",
        "A board beneath you squeaks an A note loudly.",
        "A board beneath you squeaks an E note loudly.",
        "A board beneath you squeaks an F note loudly.",
        "A cloud of gas puts you to sleep!",
        "You wake up.",
        "You stumble into a spider web!",
        "You disentangle yourself.",
        "With great effort you move the boulder.",
        "You try to move the boulder, but in vain.",
        "However, you can squeeze yourself into a small opening.",
        "You see here a boulder.",
        "You cannot pass through the bars.",
        "It's a tree.",

        "What do you want to drop? [*] ",
        "You don't have that object.",
        "Never mind.",

        "It is written in the Book of Thoth:",
        "Your god Thoth seeks to possess the Amulet, and with it",
        "You, a newly trained Evoker, have been heralded",
        "from birth as the instrument of Thoth.  You are destined",
        "of us all:  Go bravely with Thoth!",
        "[Thoth has chosen you to recover the Amulet of Yendor for Him.]",
    
        "It is written in the Book of Ishtar:",
        "Your goddess Ishtar seeks to possess the Amulet, and with it",
        "from birth as the instrument of Ishtar.  You are destined",
        "of us all:  Go bravely with Ishtar!",
        "[Ishtar has chosen you to recover the Amulet of Yendor for Her.]",

        "It is written in the Book of Thoth:",
        "Your god Thoth seeks to possess the Amulet, and with it",
        "You, a newly trained Evoker, have been heralded",
        "from birth as the instrument of Thoth.  You are destined",
        "of us all:  Go bravely with Thoth!",
        "[Thoth has chosen you to recover the Amulet of Yendor for Him.]",
        "Aloha player, welcome to NetHack!  You are a neutral female human Tourist.",
        "It is written in the Book of Ishtar:",
        "Your goddess Ishtar seeks to possess the Amulet, and with it",
        "from birth as the instrument of Ishtar.  You are destined",
        "of us all:  Go bravely with Ishtar!",
        "[Ishtar has chosen you to recover the Amulet of Yendor for Her.]",

        "You fall into the pool of water!",
        "You sink like a rock.",
        "You try to crawl out of the water.",
        "Pheew!  That was close.",
        "You avoid stepping into the wall of water.",
        "You plunge into the wall of water!",

        "Really step onto that sleeping gas trap? yn",
        "A board beneath you squeaks a C note loudly.",
        "A board beneath you squeaks a G sharp loudly.",
        "A board beneath you squeaks a B flat loudly.",
        "You are stuck to the web.",
    ]
}
