/**
 * 固有名詞や単語単位の翻訳辞書
 * 再帰翻訳で使用されます。
 */
function nhMessage_entity() {
    return {
        //
        "you": "you",

        // 性別・神
        "god": "神",
        "goddess": "女神",
        "Her": "彼女",
        "Him": "彼",
        "Her.": "彼女。",
        "Him.": "彼。",

        // 神の名前
        "The Lady": "レディ",
        "Amaterasu Omikami": "天照大御神",
        "Quetzalcoatl": "ケツァルコアトル",
        "Lugh": "ルー",
        "Venus": "ヴィーナス",
        "Anu": "アヌ",
        "Hermes": "ヘルメス",
        "Set": "セト",
        "Tyr": "テュール",
        "Chih Sung-tzu": "赤松子",
        "Mars": "マーズ",
        "Camaxtli": "カマシュトリ",
        "Kos": "コス",
        "Thoth": "トート",
        "Ishtar": "イシュタル",
        "Huan Ti": "黄帝",
        "Mitora": "ミトラ",
        "Anhur": "アンフル",
        "Athena": "アテナ",
        "Offler": "オファーラー",
        "Poseidon": "ポセイドン",
        "Crom": "クロム",
        "Odin": "オーディン",
        "Shan Lai Ching": "山海経",
        "Loki": "ロキ",

        //Alignment
        "lawful": "秩序",
        "neutral": "中立",
        "chaotic": "混沌",

        // 職業（サンプル）
        "Rambler": "放浪者",
        "Hatamoto": "旗本",
        "Digger": "掘削者",
        "Gallant": "騎士",
        "Tenderfoot": "初心者",
        "Troglodyte": "原始人",
        "Rhizotomist": "薬草取り",
        "Plunderer": "掠奪者",
        "Plunderess": "掠奪者",
        "Stripling": "若造",
        "Candidate": "候補生",
        "Footpad": "追剥",
        "Evoker": "召喚師",
        "Aspirant": "志願者",

        //Starting attributes
        "Archeologist": "考古学者",
        "Barbarian": "武闘家",
        "Caveman": "洞窟人",
        "Healer": "ヒーラー",
        "Knight": "騎士",
        "Monk": "僧侶",
        "Priest": "僧侶",
        "Ranger": "レンジャー",
        "Rogue": "ローグ",
        "Samurai": "侍",
        "Tourist": "観光客",
        "Valkyrie": "ワルキューレ",
        "Wizard": "魔法使い",

        // チュートリアル・その他
        "Move around with 4 2 8 6": "8 2 4 6 で上下左右に移動",
        "Move diagonally with 1 9 3 7": "7 9 1 3 で斜め移動",

        "an E note": "ミの音",
        "an F note": "ファの音",
        "an A note": "ラの音",
        "a B note": "シの音",
        "a C note": "ドの音",
        "a D note": "レの音",
        "an E flat": "Eフラットの音",
        "an F sharp": "Fシャープの音",
        "a G sharp": "Gシャープの音",
        "a B flat": "Bフラットの音",
        "a D flat": "Dフラットの音",

        "pool of water": "水たまり",
        "molten lava": "溶けた溶岩",
        "wall of lava": "溶岩の壁",
        "wall of water": "水の壁",

        "You stop in front of the door.": "ドアの前で立ち止まった。",
        "Wrong secret": "間違った秘密",
        "Use 'e' to eat edible things": "「e」で食べられるものを食べます",
        "You can run by prefixing a movement key with '5'": "移動キーの前に「5」を付けることで走ることができます",
        "Travel across the level with '_'": "「_」でレベル内を移動（トラベル）します",
        "Swap weapons quickly with 'x'": "「x」で武器を素早く切り替えます",
        "Use 'X' to use two weapons at once": "「X」で二刀流（二つの武器を同時に使用）にします",
        "Put on accessories with 'P'": "「P」でアクセサリーを身に着けます",
        "Remove accessories with 'R'": "「R」でアクセサリーを外します",
        "You \"quaff\" potions with 'q'": "「q」でポーションを「飲み（がぶ飲み）」ます",
        "Pick up the spellbook with ','": "「,」で魔導書を拾います",
        "Read the spellbook with 'r'": "「r」で魔導書を読みます",
        "Use 'Z' to cast a spell": "「Z」で呪文を唱えます",
        "Use '<' to go up the stairs": "「<」で階段を上ります",
        "Use '>' to go down the stairs": "「>」で階段を下りること",

        // pet/Monst (from monster_list.ja.md & item_list.ja.md)
        "giant ant": "巨大蟻",
        "killer bee": "キラービー",
        "soldier ant": "兵隊蟻",
        "fire ant": "火炎蟻",
        "giant beetle": "巨大甲虫",
        "queen bee": "女王蜂",
        "acid blob": "酸のブロッブ",
        "quivering blob": "震えるブロッブ",
        "gelatinous cube": "ゼラチンキューブ",
        "chickatrice": "チカトリス",
        "cockatrice": "コカトリス",
        "pyrolisk": "パイロリスク",
        "jackal": "ジャッカル",
        "fox": "キツネ",
        "coyote": "コヨーテ",
        "werejackal": "ワー・ジャッカル",
        "little dog": "子犬",
        "dingo": "ディンゴ",
        "dog": "犬",
        "large dog": "大きな犬",
        "floating eye": "フローティング・アイ",
        "kitten": "子猫",
        "housecat": "飼い猫",
        "large cat": "大きな猫",
        "gremlin": "グレムリン",
        "hobbit": "ホビット",
        "dwarf": "ドワーフ",
        "bugbear": "バグベア",
        "dwarf lord": "ドワーフの貴族",
        "dwarf king": "ドワーフの王",
        "manes": "マネス",
        "homunculus": "ホムンクルス",
        "imp": "インプ",
        "lemure": "レムール",
        "quasit": "クアジット",
        "tengu": "天狗",
        "blue jelly": "青いゼリー",
        "spotted jelly": "斑点のあるゼリー",
        "ochre jelly": "黄土色のゼリー",
        "kobold": "コボルド",
        "large kobold": "大きなコボルド",
        "kobold lord": "コボルドの君主",
        "kobold shaman": "コボルドのシャーマン",
        "leprechaun": "レプラコーン",
        "small mimic": "小さなミミック",
        "large mimic": "大きなミミック",
        "giant mimic": "巨大なミミック",
        "wood nymph": "森のニンフ",
        "water nymph": "水のニンフ",
        "mountain nymph": "山のニンフ",
        "goblin": "ゴブリン",
        "hobgoblin": "ホブゴブリン",
        "orc": "オーク",
        "hill orc": "山オーク",
        "Mordor orc": "モルドールオーク",
        "Uruk-hai": "ウルク＝ハイ",
        "orc shaman": "オークのシャーマン",
        "orc-captain": "オークの隊長",
        "rock piercer": "岩抜き",
        "iron piercer": "鉄抜き",
        "glass piercer": "ガラス抜き",
        "rothe": "ローセ",
        "mumak": "ムマク",
        "leocrotta": "レオクロッタ",
        "wumpus": "ワンプス",
        "titanothere": "ティタノテリウム",
        "baluchitherium": "バルキテリウム",
        "mastodon": "マストドン",
        "sewer rat": "ドブネズミ",
        "giant rat": "巨大ネズミ",
        "rabid rat": "狂犬病ネズミ",
        "wererat": "ワー・ラット",
        "rock mole": "イワモグラ",
        "woodchuck": "ウッドチャック",
        "cave spider": "洞窟蜘蛛",
        "centipede": "ムカデ",
        "giant spider": "巨大蜘蛛",
        "scorpion": "サソリ",
        "lurker above": "天井に潜むもの",
        "trapper": "トラッパー",
        "pony": "子馬",
        "white unicorn": "白いユニコーン",
        "gray unicorn": "灰色のユニコーン",
        "black unicorn": "黒いユニコーン",
        "horse": "馬",
        "warhorse": "軍馬",
        "fog cloud": "霧の雲",
        "dust vortex": "塵の渦",
        "ice vortex": "氷の渦",
        "energy vortex": "エネルギーの渦",
        "steam vortex": "蒸気の渦",
        "fire vortex": "火の渦",
        "baby long worm": "赤子長虫",
        "baby purple worm": "赤子紫虫",
        "long worm": "長虫",
        "purple worm": "紫虫",
        "grid bug": "グリッドバグ",
        "xan": "ザン",
        "yellow light": "黄色い光",
        "black light": "黒い光",
        "zruty": "ズルティ",
        "couatl": "クアトル",
        "Aleax": "アレアクス",
        "Angel": "天使",
        "ki-rin": "麒麟",
        "Archon": "アルコン",
        "bat": "コウモリ",
        "giant bat": "巨大コウモリ",
        "raven": "大烏",
        "vampire bat": "吸血コウモリ",
        "plains centaur": "平原のケンタウロス",
        "forest centaur": "森のケンタウロス",
        "mountain centaur": "山のケンタウロス",
        "gray dragon": "グレイドラゴン",
        "silver dragon": "シルバードラゴン",
        "red dragon": "レッドドラゴン",
        "white dragon": "ホワイトドラゴン",
        "orange dragon": "オレンジドラゴン",
        "black dragon": "ブラックドラゴン",
        "blue dragon": "ブルードラゴン",
        "green dragon": "グリーンドラゴン",
        "yellow dragon": "イエロードラゴン",
        "stalker": "ストーカー",
        "air elemental": "大気の精霊",
        "fire elemental": "火の精霊",
        "earth elemental": "大地の精霊",
        "water elemental": "水の精霊",
        "lichen": "地衣類",
        "brown mold": "茶色のカビ",
        "yellow mold": "黄色のカビ",
        "green mold": "緑色のカビ",
        "red mold": "赤色のカビ",
        "shrieker": "シュリーカー",
        "violet fungus": "ヴァイオレット・ファンガス",
        "gnome": "ノーム",
        "gnome lord": "ノームの貴族",
        "gnomish wizard": "ノームの術師",
        "gnome king": "ノームの王",
        "giant": "巨人",
        "stone giant": "石の巨人",
        "hill giant": "丘の巨人",
        "fire giant": "火の巨人",
        "frost giant": "氷の巨人",
        "ettin": "エティン",
        "storm giant": "嵐の巨人",
        "titan": "ティタン",
        "minotaur": "ミノタウロス",
        "jabberwock": "ジャバウォック",
        "Keystone Kop": "キーストーン・コップ",
        "lich": "リッチ",
        "master lich": "マスター・リッチ",
        "arch-lich": "アーチ・リッチ",
        "kobold mummy": "コボルドのミイラ",
        "human mummy": "人間のミイラ",
        "red naga": "レッド・ナーガ",
        "golden naga": "ゴールデン・ナーガ",
        "ogre": "オーガ",
        "gray ooze": "グレイ・ウーズ",
        "black pudding": "ブラック・プリン",
        "quantum mechanic": "量子力学者",
        "rust monster": "錆の怪物",
        "disenchanter": "ディスエンチャンター",
        "snake": "ヘビ",
        "pit viper": "クサリヘビ",
        "troll": "トロール",
        "umber hulk": "アンバー・ハルク",
        "vampire": "吸血鬼",
        "Vlad the Impaler": "串刺し公ヴラド",
        "wraith": "幽霊",
        "Nazgul": "ナズグル",
        "xorn": "ゾーン",
        "monkey": "猿",
        "yeti": "イエティ",
        "carnivorous ape": "肉食猿",
        "human zombie": "人間のゾンビ",
        "skeleton": "骸骨",
        "shopkeeper": "店主",
        "Medusa": "メデューサ",
        "Wizard of Yendor": "イェンダーの魔術師",
        "Death": "死神",
        "Pestilence": "疫病",
        "Famine": "飢饉",
        "giant eel": "巨大ウナギ",
        "kraken": "クラーケン",
        "newt": "イモリ",
        "chameleon": "カメレオン",
        "gecko": "ヤモリ",
        "it": "それ",
        "It": "それ",
        "gnome lady": "ノームの貴婦人",
        "kobold zombie": "コボルドのゾンビ",
        "dwarf zombie": "ドワーフのゾンビ",
        "gnome zombie": "ノームのゾンビ",

        // Weapons
        "arrow": "矢",
        "elven arrow": "エルフの矢",
        "runed arrow": "ルーンの矢",
        "orcish arrow": "オークの矢",
        "crude arrow": "粗末な矢",
        "silver arrow": "銀の矢",
        "ya": "竹の矢",
        "bamboo arrow": "竹の矢",
        "crossbow bolt": "クロスボウのボルト",
        "dart": "ダーツ",
        "little dart": "小さなダーツ",
        "shuriken": "手裏剣",
        "throwing star": "手裏剣",
        "boomerang": "ブーメラン",
        "spear": "槍",
        "elven spear": "エルフの槍",
        "runed spear": "ルーンの槍",
        "orcish spear": "オークの槍",
        "crude spear": "粗末な槍",
        "dwarvish spear": "ドワーフの槍",
        "stout spear": "頑丈な槍",
        "silver spear": "銀の槍",
        "javelin": "ジャベリン",
        "throwing spear": "投げ槍",
        "trident": "三叉矛",
        "dagger": "短剣",
        "elven dagger": "エルフの短剣",
        "runed dagger": "ルーンの短剣",
        "orcish dagger": "オークの短剣",
        "crude dagger": "粗末な短剣",
        "silver dagger": "銀の短剣",
        "athame": "アサメ",
        "scalpel": "手術用メス",
        "knife": "ナイフ",
        "stiletto": "スティレット",
        "worm tooth": "芋虫の歯",
        "crysknife": "クリスカナイフ",
        "axe": "斧",
        "battle-axe": "戦斧",
        "double-headed axe": "両頭の斧",
        "short sword": "ショートソード",
        "elven short sword": "エルフのショートソード",
        "runed short sword": "ルーンのショートソード",
        "orcish short sword": "オークのショートソード",
        "crude short sword": "粗末なショートソード",
        "dwarvish short sword": "ドワーフのショートソード",
        "broad short sword": "幅広いショートソード",
        "scimitar": "シミター",
        "curved sword": "曲刀",
        "silver saber": "銀のサーベル",
        "broadsword": "ブロードソード",
        "elven broadsword": "エルフのブロードソード",
        "runed broadsword": "ルーンのブロードソード",
        "long sword": "ロングソード",
        "two-handed sword": "両手剣",
        "katana": "カタナ",
        "samurai sword": "カタナ",
        "tsurugi": "ツルギ",
        "long samurai sword": "ツルギ",
        "runesword": "ルーンソード",
        "partisan": "パルチザン",
        "vulgar polearm": "ありふれた長柄武器",
        "ranseur": "ランセーア",
        "hilted polearm": "柄のある長柄武器",
        "spetum": "スペタム",
        "forked polearm": "二又の長柄武器",
        "glaive": "グレイブ",
        "single-edged polearm": "片刃の長柄武器",
        "halberd": "ハルバード",
        "angled poleaxe": "角ばった長柄斧",
        "bardiche": "バルディッシュ",
        "long poleaxe": "長い長柄斧",
        "voulge": "ヴルジュ",
        "pole cleaver": "長柄の鉈",
        "fauchard": "フォシャール",
        "pole sickle": "長柄の鎌",
        "guisarme": "ギザーム",
        "pruning hook": "剪定フック",
        "bill-guisarme": "ビルギザーム",
        "hooked polearm": "鉤状の長柄武器",
        "lucern hammer": "ルツェルン・ハンマー",
        "pronged polearm": "多枝の長柄武器",
        "bec de corbin": "ベド・コルバン",
        "beaked polearm": "嘴状の長柄武器",
        "dwarvish mattock": "ドワーフのマトック",
        "broad pick": "幅広いツルハシ",
        "lance": "ランス",
        "mace": "メイス",
        "silver mace": "銀のメイス",
        "morning star": "モーニングスター",
        "war hammer": "ウォーハンマー",
        "club": "棍棒",
        "rubber hose": "ゴムのホース",
        "quarterstaff": "杖",
        "staff": "杖",
        "aklys": "アクリス",
        "thonged club": "紐付きの棍棒",
        "flail": "フレイル",
        "bullwhip": "鞭",
        "bow": "弓",
        "elven bow": "エルフの弓",
        "runed bow": "ルーンの弓",
        "orcish bow": "オークの弓",
        "crude bow": "粗末な弓",
        "yumi": "和弓",
        "long bow": "ロングボウ",
        "sling": "投石紐",
        "crossbow": "クロスボウ",

        // Armor
        "elven leather helm": "エルフの革の兜",
        "leather hat": "革の帽子",
        "orcish helm": "オークの兜",
        "iron skull cap": "鉄の頭蓋冠",
        "dwarvish iron helm": "ドワーフの鉄の兜",
        "hard hat": "ヘルメット",
        "fedora": "中折れ帽",
        "cornuthaum": "コーニュソーム",
        "conical hat": "とんがり帽子",
        "dunce cap": "とんがり帽子",
        "dented pot": "へこんだ鍋",
        "helm of brilliance": "輝きの兜",
        "crystal helmet": "水晶の兜",
        "helmet": "兜",
        "plumed helmet": "羽飾りのある兜",
        "helm of caution": "警戒の兜",
        "etched helmet": "エッチングされた兜",
        "helm of opposite alignment": "逆配列の兜",
        "crested helmet": "紋章のついた兜",
        "helm of telepathy": "テレパシーの兜",
        "visored helmet": "面頬付きの兜",
        "gray dragon scale mail": "灰色ドラゴンの鱗鎧",
        "gold dragon scale mail": "金色ドラゴンの鱗鎧",
        "silver dragon scale mail": "銀色ドラゴンの鱗鎧",
        "red dragon scale mail": "赤色ドラゴンの鱗鎧",
        "white dragon scale mail": "白色ドラゴンの鱗鎧",
        "orange dragon scale mail": "橙色ドラゴンの鱗鎧",
        "black dragon scale mail": "黒色ドラゴンの鱗鎧",
        "blue dragon scale mail": "青色ドラゴンの鱗鎧",
        "green dragon scale mail": "緑色ドラゴンの鱗鎧",
        "yellow dragon scale mail": "黄色ドラゴンの鱗鎧",
        "gray dragon scales": "灰色ドラゴンの鱗",
        "gold dragon scales": "金色ドラゴンの鱗",
        "silver dragon scales": "銀色ドラゴンの鱗",
        "red dragon scales": "赤色ドラゴンの鱗",
        "white dragon scales": "白色ドラゴンの鱗",
        "orange dragon scales": "橙色ドラゴンの鱗",
        "black dragon scales": "黒色ドラゴンの鱗",
        "blue dragon scales": "青色ドラゴンの鱗",
        "green dragon scales": "緑色ドラゴンの鱗",
        "yellow dragon scales": "黄色ドラゴンの鱗",
        "plate mail": "プレートメイル",
        "crystal plate mail": "クリスタルプレートメイル",
        "bronze plate mail": "ブロンズプレートメイル",
        "splint mail": "スプリントメイル",
        "banded mail": "バンデッドメイル",
        "dwarvish mithril-coat": "ドワーフのミスリルコート",
        "elven mithril-coat": "エルフのミスリルコート",
        "chain mail": "チェインメイル",
        "orcish chain mail": "オークのチェインメイル",
        "crude chain mail": "粗末なチェインメイル",
        "scale mail": "スケイルメイル",
        "studded leather armor": "スタッドレザーアーマー",
        "ring mail": "リングメイル",
        "orcish ring mail": "オークのリングメイル",
        "crude ring mail": "粗末なリングメイル",
        "leather armor": "レザーアーマー",
        "leather jacket": "レザージャケット",
        "Hawaiian shirt": "アロハシャツ",
        "T-shirt": "Tシャツ",
        "mummy wrapping": "ミイラの包帯",
        "elven cloak": "エルフのクローク",
        "faded pall": "色あせた帳",
        "orcish cloak": "オークのクローク",
        "coarse mantelet": "粗末なマントレット",
        "dwarvish cloak": "ドワーフのクローク",
        "hooded cloak": "フード付きのクローク",
        "oilskin cloak": "オイルスキンクローク",
        "slippery cloak": "滑りやすいクローク",
        "robe": "ローブ",
        "alchemy smock": "錬金術師の作業着",
        "apron": "エプロン",
        "leather cloak": "革のクローク",
        "cloak of protection": "保護のクローク",
        "tattered cape": "ボロボロのケープ",
        "cloak of invisibility": "透明のクローク",
        "opera cloak": "オペラクローク",
        "cloak of magic resistance": "抗魔のクローク",
        "ornamental cope": "装飾的なカッパ",
        "cloak of displacement": "分身のクローク",
        "piece of cloth": "布切れ",
        "small shield": "小さな盾",
        "elven shield": "エルフの盾",
        "blue and green shield": "青と緑の盾",
        "Uruk-hai shield": "ウルク＝ハイの盾",
        "white-handed shield": "白い手の盾",
        "orcish shield": "オークの盾",
        "red-eyed shield": "赤い目の盾",
        "large shield": "大きな盾",
        "dwarvish roundshield": "ドワーフの円盾",
        "large round shield": "大きな円盾",
        "shield of reflection": "反射の盾",
        "polished silver shield": "磨かれた銀の盾",
        "leather gloves": "革の手袋",
        "old gloves": "古い手袋",
        "gauntlets of fumbling": "下手な小手",
        "padded gloves": "パッド付きの手袋",
        "gauntlets of power": "力の小手",
        "riding gloves": "乗馬用の手袋",
        "gauntlets of dexterity": "器用さの小手",
        "fencing gloves": "フェンシング用の手袋",
        "low boots": "短靴",
        "walking shoes": "ウォーキングシューズ",
        "iron shoes": "鉄の靴",
        "hard shoes": "硬い靴",
        "high boots": "長靴",
        "jackboots": "半長靴",
        "speed boots": "スピードの靴",
        "combat boots": "コンバットブーツ",
        "water walking boots": "水上歩行の靴",
        "jungle boots": "ジャングルブーツ",
        "jumping boots": "跳躍の靴",
        "hiking boots": "ハイキングブーツ",
        "elven boots": "エルフの靴",
        "mud boots": "泥だらけの靴",
        "kicking boots": "蹴りの靴",
        "buckled boots": "バックル付きの靴",
        "fumble boots": "下手な靴",
        "levitation boots": "浮遊の靴",
        "snow boots": "スノーブーツ",

        // Rings
        "adornment": "飾り",
        "gain strength": "腕力増大",
        "gain constitution": "体力増大",
        "increase accuracy": "命中率向上",
        "increase damage": "ダメージ向上",
        "protection": "保護",
        "regeneration": "再生",
        "searching": "探索",
        "stealth": "忍び",
        "sustain ability": "能力保持",
        "levitation": "浮遊",
        "hunger": "飢え",
        "aggravate monster": "モンスターを怒らせる",
        "conflict": "争い",
        "warning": "警告",
        "poison resistance": "毒耐性",
        "fire resistance": "火耐性",
        "cold resistance": "冷気耐性",
        "shock resistance": "電撃耐性",
        "free action": "自由行動",
        "slow digestion": "消化鈍化",
        "teleportation": "テレポート",
        "teleport control": "テレポート制御",

        // Amulets
        "amulet of clairvoyance": "透視のアミュレット",
        "amulet of drain resistance": "吸収耐性のアミュレット",
        "amulet of ESP": "ESPのアミュレット",
        "amulet of life saving": "生命維持のアミュレット",
        "amulet of magical breathing": "魔法の呼吸のアミュレット",
        "amulet of reflection": "反射のアミュレット",
        "amulet of restful sleep": "安眠のアミュレット",
        "amulet of strangulation": "絞殺のアミュレット",
        "amulet of unchanging": "不変のアミュレット",
        "amulet versus poison": "毒守りのアミュレット",

        // Tools
        "large box": "大きな箱",
        "chest": "宝箱",
        "ice box": "氷箱",
        "sack": "袋",
        "oilskin sack": "オイルスキンの袋",
        "bag of holding": "軽量化の袋",
        "bag of tricks": "手品の袋",
        "skeleton key": "合鍵",
        "lock pick": "ロックピック",
        "credit card": "クレジットカード",
        "tallow candle": "獣脂の蝋燭",
        "wax candle": "蜜蝋の蝋燭",
        "brass lantern": "真鍮のランタン",
        "oil lamp": "油灯",
        "expensive camera": "高級カメラ",
        "mirror": "鏡",
        "crystal ball": "水晶玉",
        "lenses": "レンズ",
        "blindfold": "目隠し",
        "towel": "タオル",
        "saddle": "鞍",
        "leash": "紐",
        "stethoscopes": "聴診器",
        "tinning kit": "缶詰作成キット",
        "tin opener": "缶切り",
        "can of grease": "グリース缶",
        "figurine": "小像",
        "magic marker": "魔法のマーカー",
        "land mine": "地雷",
        "beartrap": "虎ばさみ",
        "tin": "缶詰",
        "potion of oil": "油のポーション",

        // Food
        "meatball": "肉団子",
        "meat ring": "肉の輪",
        "meat stick": "肉の棒",
        "egg": "卵",
        "clove of garlic": "ニンニクの球根",
        "onion": "玉ねぎ",
        "apple": "リンゴ",
        "pear": "ナシ",
        "banana": "バナナ",
        "orange": "オレンジ",
        "fortune cookie": "占いクッキー",
        "candy bar": "キャンディバー",
        "pancake": "パンケーキ",
        "Lembas wafer": "レンバス",
        "cram ration": "携帯食糧",
        "food ration": "食料",
        "K-ration": "Kレーション",
        "C-ration": "Cレーション",
        "slime mold": "スライム・モールド",

        // Potions
        "gain ability": "能力上昇",
        "restore ability": "能力回復",
        "confusion": "混乱",
        "blindness": "盲目",
        "paralysis": "麻痺",
        "speed": "スピード",
        "halluncination": "幻覚",
        "see invisible": "可視",
        "healing": "回復",
        "extra healing": "強力回復",
        "full healing": "完全回復",
        "polymorph": "変身",
        "object detection": "アイテム探索",
        "monster detection": "モンスター探索",
        "enlightenment": "啓蒙",
        "gain energy": "エネルギー獲得",
        "acid": "酸",
        "blood": "血",
        "water": "水",

        // Scrolls
        "enchant armor": "防具強化",
        "enchant weapon": "武器強化",
        "identify": "鑑定",
        "light": "明かり",
        "blank paper": "白紙",
        "remove curse": "呪い解除",
        "gold detection": "金貨探索",
        "food detection": "食料探索",
        "magic mapping": "魔法の地図",
        "scare monster": "モンスターを怖がらせる",
        "taming": "モンスターを飼いならす",
        "amnesia": "忘却",
        "earth": "土",
        "fire": "火",
        "punishment": "処罰",
        "charging": "充填",
        "genocide": "大虐殺",
        "stinking cloud": "悪臭の雲",

        // Spellbooks
        "force bolt": "フォースボルト",
        "drain life": "生命吸収",
        "magic missile": "マジックミサイル",
        "cone of cold": "氷の円錐",
        "fireball": "ファイアボール",
        "finger of death": "死の指線",
        "lightning": "稲妻",
        "sleep": "睡眠",
        "detect monsters": "モンスター探索",
        "detect Food": "食料探索",
        "clairvoyance": "透視",
        "detect treasure": "宝探索",
        "stone to flesh": "石を肉にする",
        "cure blindness": "盲目治療",
        "cure sickness": "病気治療",
        "create monster": "モンスター作成",
        "jumping": "跳躍",
        "haste self": "加速",
        "teleport away": "テレポート",
        "knock": "開扉",
        "wizard lock": "施錠",
        "dig": "掘削",
        "cancellation": "無力化",
        "charm monster": "モンスター魅了",

        // Wands
        "nothing": "何も起きない",
        "digging": "掘削",
        "enrichment": "豊穣",
        "death": "死",
        "striking": "打撃",
        "opening": "開扉",
        "locking": "施錠",
        "probing": "調査",
        "secret door detection": "隠しドア探索",
        "slow monster": "モンスター鈍化",
        "speed monster": "モンスター加速",
        "undead turning": "アンデッドを追い払う",
        "make invisible": "透明化",
        "wishing": "願い",

        // Gems
        "dilithium crystal": "ディリチウムの結晶",
        "diamond": "ダイヤモンド",
        "ruby": "ルビー",
        "sapphire": "サファイア",
        "emerald": "エメラルド",
        "turquoise": "トルコ石",
        "aquamarine": "アクアマリン",
        "amber": "琥珀",
        "topaz": "トパーズ",
        "amethyst": "アメジスト",
        "agate": "メノウ",
        "jade": "ヒスイ",
        "garnet": "ガーネット",
        "opal": "オパール",
        "jet": "黒玉",
        "obsidian": "黒曜石",
        "chrysoberyl": "金緑石",
        "citrine": "シトリン",
        "jasper": "碧玉",
        "quartz": "石英",
        "rock crystal": "水晶",
        "fluorite": "蛍石",
        "luckstone": "幸運の石",
        "loadstone": "重い石",
        "touchstone": "試金石",
        "flint": "火打石",
        "rock": "岩",
        "glass": "屑ガラス",
        "gold piece": "金貨",

        // Artifacts
        "Excalibur": "エクスカリバー",
        "Stormbringer": "ストームブリンガー",
        "Mjollnir": "ミョルニル",
        "Cleaver": "クリーヴァー",
        "Grimtooth": "グリムトゥース",
        "Orcrist": "オルクリスト",
        "Sting": "スティング",
        "Magicbane": "マジックバイン",
        "Frost Brand": "フロストブランド",
        "Fire Brand": "ファイアブランド",
        "Dragonbane": "ドラゴンベイン",
        "Demonbane": "デーモンベイン",
        "Werebane": "ウェアベイン",
        "Grayswandir": "グレイスワンディール",
        "Giantslayer": "ジャイアントスレイヤー",
        "Ogresmasher": "オウガスマッシャー",
        "Trollsbane": "トロールズベイン",
        "Vorpal Blade": "ヴォーパルブレード",
        "Snickersnee": "スニッカースニー",
        "Sunsword": "サンソード",
        "The Orb of Detection": "探索の宝珠",
        "The Heart of Ahriman": "アーリマンの心臓",
        "The Sceptre of Might": "力の笏",
        "The Staff of Aesculapius": "アスクレピオスの杖",
        "The Magic Mirror of Merlin": "マーリンの魔法の鏡",
        "The Eyes of the Overworld": "異界の眼",
        "The Mitre of Holiness": "聖なる冠",
        "The Longbow of Diana": "ダイアナの長弓",
        "The Master Key of Thievery": "盗みのマスターキー",
        "The Tsurugi of Muramasa": "村正のツルギ",
        "The Platinum Yendorian Express Card": "プラチナ・イェンダー・エクスプレスカード",
        "The Orb of Fate": "運命の宝珠",
        "The Eye of the Aethiopica": "エチオピカの眼",

        // その他

        //Command
        "zap": "振る",
        "put on": "身に付ける",
        "wear": "着る",
        "wield": "構える",
        "fire": "発射",
        "ready": "準備",
        "read": "読む",
        "drink": "飲む",
        "eat": "食べる",
        "throw": "投げる",

        //color
        "milky": "milky", 

    };
}
