//items 
//
function nhMessage_entity_items() {
    return {
        //status
        "cursed": "呪われた",
        "uncursed": "呪われていない",
        "blessed": "祝福された",
        "locked": "施錠された",
        "unlocked": "解錠された",
        "greased": "油を塗られた",
        "poisoned": "毒を塗られた",
        "burnt": "焼けた",
        "very burnt": "ひどく焼けた",
        "thoroughly burnt": "焼き尽くされた",
        "rusted": "錆びた",
        "very rusted": "ひどく錆びた",
        "thoroughly rusted": "錆び付いた",
        "corroded": "腐食した",
        "very corroded": "ひどく腐食した",
        "thoroughly corroded": "朽ち果てた",
        "rotted": "腐った",
        "very rotted": "ひどく腐った",
        "thoroughly rotted": "腐り果てた",

        // Weapons
        "arrow": "矢",
        "elven arrow": "エルフの矢",
        "runed arrow": "ルーンの矢",
        "orcish arrow": "オークの矢",
        "crude arrow": "粗末な矢",
        "silver arrow": "銀の矢",
        "ya": "竹の矢",
        "bamboo arrow": "竹の矢",
        "crossbow bolt": "クロスボウのボルト",
        "dart": "ダーツ",
        "little dart": "小さなダーツ",
        "shuriken": "手裏剣",
        "throwing star": "手裏剣",
        "boomerang": "ブーメラン",
        "spear": "槍",
        "elven spear": "エルフの槍",
        "runed spear": "ルーンの槍",
        "orcish spear": "オークの槍",
        "crude spear": "粗末な槍",
        "dwarvish spear": "ドワーフの槍",
        "stout spear": "頑丈な槍",
        "silver spear": "銀の槍",
        "javelin": "ジャベリン",
        "throwing spear": "投げ槍",
        "trident": "三叉矛",
        "dagger": "短剣",
        "elven dagger": "エルフの短剣",
        "runed dagger": "ルーンの短剣",
        "orcish dagger": "オークの短剣",
        "crude dagger": "粗末な短剣",
        "silver dagger": "銀の短剣",
        "athame": "アサメ",
        "scalpel": "手術用メス",
        "knife": "ナイフ",
        "stiletto": "スティレット",
        "worm tooth": "芋虫の歯",
        "crysknife": "クリスカナイフ",
        "axe": "斧",
        "battle-axe": "戦斧",
        "double-headed axe": "両頭の斧",
        "short sword": "ショートソード",
        "elven short sword": "エルフのショートソード",
        "runed short sword": "ルーンのショートソード",
        "orcish short sword": "オークのショートソード",
        "crude short sword": "粗末なショートソード",
        "dwarvish short sword": "ドワーフのショートソード",
        "broad short sword": "幅広いショートソード",
        "scimitar": "シミター",
        "curved sword": "曲刀",
        "silver saber": "銀のサーベル",
        "broadsword": "ブロードソード",
        "elven broadsword": "エルフのブロードソード",
        "runed broadsword": "ルーンのブロードソード",
        "long sword": "ロングソード",
        "two-handed sword": "両手剣",
        "katana": "カタナ",
        "samurai sword": "カタナ",
        "tsurugi": "ツルギ",
        "long samurai sword": "ツルギ",
        "runesword": "ルーンソード",
        "partisan": "パルチザン",
        "vulgar polearm": "ありふれた長柄武器",
        "ranseur": "ランセーア",
        "hilted polearm": "柄のある長柄武器",
        "spetum": "スペタム",
        "forked polearm": "二又の長柄武器",
        "glaive": "グレイブ",
        "single-edged polearm": "片刃の長柄武器",
        "halberd": "ハルバード",
        "angled poleaxe": "角ばった長柄斧",
        "bardiche": "バルディッシュ",
        "long poleaxe": "長い長柄斧",
        "voulge": "ヴルジュ",
        "pole cleaver": "長柄の鉈",
        "fauchard": "フォシャール",
        "pole sickle": "長柄の鎌",
        "guisarme": "ギザーム",
        "pruning hook": "剪定フック",
        "bill-guisarme": "ビルギザーム",
        "hooked polearm": "鉤状の長柄武器",
        "lucern hammer": "ルツェルン・ハンマー",
        "pronged polearm": "多枝の長柄武器",
        "bec de corbin": "ベド・コルバン",
        "beaked polearm": "嘴状の長柄武器",
        "dwarvish mattock": "ドワーフのマトック",
        "broad pick": "幅広いツルハシ",
        "lance": "ランス",
        "mace": "メイス",
        "silver mace": "銀のメイス",
        "morning star": "モーニングスター",
        "war hammer": "ウォーハンマー",
        "club": "棍棒",
        "rubber hose": "ゴムのホース",
        "quarterstaff": "杖",
        "staff": "杖",
        "aklys": "アクリス",
        "thonged club": "紐付きの棍棒",
        "flail": "フレイル",
        "bullwhip": "鞭",
        "bow": "弓",
        "elven bow": "エルフの弓",
        "runed bow": "ルーンの弓",
        "orcish bow": "オークの弓",
        "crude bow": "粗末な弓",
        "yumi": "和弓",
        "long bow": "ロングボウ",
        "sling": "投石紐",
        "crossbow": "クロスボウ",

        // Armor
        "elven leather helm": "エルフの革の兜",
        "leather hat": "革の帽子",
        "orcish helm": "オークの兜",
        "iron skull cap": "鉄の頭蓋冠",
        "dwarvish iron helm": "ドワーフの鉄の兜",
        "hard hat": "ヘルメット",
        "fedora": "中折れ帽",
        "cornuthaum": "コーニュソーム",
        "conical hat": "とんがり帽子",
        "dunce cap": "とんがり帽子",
        "dented pot": "へこんだ鍋",
        "helm of brilliance": "輝きの兜",
        "crystal helmet": "水晶の兜",
        "helmet": "兜",
        "plumed helmet": "羽飾りのある兜",
        "helm of caution": "警戒の兜",
        "etched helmet": "エッチングされた兜",
        "helm of opposite alignment": "逆配列の兜",
        "crested helmet": "紋章のついた兜",
        "helm of telepathy": "テレパシーの兜",
        "visored helmet": "面頬付きの兜",
        "gray dragon scale mail": "灰色ドラゴンの鱗鎧",
        "gold dragon scale mail": "金色ドラゴンの鱗鎧",
        "silver dragon scale mail": "銀色ドラゴンの鱗鎧",
        "red dragon scale mail": "赤色ドラゴンの鱗鎧",
        "white dragon scale mail": "白色ドラゴンの鱗鎧",
        "orange dragon scale mail": "橙色ドラゴンの鱗鎧",
        "black dragon scale mail": "黒色ドラゴンの鱗鎧",
        "blue dragon scale mail": "青色ドラゴンの鱗鎧",
        "green dragon scale mail": "緑色ドラゴンの鱗鎧",
        "yellow dragon scale mail": "黄色ドラゴンの鱗鎧",
        "gray dragon scales": "灰色ドラゴンの鱗",
        "gold dragon scales": "金色ドラゴンの鱗",
        "silver dragon scales": "銀色ドラゴンの鱗",
        "red dragon scales": "赤色ドラゴンの鱗",
        "white dragon scales": "白色ドラゴンの鱗",
        "orange dragon scales": "橙色ドラゴンの鱗",
        "black dragon scales": "黒色ドラゴンの鱗",
        "blue dragon scales": "青色ドラゴンの鱗",
        "green dragon scales": "緑色ドラゴンの鱗",
        "yellow dragon scales": "黄色ドラゴンの鱗",
        "plate mail": "プレートメイル",
        "crystal plate mail": "クリスタルプレートメイル",
        "bronze plate mail": "ブロンズプレートメイル",
        "splint mail": "スプリントメイル",
        "banded mail": "バンデッドメイル",
        "dwarvish mithril-coat": "ドワーフのミスリルコート",
        "elven mithril-coat": "エルフのミスリルコート",
        "chain mail": "チェインメイル",
        "orcish chain mail": "オークのチェインメイル",
        "crude chain mail": "粗末なチェインメイル",
        "scale mail": "スケイルメイル",
        "studded leather armor": "スタッドレザーアーマー",
        "ring mail": "リングメイル",
        "orcish ring mail": "オークのリングメイル",
        "crude ring mail": "粗末なリングメイル",
        "leather armor": "レザーアーマー",
        "leather jacket": "レザージャケット",
        "Hawaiian shirt": "アロハシャツ",
        "T-shirt": "Tシャツ",
        "mummy wrapping": "ミイラの包帯",
        "elven cloak": "エルフのクローク",
        "faded pall": "色あせた帳",
        "orcish cloak": "オークのクローク",
        "coarse mantelet": "粗末なマントレット",
        "dwarvish cloak": "ドワーフのクローク",
        "hooded cloak": "フード付きのクローク",
        "oilskin cloak": "オイルスキンクローク",
        "slippery cloak": "滑りやすいクローク",
        "robe": "ローブ",
        "alchemy smock": "錬金術師の作業着",
        "apron": "エプロン",
        "leather cloak": "革のクローク",
        "cloak of protection": "保護のクローク",
        "tattered cape": "ボロボロのケープ",
        "cloak of invisibility": "透明のクローク",
        "opera cloak": "オペラクローク",
        "cloak of magic resistance": "抗魔のクローク",
        "ornamental cope": "装飾的なカッパ",
        "cloak of displacement": "分身のクローク",
        "piece of cloth": "布切れ",
        "small shield": "小さな盾",
        "elven shield": "エルフの盾",
        "blue and green shield": "青と緑の盾",
        "Uruk-hai shield": "ウルク＝ハイの盾",
        "white-handed shield": "白い手の盾",
        "orcish shield": "オークの盾",
        "red-eyed shield": "赤い目の盾",
        "large shield": "大きな盾",
        "dwarvish roundshield": "ドワーフの円盾",
        "large round shield": "大きな円盾",
        "shield of reflection": "反射の盾",
        "polished silver shield": "磨かれた銀の盾",
        "leather gloves": "革の手袋",
        "old gloves": "古い手袋",
        "gauntlets of fumbling": "下手な小手",
        "padded gloves": "パッド付きの手袋",
        "gauntlets of power": "力の小手",
        "riding gloves": "乗馬用の手袋",
        "gauntlets of dexterity": "器用さの小手",
        "fencing gloves": "フェンシング用の手袋",
        "low boots": "短靴",
        "walking shoes": "ウォーキングシューズ",
        "iron shoes": "鉄の靴",
        "hard shoes": "硬い靴",
        "high boots": "長靴",
        "jackboots": "半長靴",
        "speed boots": "スピードの靴",
        "combat boots": "コンバットブーツ",
        "water walking boots": "水上歩行の靴",
        "jungle boots": "ジャングルブーツ",
        "jumping boots": "跳躍の靴",
        "hiking boots": "ハイキングブーツ",
        "elven boots": "エルフの靴",
        "mud boots": "泥だらけの靴",
        "kicking boots": "蹴りの靴",
        "buckled boots": "バックル付きの靴",
        "fumble boots": "下手な靴",
        "levitation boots": "浮遊の靴",
        "snow boots": "スノーブーツ",

        // Rings
        "adornment": "飾り",
        "gain strength": "腕力増大",
        "gain constitution": "体力増大",
        "increase accuracy": "命中率向上",
        "increase damage": "ダメージ向上",
        "protection": "保護",
        "regeneration": "再生",
        "searching": "探索",
        "stealth": "忍び",
        "sustain ability": "能力保持",
        "levitation": "浮遊",
        "hunger": "飢え",
        "aggravate monster": "モンスターを怒らせる",
        "conflict": "争い",
        "warning": "警告",
        "poison resistance": "毒耐性",
        "fire resistance": "火耐性",
        "cold resistance": "冷気耐性",
        "shock resistance": "電撃耐性",
        "free action": "自由行動",
        "slow digestion": "消化鈍化",
        "teleportation": "テレポート",
        "teleport control": "テレポート制御",

        // Rings appearances
        "wooden": "木製",
        "granite": "花崗岩",
        "opal": "オパール製",
        "clay": "粘土製",
        "coral": "珊瑚製",
        "black onyx": "ブラックオニキス",
        "moonstone": "ムーンストーン",
        "tiger eye": "タイガーアイ",
        "jade": "翡翠製",
        "bronze": "青銅製",
        "agate": "瑪瑙製",
        "topaz": "トパーズ製",
        "sapphire": "サファイア製",
        "diamond": "ダイヤモンド製",
        "pearl": "真珠製",
        "iron": "鉄製",
        "brass": "真鍮製",
        "copper": "銅製",
        "twisted": "ねじれた",
        "steel": "鋼鉄製",
        "silver": "銀製",
        "gold": "金製",
        "ivory": "象牙製",
        "wire": "針金状",
        "engagement": "婚約",
        "shiny": "輝く",

        // Amulets
        "amulet of clairvoyance": "透視のアミュレット",
        "amulet of drain resistance": "吸収耐性のアミュレット",
        "amulet of ESP": "ESPのアミュレット",
        "amulet of life saving": "生命維持のアミュレット",
        "amulet of magical breathing": "魔法の呼吸のアミュレット",
        "amulet of reflection": "反射のアミュレット",
        "amulet of restful sleep": "安眠のアミュレット",
        "amulet of strangulation": "絞殺のアミュレット",
        "amulet of unchanging": "不変のアミュレット",
        "amulet versus poison": "毒守りのアミュレット",

        // Amulets appearances
        "circular": "円形",
        "spherical": "球体",
        "oval": "楕円形",
        "triangular": "三角形",
        "pyramidal": "ピラミッド型",
        "square": "四角形",
        "concave": "凹型",
        "octagonal": "八角形",
        "perforated": "穴の空いた",
        "cubical": "立方体",

        // Tools
        "large box": "大きな箱",
        "chest": "宝箱",
        "ice box": "氷箱",
        "sack": "袋",
        "oilskin sack": "オイルスキンの袋",
        "bag of holding": "軽量化の袋",
        "bag of tricks": "手品の袋",
        "skeleton key": "合鍵",
        "lock pick": "ロックピック",
        "credit card": "クレジットカード",
        "tallow candle": "獣脂の蝋燭",
        "wax candle": "蜜蝋の蝋燭",
        "brass lantern": "真鍮のランタン",
        "oil lamp": "油灯",
        "expensive camera": "高級カメラ",
        "mirror": "鏡",
        "crystal ball": "水晶玉",
        "lenses": "レンズ",
        "blindfold": "目隠し",
        "towel": "タオル",
        "saddle": "鞍",
        "leash": "紐",
        "stethoscopes": "聴診器",
        "tinning kit": "缶詰作成キット",
        "tin opener": "缶切り",
        "can of grease": "グリース缶",
        "figurine": "小像",
        "magic marker": "魔法のマーカー",
        "land mine": "地雷",
        "beartrap": "虎ばさみ",
        "tin": "缶詰",
        "potion of oil": "油のポーション",

        // Food
        "meatball": "肉団子",
        "meat ring": "肉の輪",
        "meat stick": "肉の棒",
        "egg": "卵",
        "clove of garlic": "ニンニクの球根",
        "onion": "玉ねぎ",
        "apple": "リンゴ",
        "pear": "ナシ",
        "banana": "バナナ",
        "orange": "オレンジ",
        "fortune cookie": "占いクッキー",
        "candy bar": "キャンディバー",
        "pancake": "パンケーキ",
        "Lembas wafer": "レンバス",
        "cram ration": "携帯食糧",
        "food ration": "食料",
        "K-ration": "Kレーション",
        "C-ration": "Cレーション",
        "slime mold": "スライム・モールド",

        // Potions
        "gain ability": "能力上昇",
        "restore ability": "能力回復",
        "confusion": "混乱",
        "blindness": "盲目",
        "paralysis": "麻痺",
        "speed": "スピード",
        "halluncination": "幻覚",
        "see invisible": "可視",
        "healing": "回復",
        "extra healing": "強力回復",
        "full healing": "完全回復",
        "polymorph": "変身",
        "object detection": "アイテム探索",
        "monster detection": "モンスター探索",
        "enlightenment": "啓蒙",
        "gain energy": "エネルギー獲得",
        "acid": "酸",
        "blood": "血",
        "water": "水",

        // Potions appearances
        "ruby": "ルビー色",
        "pink": "ピンク色",
        "orange": "オレンジ色",
        "yellow": "黄色",
        "emerald": "エメラルド色",
        "dark green": "濃い緑",
        "cyan": "シアン色",
        "sky blue": "空色",
        "brilliant blue": "鮮やかな青",
        "magenta": "マゼンタ色",
        "purple-red": "紫がかった赤",
        "puce": "暗褐色",
        "milky": "乳白色",
        "swirly": "渦巻いた",
        "bubbly": "泡立つ",
        "smoky": "煙った",
        "cloudy": "濁った",
        "effervescent": "弾ける",
        "black": "黒色",
        "golden": "金色",
        "brown": "茶色",
        "fizzy": "シュワシュワする",
        "dark": "暗い色",
        "white": "白色",
        "murky": "泥り",
        "clear": "透明な",
        "yellowish brown": "黄褐色",

        // Scrolls
        "enchant armor": "防具強化",
        "enchant weapon": "武器強化",
        "identify": "鑑定",
        "light": "明かり",
        "blank paper": "白紙",
        "remove curse": "呪い解除",
        "gold detection": "金貨探索",
        "food detection": "食料探索",
        "magic mapping": "魔法の地図",
        "scare monster": "モンスターを怖がらせる",
        "taming": "モンスターを飼いならす",
        "amnesia": "忘却",
        "earth": "土",
        "fire": "火",
        "punishment": "処罰",
        "charging": "充填",
        "genocide": "大虐殺",
        "stinking cloud": "悪臭の雲",

        // Spellbooks
        "force bolt": "フォースボルト",
        "drain life": "生命吸収",
        "magic missile": "マジックミサイル",
        "cone of cold": "氷の円錐",
        "fireball": "ファイアボール",
        "finger of death": "死の指線",
        "lightning": "稲妻",
        "sleep": "睡眠",
        "detect monsters": "モンスター探索",
        "detect Food": "食料探索",
        "clairvoyance": "透視",
        "detect treasure": "宝探索",
        "stone to flesh": "石を肉にする",
        "cure blindness": "盲目治療",
        "cure sickness": "病気治療",
        "create monster": "モンスター作成",
        "jumping": "跳躍",
        "haste self": "加速",
        "teleport away": "テレポート",
        "knock": "開扉",
        "wizard lock": "施錠",
        "dig": "掘削",
        "cancellation": "無力化",
        "charm monster": "モンスター魅了",

        // Spellbooks appearances
        "parchment": "羊皮紙",
        "vellum": "上質皮紙",
        "ragged": "ぼろぼろの",
        "dog eared": "耳折れの",
        "mottled": "斑点のある",
        "stained": "汚れた",
        "cloth": "布製",
        "leathery": "革のような",
        "light green": "明るい緑",
        "turquoise": "ターコイズ",
        "light blue": "明るい青",
        "dark blue": "濃い青",
        "indigo": "藍色",
        "purple": "紫色",
        "violet": "スミレ色",
        "tan": "黄褐色",
        "plaid": "格子縞",
        "light brown": "明るい茶色",
        "dark brown": "濃い茶色",
        "gray": "灰色",
        "wrinkled": "しわくちゃの",
        "dusty": "埃っぽい",
        "glittering": "きらめく",
        "shining": "光り輝く",
        "dull": "鈍い色",
        "thin": "薄い",
        "thick": "厚い",
        "checkered": "市松模様",
        "paperback": "ペーパーバック",
        "papyrus": "パピルス",

        // Wands
        "nothing": "何も起きない",
        "digging": "掘削",
        "enrichment": "豊穣",
        "death": "死",
        "striking": "打撃",
        "opening": "開扉",
        "locking": "施錠",
        "probing": "調査",
        "secret door detection": "隠しドア探索",
        "slow monster": "モンスター鈍化",
        "speed monster": "モンスター加速",
        "undead turning": "アンデッドを追い払う",
        "make invisible": "透明化",
        "wishing": "願い",

        // Wands appearances
        "balsa": "バルサ材",
        "maple": "カエデ",
        "pine": "松",
        "oak": "樫",
        "ebony": "コクタン",
        "marble": "大理石",
        "tin": "錫",
        "platinum": "白金",
        "iridium": "イリジウム",
        "zinc": "亜鉛",
        "aluminum": "アルミニウム",
        "uranium": "ウラン",
        "hexagonal": "六角形",
        "short": "短い",
        "runed": "ルーンの刻まれた",
        "long": "長い",
        "curved": "曲がった",
        "forked": "二股の",
        "spiked": "スパイク付き",
        "jeweled": "宝石を散りばめた",

        // Gems
        "dilithium crystal": "ディリチウムの結晶",
        "diamond": "ダイヤモンド",
        "ruby": "ルビー",
        "sapphire": "サファイア",
        "emerald": "エメラルド",
        "turquoise": "トルコ石",
        "aquamarine": "アクアマリン",
        "amber": "琥珀",
        "topaz": "トパーズ",
        "amethyst": "アメジスト",
        "agate": "メノウ",
        "jade": "ヒスイ",
        "garnet": "ガーネット",
        "opal": "オパール",
        "jet": "黒玉",
        "obsidian": "黒曜石",
        "chrysoberyl": "金緑石",
        "citrine": "シトリン",
        "jasper": "碧玉",
        "quartz": "石英",
        "rock crystal": "水晶",
        "fluorite": "蛍石",
        "luckstone": "幸運の石",
        "loadstone": "重い石",
        "touchstone": "試金石",
        "flint": "火打石",
        "rock": "岩",
        "glass": "屑ガラス",
        "gold piece": "金貨",

        // Artifacts
        "Excalibur": "エクスカリバー",
        "Stormbringer": "ストームブリンガー",
        "Mjollnir": "ミョルニル",
        "Cleaver": "クリーヴァー",
        "Grimtooth": "グリムトゥース",
        "Orcrist": "オルクリスト",
        "Sting": "スティング",
        "Magicbane": "マジックバイン",
        "Frost Brand": "フロストブランド",
        "Fire Brand": "ファイアブランド",
        "Dragonbane": "ドラゴンベイン",
        "Demonbane": "デーモンベイン",
        "Werebane": "ウェアベイン",
        "Grayswandir": "グレイスワンディール",
        "Giantslayer": "ジャイアントスレイヤー",
        "Ogresmasher": "オウガスマッシャー",
        "Trollsbane": "トロールズベイン",
        "Vorpal Blade": "ヴォーパルブレード",
        "Snickersnee": "スニッカースニー",
        "Sunsword": "サンソード",
        "The Orb of Detection": "探索の宝珠",
        "The Heart of Ahriman": "アーリマンの心臓",
        "The Sceptre of Might": "力の笏",
        "The Staff of Aesculapius": "アスクレピオスの杖",
        "The Magic Mirror of Merlin": "マーリンの魔法の鏡",
        "The Eyes of the Overworld": "異界の眼",
        "The Mitre of Holiness": "聖なる冠",
        "The Longbow of Diana": "ダイアナの長弓",
        "The Master Key of Thievery": "盗みのマスターキー",
        "The Tsurugi of Muramasa": "村正のツルギ",
        "The Platinum Yendorian Express Card": "プラチナ・イェンダー・エクスプレスカード",
        "The Orb of Fate": "運命の宝珠",
        "The Eye of the Aethiopica": "エチオピカの眼",

        // その他
    };

}

function nhMessage_pattern_items() {
    return [
        // フレーズパターン（再帰翻訳用）
        {
            pattern: /^(.*) corpse$/,
            replace: "$1の屍"
        },
        {
            pattern: /^a corpse of (.*)$/,
            replace: "$1の死体"
        },
        {
            pattern: /^(.*) statue$/,
            replace: "$1の像"
        },
        {
            pattern: /^a statue of (.*)$/,
            replace: "$1の像"
        },
        {
            pattern: /^(.*) egg$/,
            replace: "$1の卵"
        },
        {
            pattern: /^(.*) scroll$/,
            replace: "$1の巻物"
        },
        {
            pattern: /^(.*) potion$/,
            replace: "$1のポーション"
        },
        {
            pattern: /^(.*) wand$/,
            replace: "$1の杖"
        },
        {
            pattern: /^(.*) ring$/,
            replace: "$1の指輪"
        },
        {
            pattern: /^(.*) spellbook$/,
            replace: "$1の魔導書"
        },
        {
            pattern: /^potion of (.*)$/,
            replace: "$1のポーション"
        },
        {
            pattern: /^scroll of (.*)$/,
            replace: "$1の巻物"
        },
        {
            pattern: /^wand of (.*)$/,
            replace: "$1の杖"
        },
        {
            pattern: /^ring of (.*)$/,
            replace: "$1の指輪"
        },
        {
            pattern: /^spellbook of (.*)$/,
            replace: "$1の魔導書"
        },
        {
            pattern: /^(.*) (human|elf|dwarf|gnome|orc)$/,
            replace: "$1の$2"
        },
    ]
}
