function nhMessage_jp() {
    return [
        "キャラクターの種族、役割、性別、属性を選んであげましょうか？ [ynaq]",

        "    天地創造の後、残酷な神モロクは",
        "    創造主マルドゥクの権威に反逆した。",
        "    モロクはマルドゥクから",
        "    神々の最も強力な遺物であるイェンドールの護符を盗み、",
        "    それをゲヘナの暗い空洞に隠した。",
        "    そして今、彼はそこに潜み、時を待っている",

        "注意！もう戻れないぞ！まだ登るのか？",
        "所持品を確認したいか？",
        "自分の能力を見たいか？",
        "倒したクリーチャーの記録を見たいか？",
        "自分の行動を見たいか？",
        "ダンジョンの概要を見たいか？",

        "チュートリアルに入ります。",
        "床に何かが刻まれています。",
        "You read: \"8 2 4 6 で上下左右に移動\".",
        "You read: \"7 9 1 3 で斜め移動\".",
        "You read: \"一部のアクションは、成功するまでに複数回試す必要がある場合があります\".",
        "You read: \"ドアの中に入り込んで開ける\".",
        "You read: \"'c' でドアを閉める\".",
        "You read: \"注：チュートリアル以外では、Space(オリジナルではCtrlキー)の組み合わせは '^D' のようにキャレットで始まります\".",
        "You read: \"このドアは施錠されています。「k」 でキックしましょう\".",
        "(ヒント: どうしても入りたい場合は、先頭に 'm' を付けてステップインしてください。)",
        "You read: \"マップを ';' で調べて、終わったら ESC を押してください\".",
        "You read: \"'s' を使って秘密の扉を探してください\".",
        "You read: \"この扉の向こうには暗い廊下があります\".",
        "You read: \"あなたのすぐそばに4つの罠があります！探してください。\".",
        "You read: \"一部の罠は「u」で解除できます\".",
        "You read: \"「,」でアイテムを拾います\".",
        "You read: \"「W」で鎧を着ます\".",
        "You read: \"「w」で武器を振り回します\".",
        "You read: \"モンスターにぶつかって攻撃します\".",
        "You read: \"これで基本は分かりました。魔法のポータルからチュートリアルを終了できます。\".",
        "You read: \"チュートリアルを終了するには、このポータルに入りましょう\".",
        "You read: \"岩に向かって移動することで岩を押します\".",
        "You read: \"「T」で鎧を脱ぎます\".",
        "You read: \"一部のアイテムの説明はシャッフルされており、ゲームごとに異なります\".",
        "You read: \"この巻物を拾い、'r'で読み、もう一度鎧を脱いでみてください\".",
        "You read: \"重荷を背負うことは避けましょう。重荷は動きを遅くします\".",
        "You read: \"「d」でアイテムを落とします\".",
        "You read: \"アイテムスロットの文字の前に数字を付けることで、スタックの一部を落とします\".",
        "You read: \"「t」でアイテムを投げます\".",
        "You read: \"岩などのミサイルは、ランチャー等の適切な場所から発射するとより効果的です\".",
        "You read: \"スリングを使う\".",
        "You read: \"装備したランチャーでミサイルを発射するには「f」キーを使用します\".",
        "You read: \"「.」で1ターン待つことができます\".",
        "You read: \"発射すると矢筒からアイテムが発射されます。矢筒にアイテムを入れるには「Q」キーを使用します\".",
        "You read: \"コンテナからアイテムを拾うには「l」キーを使用します\".",
        "You read: \"コンテナは「Alt-T」キーで空にすることもできます\".",
        "You read: \"魔法の杖は「z」キーで使用します\".",
        "You read: \"もう一つの魔法のポータル、このチュートリアルから抜け出す方法\".",
        "通常のプレイを再開します。",

        "壁だ。",
        "ドアが開く。",
        "このドアは鍵がかかっている。",
        "どの方向？ ",
        "ドアを蹴ると、ガチャンと開いた！",
        "ここに壊れたドアがある。",
        "隠し扉を見つけた。",
        "ドアが抵抗する！",
        "硬い石だ。",
        "なんて変な方向なんだ！",
        "バタン！！",
        "ドスン！！",
        "ガチャン！",
        "本当にあのキーキー鳴る板の上に乗るの？",
        "本当にあの魔法のポータルに入るの？",
        "魔法のポータルを起動した！",
        "Resetting time to move #1.",
        "ここにダンジョンから上へ上がる階段がある。",
        "ここに階段があります。",
        "階段を降ります。",
        "階段を上ります. ",

        "ガスの雲が眠りに包んだ！",
        "あなたは目覚めた。",
        "あなたは蜘蛛の巣につまずきました！",
        "あなたは自分自身を解き放ちました。",
        "あなたは大変な努力をして岩を動かしました。",
        "あなたは岩を動かそうとしましたが、無駄でした。",
        "しかし、あなたは小さな隙間に身を潜めることができます。",
        "あなたはここに岩が見えます。",
        "あなたは格子を通り抜けることはできません。",
        "それは木です。",

        "あなたはその物を持っていません。",
        "気にしないでください。",

        "水たまりに落ちた！",
        "石のように沈んだ。",
        "水から這い出そうとした。",
        "ふぅ！危なかった。",
        "水の壁に飛び込んだ！",

        "本当にあの睡眠ガストラップに足を踏み入れるの？",
        "あなたはクモの巣に張り付いている。",
        "本当にそのクモの巣に足を踏み入れるのか？",
        "あなたはクモの巣から逃れた。",

        "ここに何かがある：",
        "痛い！ 痛すぎる！",
        "右足がキックできる状態ではありません。",
        "足の調子が良くなった。",
        "ここには床に何かの文字が焼き付けられている。",
        "食べるものが何もありません。",
        "自動拾い：ON（全オブジェクト）",
        "コアダンプしました。",
        "地面に何かが刻まれている。",
        "移動キーの前に「5」を付けることで走ることができます",
        "「_」でレベル内を移動（トラベル）します",
        "どこへ移動（トラベル）したいですか？",
        "(説明を表示するには '?' を入力してください)",
        "カーソルを目的地に移動してください：",
        "部屋の床",
        "壁（移動経路なし）",
        "閉じたドア",
        "未探索エリア（移動経路なし）",
        "ここには拾うものが何もありません。",
        "あなたは既に素手です。",
        "あなたの手には何もありません。",
        "あなたの左手には何もありません。",
        "あなたは素手です。",
        "予備の武器が準備されていません。",
        "二刀流での戦闘を開始します。",
        "自動拾い：OFF",
        "どちらの薬指ですか？ 右(R) それとも 左(L)？",
        "あなたは宙に浮き始めた！",
        "ここに溶岩がある。",
        "堅い地面の上に戻った。",
        "あなたは静かに床に降り立った。",
        "アクセサリーも鎧も身に着けていません。",
        "飲むものが何もありません。",
        "建設中（実装中）",
        "呪文詠唱",
        "残念ながら、呪文を唱えるためのエネルギーが足りません。",
        "「,」で魔導書を拾いましょう",
        "通り抜けられない？ 荷物が重すぎます。",
        "足元の落とし戸が開いた！",
        "ここに上り階段がある。",
        "このコマンドでは回数指定はできません。",
        "支払いを受け取る店主がここにはいないようです。",
        "「>」で階段を下ります",
        "隠し扉を見つけた！",
        "あなたはルーン文字を暗記し始めた。",
        "まだその呪文を唱えるためのエネルギーが足りません。",
        "ふーむ、チェストには鍵がかかっているようだ。",
        "パトロール中の衛兵の足音が聞こえる。",
        "堀",
        "あなたは虚空を蹴った。",
        "誰かが金貨を数えている音が聞こえる。",
        "二重の走行プレフィックス、キャンセルされました。",
        "埃の中に何かが書かれている。",
        "あなたは今、呪文を一つも知りません。",
        "店引き（万引き犯）を罵る声が聞こえる。",
        "ドアが開く音が聞こえた。",
        "そのドアは閉じている。",
        "アイテムを比較することで、それらについてより詳しく知ることができます。",
        "本当に保存しますか？",
        "保存中...",
        "セーブファイルを復元中...",

        "溶岩の中に落ちた！",
        "あなたは焼き尽くされた...",
        "「5」プレフィックスの後には移動コマンドを続けてください。",
        "プログラムが混乱しています！（保存してリロードすると直るかもしれません）",
        "これらのメッセージを devteam@nethack.org に報告してください。",
        "あるいは、ローカルサポートに連絡してください：NetHack Wasm Port",
        "アイテムの存在を感知した。",
        "カーソルを対象に移動してください：",

        "ふーむ、大きな箱には鍵がかかっているようだ。",
        "ナイアデスが水しぶきを上げる音が聞こえる。",

        "あなたはザップされた！",
        "岩の向こう側にモンスターの気配がする。",
        "おそらくそれが、岩を動かせない理由だろう。",

        "遠吠えが聞こえる。",
        "あなたはガスの雲に包まれた！",
        "それを身につけるのは愚かなことだ。",
        "本当にその穴に足を踏み入れるのか？",
        "あなたは穴から脱出した。",
        "ここに噴水がある。",
        "ロックピックで鍵を開けますか？",
        "鍵開けに成功した。",
        "岩が砕ける音が聞こえる。",
        "あなたは死んだ...",

        "愚かな動きだ！ 筋肉を違えた。",
        "ここにシンク（流し台）がある。",
        "ゴクゴクという音が聞こえる。",
        "ここの床に落書きがある。",
        "ここを下りることはできません。",
        "杖の魔法があなたに当たった！",

        "あなたは別の場所に実体化した！",
        "遠くで何かの物音が聞こえる。",
        "一瞬、閃光で目がくらんだ！",
        "耳をつんざくような咆哮が聞こえた！",
        "待て！ そこに目に見えない何かがいる！",
        "水が沸き立つ音が聞こえる。",
        "突然、体がとても熱くなった！",
        "何かの物音が聞こえる。",
        "ここに戸口がある。",
        "再び見えるようになった。",
        "本当にその魔法の罠に足を踏み入れるのか？",
        "再び聞こえるようになった。",
        "外れた！",
        "噛み付いた！",
        "あなたはそれを倒した！",

        "あなたは空腹で失神した。",
        "意識が戻った。",
        "再び動けるようになった。",
        "巨石を押すための力が足りない。",
        "床に手が届かない。",
        "それは読むものではありません。",
        "床に手が届きません。",
        "あなたは鎧を身に着けていません。",
        "本当にその魔法のポータルに浮かんで入るの？",
        "荷物が重いため、動きが少し遅くなっています。",
        "身軽になり、動きがスムーズになった。",
        "巻物を読むと、それは消え去った。",

        "ランプがついた。",
        "荷物のバランスを整えた。移動が困難だ。",
        "隠し通路を見つけた。",
        "階段から転げ落ちた！",
        "空腹を感じ始めた。",
        "着替えを終えた。",
        "金貨の上に水が落ちる音が聞こえる。",
        "粗末な短剣が当たった。",
        "体が弱ってきたと感じる。",
        "オークのゾンビを攻撃した。",
        "この食べ物は最高だ！",
        "食べるのをやめた。",

        "天井の落とし戸が開き、岩が頭に落ちてきた！",
        "本当にその落石トラップに足を踏み入れるの？",
        "墓石に何かが刻まれている。",
        "ブレスケアをしてくれませんか？",

        "モンスター、アイテム、または場所を選択してください。",
        "モンスター、アイテム、または場所にカーソルを移動してください：",
        "壁",
        "未探索エリア",
        "部屋の暗い部分",
        "彫り物",
        "被害を免れた。",
        "ドアを蹴ると、粉々に砕け散った！",
        "ダメです。呪われています。",
        "他に身に着けるものがありません。",
        "準備された弾薬がありません。",
        "げっ！ 腐った食べ物だ！",
        "岩（移動経路なし）",
        "廊下",
        "戸口",
        "壊れたドア",
        "泡立つ何か",

        "岩",
        "照らされた廊下",
        "脅威を感じる。",
        "奇妙な口笛の音を出した。",

        "深い穴に落ちた！",
        "背筋が凍るような感覚が走った！",
        "すでにモンスターを見つけています。「m」プレフィックスを使えば再探索できます。",
        "忍び寄る手がかりを感じた！",
        "財布が軽くなった気がする。",

        "レジのチャイムが聞こえる。",
        "ゴボゴボという音が聞こえる。",
        "「塗油する(v.t.)：王やその他の高官に油を塗ること」",
        "「すでに十分に滑りやすい」",
        "        [ 悪魔の辞典, アンブローズ・ビアス ]",
        "矢が当たった。",
        "足が床に凍り付いた！",

        "本当に終了しますか？",
        "魔除けを身に着けていません。",
        "それは飲むものではありません。",
        "立ち止まってバラの香りを嗅ぐのを忘れないでください",
        "力が溢れてくる！",
        "熱心に訓練したに違いありません。",
        "体が丈夫になった！",
        "健康的な生活を送っていたに違いありません。",
        "あなたはまだ弱っています。",

        "あなたはよろめいた...",
        "少し足元がしっかりしてきた。",
        "発射の準備ができるものが何もありません。",
        "開いたドア",

        "Is this a dagger which I see before me,",
        "The handle toward my hand? Come, let me clutch thee.",
        "I have thee not, and yet I see thee still.",
        "Art thou not, fatal vision, sensible",
        "To feeling as to sight? or art thou but",
        "A dagger of the mind, a false creation,",
        "Proceeding from the heat-oppressed brain?",
        "I see thee yet, in form as palpable",
        "As this which now I draw.",
        "        [ Macbeth, by William Shakespeare ]",
        "You smite the yellow mold.",
        "That ammunition is already readied!",
        "Confess my sins to god?  Which one?",
        "You feel better.",
        "Really step into that pit?",
        "You fall into a pit!",
        "There is a grave here.",
        "You stagger under your heavy load.  Movement is very hard.",
        "You don't have enough stamina to move.",
        "You hear scratching noises.",
        "You don't have anything else to put on.",
        "Ouch!  You bump into a door.",
        "Refresh your memory anyway?",

        "Loot in what direction?",
        "You don't find anything there to loot.",
        "A map coalesces in your mind!",
        "When the gods want to punish you, they answer your prayers.",
        "fountain",
        "grave",
        "You feel feverish.",
                
        "You are already wearing some armor.",
        "Orcs, bipeds with a humanoid appearance, are related to the",
        "goblins, but much bigger and more dangerous.  The average",
        "is only moderately intelligent, has broad, muscled shoulders,",
        "a short neck, a sloping forehead and a thick, dark fur.",
        "Their lower eye-teeth are pointing forward, like a boar's.",
        "Female orcs are more lightly built and bare-chested.  Not",
        "needing any clothing, they do like to dress in variegated",
        "apparels.  Suspicious by nature, orcs live in tribes or",
        "hordes.  They tend to live underground as well as above",
        "ground (but they dislike sunlight).  Orcs can use all weapons,",
        "tools and armours that are used by men.  Since they don't have",
        "the talent to fashion these themselves, they are constantly",
        "hunting for them.  There is nothing a horde of orcs cannot",
        "use.",
        "        [ het Boek van de Regels; Het Oog des Meesters ]",

        "You finish taking off your mail.",
        "The door closes.",

        "If you start from scratch, cooking tripe is a long-drawn-out",
        "affair.  Fresh whole tripe calls for a minimum of 12 hours of",
        "cooking, some time-honored recipes demanding as much as 24.",
        "To prepare fresh tripe, trim if necessary.  Wash it thoroughly,",
        "soaking overnight, and blanch, for 1/2 hour in salted water.",
        "Wash well again, drain and cut for cooking.  When cooked, the",
        "texture of tripe should be like that of soft gristle.  More",
        "often, alas, because the heat has not been kept low enough,",
        "it has the consistency of wet shoe leather.",
        "        [ Joy of Cooking, by I Rombauer and M Becker ]",

        "A metal of characteristic yellow colour, the most precious",
        "metal used as a common commercial medium of exchange.  Symbol,",
        "Au; at. no. 79; at. wt. 197.2.  It is the most malleable",
        "and ductile of all metals, and very heavy (sp. gr., 19.3).",
        "It is quite unalterable by heat, moisture, and most",
        "corrosive agents, and therefore well suited for its use in",
        "coin and jewelry.",
        "     [ Webster's New International Dictionary",
        "          of the English Language, Second Edition ]",

        "The little girl stood on tip-toe and picked one of the nicest",
        "and biggest lunch-boxes, and then she sat down upon the ground",
        "and eagerly opened it.  Inside she found, nicely wrapped in",
        "white papers, a ham sandwich, a piece of sponge-cake, a pickle,",
        "a slice of new cheese and an apple.  Each thing had a separate",
        "stem, and so had to be picked off the side of the box; but",
        "Dorothy found them all to be delicious, and she ate every bit",
        "of luncheon in the box before she had finished.",
        "        [ Ozma of Oz, by L. Frank Baum ]",

        'But I asked why not keep it and let the hen sit on it till it',
        'hatched, and then we could see what would come out of it.',
        `"Nothing good, I'm certain of that," Mom said.  "It would`,
        "probably be something horrible.  But just remember, if it's a",
        "crocodile or a dragon or something like that, I won't have it",
        'in my house for one minute."',
        "        [ The Enormous Egg, by Oliver Butterworth ]",

        '"You know salmon, Sarge," said Nobby.',
        '"It is a fish of which I am aware, yes."',
        '"You know they sell kind of slices of it in tins..."',
        '"So I am given to understand, yes."',
        '"Weell...how come all the tins are the same size?  Salmon',
        'gets thinner at both ends."',
        '"Interesting point, Nobby.  I think-"',
        "        [ Soul Music, by Terry Pratchett ]",

        "And I was gazing on the surges prone,",
        "With many a scalding tear and many a groan,",
        "When at my feet emerg'd an old man's hand,",
        "Grasping this scroll, and this same slender wand.",
        "I knelt with pain--reached out my hand--had grasp'd",
        "Those treasures--touch'd the knuckles--they unclasp'd--",
        "I caught a finger: but the downward weight",
        "O'erpowered me--it sank. Then 'gan abate",
        "The storm, and through chill aguish gloom outburst",
        "The comfortable sun. I was athirst",
        "To search the book, and in the warming air",
        "Parted its dripping leaves with eager care.",
        "Strange matters did it treat of, and drew on",
        "My soul page after page, till well-nigh won",
        "Into forgetfulness; when, stupefied,",
        "I read these words, and read again, and tried",
        "My eyes against the heavens, and read again.",
        "        [ Endymion, by John Keats ]",

        "mail turns to dust and falls to the stairs!",

        "Closed for inventory",
        '"How dare you break my door?"',
        "Do you want to see what you had when you died?",        
        
        "There is an open door here.",

        "Faustus: Come on Mephistopheles.  What shall we do?",
        "Mephistopheles: Nay, I know not.  We shall be cursed with bell,",
        "book, and candle.",
        "Faustus: How?  Bell, book, and candle, candle, book, and bell,",
        "Forward and backward, to curse Faustus to hell.",
        "Anon you shall hear a hog grunt, a calf bleat, and an ass bray,",
        "Because it is Saint Peter's holy day.",
        "(Enter all the Friars to sing the dirge)",
        "        [ Doctor Faustus and Other Plays, by Christopher Marlowe ]",

        "You don't find anything here to loot.",

        "In World War II, Britain's air ministry spread the word that",
        "a diet of these vegetables helped pilots see Nazi bombers",
        "attacking at night.  That was a lie intended to cover the real",
        "matter of what was underpinning the Royal Air Force's successes:",
        "Airborne Interception Radar, also known as AI. ... British",
        "Intelligence didn't want the Germans to find out about the",
        "superior new technology helping protect the nation, so they",
        "created a rumor to afford a somewhat plausible-sounding",
        "explanation for the sudden increase in bombers being shot down.",
        "... The disinformation was so persuasive that the English public",
        "took to eating carrots to help them find their way during the",
        "blackouts.",
        "        [ Urban Legends Reference Pages ]",

        "NEWTONIAN, adj.  Pertaining to a philosophy of the universe",
        "invented by Newton, who discovered that an apple will fall",
        "to the ground, but was unable to say why.  His successors",
        "and disciples have advanced so far as to be able to say",
        "when.",

        "That is a silly thing to zap.",

        "POTABLE, n.  Suitable for drinking.  Water is said to be",
        "potable; indeed, some declare it our natural beverage,",
        "although even they find it palatable only when suffering",
        "from the recurrent disorder known as thirst, for which it",
        "is a medicine.  Upon nothing has so great and diligent",
        "ingenuity been brought to bear in all ages and in all",
        "countries, except the most uncivilized, as upon the",
        "invention of substitutes for water.  To hold that this",
        "general aversion to that liquid has no basis in the",
        "preservative instinct of the race is to be unscientific --",
        "and without science we are as the snakes and toads.",
        "Jack Burton:  What's in the flask, Egg?  Magic potion?",
        "   Egg Shen:  Yeah.",
        "       Jack:  I thought so, good.  What do we do?  Drink it?",
        "        Egg:  Yeah.",
        "       Jack:  Good, I thought so.",
        "     [later]",
        "       Jack:  This does what again, exactly?",
        "        Egg:  Huge buzz!  [drinks]  Oh good!  See things no",
        "              one else can see, do things no one else can do.",
        "        [ Big Trouble in Little China, directed by",
        "          John Carpenter, written by Gary Goldman &",
        "          David Z. Weinstein, adaptation by W. D. Richter ]",



    ];
}

