/**
 * 固有名詞や単語単位の翻訳辞書
 * 再帰翻訳で使用されます。
 */
function nhMessage_entity() {
    return {
        // 性別・神
        "god": "神",
        "goddess": "女神",
        "Her": "彼女",
        "Him": "彼",
        "Her.": "彼女。",
        "Him.": "彼。",

        // 神の名前
        "The Lady": "レディ",
        "Amaterasu Omikami": "天照大御神",
        "Quetzalcoatl": "ケツァルコアトル",
        "Lugh": "ルー",
        "Venus": "ヴィーナス",
        "Anu": "アヌ",
        "Hermes": "ヘルメス",
        "Set": "セト",
        "Tyr": "テュール",
        "Chih Sung-tzu": "赤松子",
        "Mars": "マーズ",
        "Camaxtli": "カマシュトリ",
        "Kos": "コス",
        "Thoth": "トート",
        "Ishtar": "イシュタル",
        "Huan Ti": "黄帝",
        "Mitora": "ミトラ",
        "Anhur": "アンフル",
        "Athena": "アテナ",
        "Offler": "オファーラー",
        "Poseidon": "ポセイドン",
        "Crom": "クロム",

        // 職業（サンプル）
        "Rambler": "放浪者",
        "Hatamoto": "旗本",
        "Digger": "掘削者",
        "Gallant": "騎士",
        "Tenderfoot": "初心者",
        "Troglodyte": "原始人",
        "Rhizotomist": "薬草取り",
        "Plunderer": "掠奪者",
        "Plunderess": "掠奪者",
        "Stripling": "若造",
        "Candidate": "候補生",
        "Footpad": "追剥",
        "Evoker": "召喚師",
        "Aspirant": "志願者",

        // チュートリアル・その他
        "Move around with 4 2 8 6": "8 2 4 6 で上下左右に移動",
        "Move diagonally with 1 9 3 7": "7 9 1 3 で斜め移動",

        "an E note": "ミの音",
        "an F note": "ファの音",
        "an A note": "ラの音",
        "a B note": "シの音",
        "a C note": "ドの音",
        "a G sharp": "Gシャープの音",
        "an F sharp": "Fシャープの音",
        "a B flat": "Bフラットの音",

        "pool of water": "水たまり",
        "molten lava": "溶けた溶岩",
        "wall of lava": "溶岩の壁",
        "wall of water": "水の壁",

        "You stop in front of the door.": "You stop in front of the door.",
        "Wrong secret": "Wrong secret",
        "Use 'e' to eat edible things": "Use 'e' to eat edible things",
        "You can run by prefixing a movement key with '5'": "You can run by prefixing a movement key with '5'",
        "Travel across the level with '_'": "Travel across the level with '_'",
        "Swap weapons quickly with 'x'": "Swap weapons quickly with 'x'",
        "Use 'X' to use two weapons at once": "Use 'X' to use two weapons at once",
        "Put on accessories with 'P'": "Put on accessories with 'P'",
        "Remove accessories with 'R'": "Remove accessories with 'R'",
        "You \"quaff\" potions with 'q'":"You \"quaff\" potions with 'q'",
        "Pick up the spellbook with ','":"Pick up the spellbook with ','",
        "Read the spellbook with 'r'":"Read the spellbook with 'r'",
        "Use 'Z' to cast a spell": "Use 'Z' to cast a spell",
        "Use '<' to go up the stairs":"Use '<' to go up the stairs",
        "Use '>' to go down the stairs":"Use '>' to go down the stairs",

        //pet/Monst
        "kitten":"子猫",
        "lichen":"地衣類",
        "sewer rat":"下水ネズミ",
        "newt":"イモリ",
        "jackal":"ジャッカル",
        "grid bug":"グリッドバグ",
        "brown mold":"茶色カビ",
        "goblin":"ゴブリン",
        "little dog":"子犬",
        "fox":"キツネ",
        "dwarf":"ドワーフ",
        "gnome":"ノーム",
        "giant rat":"大ネズミ",
        "it":"それ",
        "hobbit":"ホビット",
        "red mold":"赤カビ",
    };
}
