function nhMessage_jp() {
    return [
        "キャラクターの種族、役割、性別、属性を選んであげましょうか？ [ynaq]",

        "It is written in the Book of The Lady:",
        "",
        "    天地創造の後、残酷な神モロクは",
        "    創造主マルドゥクの権威に反逆した。",
        "    モロクはマルドゥクから",
        "    神々の最も強力な遺物であるイェンドールの護符を盗み、",
        "    それをゲヘナの暗い空洞に隠した。",
        "    そして今、彼はそこに潜み、時を待っている",

        "Your goddess The Lady seeks to possess the Amulet, and with it",
        "to gain deserved ascendance over the other gods.",
        "You, a newly trained Rambler, have been heralded",
        "from birth as the instrument of The Lady.  You are destined",
        "to recover the Amulet for your deity, or die in the",
        "attempt.  Your hour of destiny has come.  For the sake",
        "of us all:  Go bravely with The Lady!",
        "[The Lady has chosen you to recover the Amulet of Yendor for Her.]",

        "注意！もう戻れないぞ！まだ登るのか？ yn",
        "所持品を確認したいか？ ynq",
        "自分の能力を見たいか？ ynq",
        "倒したクリーチャーの記録を見たいか？ ynq",
        "自分の行動を見たいか？ ynq",
        "ダンジョンの概要を見たいか？ ynq",
        "Cannot open file xlogfile.  Is NetHack installed correctly?",

        "It is written in the Book of 天照大御神:",
        "Your goddess Amaterasu Omikami seeks to possess the Amulet, and with it",
        "You, a newly trained 旗本, have been heralded",
        "from birth as the instrument of 天照大御神.  You are destined",
        "of us all:  Go bravely with 天照大御神!",
        "[天照大御神 has chosen you to recover the Amulet of Yendor for Her.]",
        
        "It is written in the Book of Quetzalcoatl:",
        "Your god Quetzalcoatl seeks to possess the Amulet, and with it",
        "You, a newly trained Digger, have been heralded",
        "from birth as the instrument of Quetzalcoatl.  You are destined",
        "of us all:  Go bravely with Quetzalcoatl!",
        "[Quetzalcoatl has chosen you to recover the Amulet of Yendor for Him.]",

        "It is written in the Book of Lugh:",
        "Your god Lugh seeks to possess the Amulet, and with it",
        "You, a newly trained Gallant, have been heralded",
        "from birth as the instrument of Lugh.  You are destined",
        "of us all:  Go bravely with Lugh!",
        "[Lugh has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Venus:",
        "Your goddess Venus seeks to possess the Amulet, and with it",
        "You, a newly trained Tenderfoot, have been heralded",
        "from birth as the instrument of Venus.  You are destined",
        "of us all:  Go bravely with Venus!",
        "[Venus has chosen you to recover the Amulet of Yendor for Her.]",
        
        "It is written in the Book of Anu:",
        "Your god Anu seeks to possess the Amulet, and with it",
        "You, a newly trained Troglodyte, have been heralded",
        "from birth as the instrument of Anu.  You are destined",
        "of us all:  Go bravely with Anu!",
        "[Anu has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Hermes:",
        "Your god Hermes seeks to possess the Amulet, and with it",
        "You, a newly trained Rhizotomist, have been heralded",
        "from birth as the instrument of Hermes.  You are destined",
        "of us all:  Go bravely with Hermes!",
        "[Hermes has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Set:",
        "Your god Set seeks to possess the Amulet, and with it",
        "You, a newly trained Plunderer, have been heralded",
        "from birth as the instrument of Set.  You are destined",
        "of us all:  Go bravely with Set!",
        "[Set has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Tyr:",
        "Your god Tyr seeks to possess the Amulet, and with it",
        "You, a newly trained Stripling, have been heralded",
        "from birth as the instrument of Tyr.  You are destined",
        "of us all:  Go bravely with Tyr!",
        "[Tyr has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Chih Sung-tzu:",
        "Your god Chih Sung-tzu seeks to possess the Amulet, and with it",
        "You, a newly trained Candidate, have been heralded",
        "from birth as the instrument of Chih Sung-tzu.  You are destined",
        "of us all:  Go bravely with Chih Sung-tzu!",
        "[Chih Sung-tzu has chosen you to recover the Amulet of Yendor for Him.]",
        
        "It is written in the Book of Mars:",
        "Your god Mars seeks to possess the Amulet, and with it",
        "from birth as the instrument of Mars.  You are destined",
        "of us all:  Go bravely with Mars!",
        "[Mars has chosen you to recover the Amulet of Yendor for Him.]",
        "It is written in the Book of Camaxtli:",
        "Your god Camaxtli seeks to possess the Amulet, and with it",
        "from birth as the instrument of Camaxtli.  You are destined",
        "of us all:  Go bravely with Camaxtli!",
        "[Camaxtli has chosen you to recover the Amulet of Yendor for Him.]",

        "It is written in the Book of Kos:",
        "Your god Kos seeks to possess the Amulet, and with it",
        "You, a newly trained Footpad, have been heralded",
        "from birth as the instrument of Kos.  You are destined",
        "of us all:  Go bravely with Kos!",
        "[Kos has chosen you to recover the Amulet of Yendor for Him.]",
        
        "You, a newly trained Plunderess, have been heralded",
        
        "チュートリアルに入ります。",
        "床に何かが刻まれています。",
        "You read: \"Move around with h j k l\".",
        "You read: \"Move diagonally with b u n y\".",
        "You read: \"一部のアクションは、成功するまでに複数回試す必要がある場合があります\".",
        "You read: \"ドアの中に入り込んで開ける\".",
        "You read: \"'c' でドアを閉める\".",
        "You read: \"注：チュートリアル以外では、Ctrlキーの組み合わせは '^D' のようにキャレットで始まります\".",
        "You read: \"このドアは施錠されています。」 Ctrl+D でキックしましょう\".",
        "(ヒント: どうしても入りたい場合は、先頭に 'm' を付けてステップインしてください。)",
        "You read: \"マップを ';' で調べて、終わったら ESC を押してください\".",
        "You read: \"'s' を使って秘密の扉を探してください\".",
        "You read: \"この扉の向こうには暗い廊下があります\".",
        "You read: \"あなたのすぐそばに4つの罠があります！探してください。\".",
        "You read: \"一部の罠は「M-u」で解除できます\".",
        "You read: \"「,」でアイテムを拾います\".",
        "You read: \"「W」で鎧を着ます\".",
        "You read: \"「w」で武器を振り回します\".",
        "You read: \"モンスターにぶつかって攻撃します\".",
        "You read: \"これで基本は分かりました。魔法のポータルからチュートリアルを終了できます。\".",
        "You read: \"チュートリアルを終了するには、このポータルに入りましょう\".",
        "You read: \"岩に向かって移動することで岩を押します\".",
        "You read: \"「T」で鎧を脱ぎます\".",
        "You read: \"一部のアイテムの説明はシャッフルされており、ゲームごとに異なります\".",
        "You read: \"この巻物を拾い、'r'で読み、もう一度鎧を脱いでみてください\".",
        "You read: \"重荷を背負うことは避けましょう。重荷は動きを遅くします\".",
        "You read: \"「d」でアイテムを落とします\".",
        "You read: \"アイテムスロットの文字の前に数字を付けることで、スタックの一部を落とします\".",
        "You read: \"「t」でアイテムを投げます\".",
        "You read: \"岩などのミサイルは、ランチャー等の適切な場所から発射するとより効果的です\".",
        "You read: \"スリングを使う\".",
        "You read: \"装備したランチャーでミサイルを発射するには「f」キーを使用します\".",
        "You read: \"「.」で1ターン待つことができます\".",
        "You read: \"発射すると矢筒からアイテムが発射されます。矢筒にアイテムを入れるには「Q」キーを使用します\".",
        "You read: \"コンテナからアイテムを拾うには「M-l」キーを使用します\".",
        "You read: \"コンテナは「Alt-T」キーで空にすることもできます\".",
        "You read: \"魔法の杖は「z」キーで使用します\".",
        "You read: \"もう一つの魔法のポータル、このチュートリアルから抜け出す方法\".",
        "通常のプレイを再開します。",
        
        "壁だ。",
        "ドアが開く。",
        "このドアは鍵がかかっている。",
        "どの方向？ ",
        "ドアを蹴ると、ガチャンと開いた！",
        "ここに壊れたドアがある。",
        "隠し扉を見つけた。",
        "ドアが抵抗する！",
        "硬い石だ。",
        "なんて変な方向なんだ！",
        "バタン！！",
        "ドスン！！",
        "本当にあのキーキー鳴る板の上に乗るの？ yn",
        "本当にあの魔法のポータルに入るの？ yn",
        "魔法のポータルを起動した！",
        "Resetting time to move #1.",
        "ここにダンジョンから上へ上がる階段がある。",
        
        "あなたは水たまりに足を踏み入れないようにしました。",
        "あなたは溶けた溶岩に足を踏み入れないようにしました。",
        "あなたは溶岩の壁に足を踏み入れないようにしました。",
        "あなたの下の板が大きなラの音を鳴らしました。",
        "あなたの下の板が大きなミの音を鳴らしました。",
        "あなたの下の板が大きなファの音を鳴らしました。",
        "ガスの雲が眠りに包んだ！",
        "あなたは目覚めた。",
        "あなたは蜘蛛の巣につまずきました！",
        "あなたは自分自身を解き放ちました。",
        "あなたは大変な努力をして岩を動かしました。",
        "あなたは岩を動かそうとしましたが、無駄でした。",
        "しかし、あなたは小さな隙間に身を潜めることができます。",
        "あなたはここに岩が見えます。",
        "あなたは格子を通り抜けることはできません。",
        "それは木です。",

        "何を落としたいですか？ [*] ",
        "あなたはその物を持っていません。",
        "気にしないでください。",

        "It is written in the Book of Thoth:",
        "Your god Thoth seeks to possess the Amulet, and with it",
        "You, a newly trained Evoker, have been heralded",
        "from birth as the instrument of Thoth.  You are destined",
        "of us all:  Go bravely with Thoth!",
        "[Thoth has chosen you to recover the Amulet of Yendor for Him.]",
    
        "It is written in the Book of Ishtar:",
        "Your goddess Ishtar seeks to possess the Amulet, and with it",
        "from birth as the instrument of Ishtar.  You are destined",
        "of us all:  Go bravely with Ishtar!",
        "[Ishtar has chosen you to recover the Amulet of Yendor for Her.]",

        "水たまりに落ちた！",
        "石のように沈んだ。",
        "水から這い出そうとした。",
        "ふぅ！危なかった。",
        "水の壁に足を踏み入れないようにした。",
        "水の壁に飛び込んだ！",

        "本当にあの睡眠ガストラップに足を踏み入れるの？yn",
        "あなたの下の板が大きなドの音を鳴らしました。",
        "あなたの下の板が大きな G sharp の音を鳴らしました。",
        "あなたの下の板が大きな B flat の音を鳴らしました。",
        "あなたはクモの巣に張り付いている。",
    ];
}

