function nhMessage_jp() {
    return [
        "キャラクターの種族、役割、性別、属性を選んであげましょうか？ [ynaq]",

        "    天地創造の後、残酷な神モロクは",
        "    創造主マルドゥクの権威に反逆した。",
        "    モロクはマルドゥクから",
        "    神々の最も強力な遺物であるイェンドールの護符を盗み、",
        "    それをゲヘナの暗い空洞に隠した。",
        "    そして今、彼はそこに潜み、時を待っている",

        "注意！もう戻れないぞ！まだ登るのか？",
        "所持品を確認したいか？",
        "自分の能力を見たいか？",
        "倒したクリーチャーの記録を見たいか？",
        "自分の行動を見たいか？",
        "ダンジョンの概要を見たいか？",
        
        "チュートリアルに入ります。",
        "床に何かが刻まれています。",
        "You read: \"8 2 4 6 で上下左右に移動\".",
        "You read: \"7 9 1 3 で斜め移動\".",
        "You read: \"一部のアクションは、成功するまでに複数回試す必要がある場合があります\".",
        "You read: \"ドアの中に入り込んで開ける\".",
        "You read: \"'c' でドアを閉める\".",
        "You read: \"注：チュートリアル以外では、Space(オリジナルではCtrlキー)の組み合わせは '^D' のようにキャレットで始まります\".",
        "You read: \"このドアは施錠されています。「k」 でキックしましょう\".",
        "(ヒント: どうしても入りたい場合は、先頭に 'm' を付けてステップインしてください。)",
        "You read: \"マップを ';' で調べて、終わったら ESC を押してください\".",
        "You read: \"'s' を使って秘密の扉を探してください\".",
        "You read: \"この扉の向こうには暗い廊下があります\".",
        "You read: \"あなたのすぐそばに4つの罠があります！探してください。\".",
        "You read: \"一部の罠は「u」で解除できます\".",
        "You read: \"「,」でアイテムを拾います\".",
        "You read: \"「W」で鎧を着ます\".",
        "You read: \"「w」で武器を振り回します\".",
        "You read: \"モンスターにぶつかって攻撃します\".",
        "You read: \"これで基本は分かりました。魔法のポータルからチュートリアルを終了できます。\".",
        "You read: \"チュートリアルを終了するには、このポータルに入りましょう\".",
        "You read: \"岩に向かって移動することで岩を押します\".",
        "You read: \"「T」で鎧を脱ぎます\".",
        "You read: \"一部のアイテムの説明はシャッフルされており、ゲームごとに異なります\".",
        "You read: \"この巻物を拾い、'r'で読み、もう一度鎧を脱いでみてください\".",
        "You read: \"重荷を背負うことは避けましょう。重荷は動きを遅くします\".",
        "You read: \"「d」でアイテムを落とします\".",
        "You read: \"アイテムスロットの文字の前に数字を付けることで、スタックの一部を落とします\".",
        "You read: \"「t」でアイテムを投げます\".",
        "You read: \"岩などのミサイルは、ランチャー等の適切な場所から発射するとより効果的です\".",
        "You read: \"スリングを使う\".",
        "You read: \"装備したランチャーでミサイルを発射するには「f」キーを使用します\".",
        "You read: \"「.」で1ターン待つことができます\".",
        "You read: \"発射すると矢筒からアイテムが発射されます。矢筒にアイテムを入れるには「Q」キーを使用します\".",
        "You read: \"コンテナからアイテムを拾うには「l」キーを使用します\".",
        "You read: \"コンテナは「Alt-T」キーで空にすることもできます\".",
        "You read: \"魔法の杖は「z」キーで使用します\".",
        "You read: \"もう一つの魔法のポータル、このチュートリアルから抜け出す方法\".",
        "通常のプレイを再開します。",
        
        "壁だ。",
        "ドアが開く。",
        "このドアは鍵がかかっている。",
        "どの方向？ ",
        "ドアを蹴ると、ガチャンと開いた！",
        "ここに壊れたドアがある。",
        "隠し扉を見つけた。",
        "ドアが抵抗する！",
        "硬い石だ。",
        "なんて変な方向なんだ！",
        "バタン！！",
        "ドスン！！",
        "ガチャン！",
        "本当にあのキーキー鳴る板の上に乗るの？",
        "本当にあの魔法のポータルに入るの？",
        "魔法のポータルを起動した！",
        "Resetting time to move #1.",
        "ここにダンジョンから上へ上がる階段がある。",
        "ここに階段があります。",
        "階段を降ります。",
        "階段を上ります. ",
 
        "ガスの雲が眠りに包んだ！",
        "あなたは目覚めた。",
        "あなたは蜘蛛の巣につまずきました！",
        "あなたは自分自身を解き放ちました。",
        "あなたは大変な努力をして岩を動かしました。",
        "あなたは岩を動かそうとしましたが、無駄でした。",
        "しかし、あなたは小さな隙間に身を潜めることができます。",
        "あなたはここに岩が見えます。",
        "あなたは格子を通り抜けることはできません。",
        "それは木です。",

        "あなたはその物を持っていません。",
        "気にしないでください。",

        "水たまりに落ちた！",
        "石のように沈んだ。",
        "水から這い出そうとした。",
        "ふぅ！危なかった。",
        "水の壁に飛び込んだ！",

        "本当にあの睡眠ガストラップに足を踏み入れるの？",
        "あなたはクモの巣に張り付いている。",
        "本当にそのクモの巣に足を踏み入れるのか？",
        "あなたはクモの巣から逃れた。",

        "Things that are here:",
        "Ouch!  That hurts!",
        "Your right leg is in no shape for kicking.",
        "Your leg feels better.",
        "Some text has been burned into the floor here.",
        "You don't have anything to eat.",
        "Autopickup: ON, for all objects.",
        "Core dumped.",
        "Something is engraved here on the ground.",
        "You can run by prefixing a movement key with '5'",
        "Travel across the level with '_'",
        "Where do you want to travel to?",
        "(For instructions type a '?')",
        "Move cursor to the desired destination:",
        "floor of a room",
        "wall (no travel path)",
        "closed door",
        "unexplored area (no travel path)",
        "There is nothing here to pick up.",
        "You are already bare handed.",
        "Your hands are empty.",
        "Your left hand is empty.",
        "You are bare handed.",
        "You have no secondary weapon readied.",
        "You begin two-weapon combat.",
        "Autopickup: OFF.",
        "Which ring-finger, Right or Left?",
        "You start to float in the air!",
        "There is molten lava here.",
        "You are back over solid ground.",
        "You float gently to the floor.",
        "Not wearing any accessories or armor.",
        "You don't have anything to drink.",
        "UNDER CONSTRUCTION",
        "Spellcasting",
        "Unfortunately you don't have enough energy to cast spells.",
        "Pick up the spellbook with ','",
        "Can't get through?  You're carrying too much.",
        "A trap door opens up under you!",
        "There is a staircase up here.",
        "No count allowed with this command.",
        "There appears to be no shopkeeper here to receive your payment.",
        "Use '>' to go down the stairs",
        "You reveal a secret door!",
        "You begin to memorize the runes.",
        "You don't have enough energy to cast that spell yet.",
        "Hmmm, the chest turns out to be locked.",
        "You hear the footsteps of a guard on patrol.",
        "moat",
        "You kick at empty space.",
        "You hear someone counting gold coins.",
        "Double run prefix, canceled.",
        "Something is written here in the dust.",
        "You don't know any spells right now.",
        "You hear someone cursing shoplifters.",
        "You hear a door open.",
        "That door is closed.",
        "You learn more about your items by comparing them.",
        "Really save?",
        "Saving...",
        "Restoring save file...",

        "You fall into the molten lava!",
        "You burn to a crisp...",
        "The '5' prefix should be followed by a movement command.",
        "Program in disorder!  (Saving and reloading may fix this problem.)",
        "Please report these messages to devteam@nethack.org.",
        "Alternatively, contact local support: NetHack Wasm Port",
        "You detect the presence of objects.",
        "Move cursor to object:",

        "Hmmm, the large box turns out to be locked.",
        "You hear the splashing of a naiad.",
        
        "You get zapped!",
        "You hear a monster behind the boulder.",
        "Perhaps that's why you cannot move it.",

        "You hear distant howling.",
        "You are enveloped in a cloud of gas!",
        "That is a silly thing to put on.",
        "Really step into that hole?",
        "You escape a hole.",
        "There is a fountain here.",
        "Unlock it with your lock pick?",
        "You succeed in picking the lock.",
        "You hear crashing rock.",
        "You die...",

        "Dumb move!  You strain a muscle.",
        "There is a sink here.",
        "You hear a chugging sound.",
        "There's some graffiti on the floor here.",
        "You can't go down here.",
        "The wand hits you!",

        "You materialize in a different location!",
        "You hear some noises in the distance.",
        "You are momentarily blinded by a flash of light!",
        "You hear a deafening roar!",
        "Wait!  There's something there you can't see!",
        "You hear bubbling water.",
        "You are suddenly very hot!",
        "You hear some noises.",
        "There is a doorway here.",
        "You can see again.",
        "Really step onto that magic trap?",
        "You can hear again.",
        "It misses!",
        "It bites!",
        "You kill it!",

    ];
}

